### ISSUE TITLE
Add to iran.dat List

### ISSUE THREAD

**Issue by Phoenix-999** [bootmortis/iran-hosted-domains#101]
Hi @bootmortis 
Please add these domain name to iran.dat please
They are online travel agencies
Thank you in advance 

Here is the List
--------------------------------
safarmarket.com
ticket-charter.com
ghasedak24.com
blitcharter.com
mrbilit.com
flightio.com
snapptrip.com
utravs.com
tikban.com
melicharter.com
digicharter.com
kishzoom.net
rahbal.com
melicharter.org
irtour.org
aracharter.com
charter1.net
melicharter.net
samtik.com
charter361.com
3click.com
amincharter.com
ticketarzan.com
mancharter.net
app.irancharter.mobi
simorgh24.com
ba-charter.com
sourtik.com
deltaban.com
charter724.vip
mellicharter.org
charter123.net
mahancharter.com
cheapcharter.net
eligasht.com
kish44.com

**Comment by FreestyleSasuke** [comment]
Hi @bootmortis 

Add these domains, I see many connection attempts to these domains from my semi-public server.

```
intrack.ir
webgozar.ir
```

My persian is lacking so I have no idea what these sites are.

**Comment by Phoenix-999** [comment]
Hi @SasukeFreestyle

`intrack.ir` is for Email marketing, SMS marketing and push marketing, Help businesses with AI marketing.
`webgozar.ir` It is a complete set of Persian web tools that are available to Iranian websites and blogs. however it comes with "403 - Forbidden: Access is denied." when I try to access Through Iranian ISP and  network.

Hope that helps

**Comment by bootmortis** [comment]
> Hi @bootmortis
> 
> Add these domains, I see many connection attempts to these domains from my semi-public server.
> 
> ```
> intrack.ir
> webgozar.ir
> ```
> 
> My persian is lacking so I have no idea what these sites are.

I believe it is best not to direct these domains as they may be on the block list of some users.

**Comment by bootmortis** [comment]
these domains are already in the list:
```
safarmarket.com
ghasedak24.com
mrbilit.com
flightio.com
snapptrip.com
utravs.com
tikban.com
melicharter.com
rahbal.com
melicharter.org
irtour.org
melicharter.net
samtik.com
3click.com
ticketarzan.com
simorgh24.com
sourtik.com
deltaban.com
mellicharter.org
charter123.net
mahancharter.com
eligasht.com
```

**Comment by Phoenix-999** [comment]
@bootmortis  Thank you for checking and updating.
Much appreciated
