### ISSUE TITLE
Make a full geosite.db / geosite.dat 

### ISSUE THREAD

**Issue by papampi** [bootmortis/iran-hosted-domains#102]
Since singbox only have support for one db file/url and also many users don't have knowledge to add this next to default geosite.dat:
Why not add a full geosite.dat and geosite.db from loyalsoldier with merged iran sites from iran-hosted-domains?

**Comment by bootmortis** [comment]
The main focus of this repository is on domains related to Iran. Merging multiple repositories could be accomplished in a separate repository.
