### ISSUE TITLE
How to add costum sites to geosite.db?

### ISSUE THREAD

**Issue by srezasm** [bootmortis/iran-hosted-domains#107]
How can I append some new sites to `geosite.db` file?

**Comment by bootmortis** [comment]
create .dat file first with this guide: https://github.com/bootmortis/iran-hosted-domains#create-dat-file-manually-tutorial

then run the following:
https://github.com/bootmortis/iran-hosted-domains/blob/685115795af66981457c00475f37d567dfdbffad/.github/workflows/main.yml#L81-L87
