### ISSUE TITLE
افزودن چند دامنه داخلی به لیست

### ISSUE THREAD

**Issue by liketolivefree** [bootmortis/iran-hosted-domains#108]
ممنون از زحمتهاتون.
چند تا دامنه ایرانی پیدا کردم که تو فهرست نبود:
anzalweb.ir
efatwa.ir
ensani.ir
forsatnet.ir
ganjoor.ir
iranbirdrecords.ir
iranianbirdingclub.com
it-planet.ir
majlis.ir
mirasmaktoob.ir
motarjemjournal.ir
online-health.ir
ostadpaz.com
parsiday.com
peykaregan.ir
poshtebammag.ir
prosody.ir
raykanet.com
sch.ir
text-mining.ir
delta3da.one
amaadnet.ir

**Comment by hawshemi** [comment]
دامنه های .ir رو میشه کلا دایرکت کرد به این صورت:
```
regexp:^.+\.ir$
```

این رو میتونید توی `v2rayn` و `v2rayng` و ... به لیست دایرکت ها اضافه کرد که کلا .ir رو دایرکت کنه.

**Comment by bootmortis** [comment]
برای دومین‌های غیر ir لطفا PR بدید.

**Comment by liketolivefree** [comment]
بله چشم. البته لابلای اینا 4 تا غیر ir هستا. گفتم یه وقت ناخاسته ازشون چشمپوشی نکنین.
ضمنا یه چیز عجیب. مگه قاعدتا نباید همه دامنه های ir داخل ایران باشن؟ یه دامنه هست به اسم karimiblog.ir که تو هلنده. مگه میشه همچین چیزی؟

**Comment by hawshemi** [comment]
بله غیر .ir هارو بررسی میکنم.
اصولا ما فرض میکنیم که .ir ها همه داخل ایران هاست میشن. ولی خب طبیعیه که بعضی وقت ها هم هاستشون خارج هست.

**Comment by liketolivefree** [comment]
متوجهم.
