### ISSUE TITLE
مسدود کردن سایت و ای پی های ای ایران روی xrayr

### ISSUE THREAD

**Issue by rahavard01** [bootmortis/iran-hosted-domains#109]
لطفا راهنمایی میکنید چطور روی xrayr میشه این کار رو انجام داد؟
من پنل v2board دارم و با xrayr سرورهارو میارم روی پنل، اما هرچی گشتم آموزشی نیست که چطور میتونم سایت و ایپی های ایران رو بلاک کنم

**Comment by Ali-Flt** [comment]
شما README رو خوندید؟ 

این بخش بهتون کمک نمیکنه؟
![image](https://github.com/bootmortis/iran-hosted-domains/assets/60854595/8dc9f35e-71ba-4858-8ea2-fca7c37f8870)

**Comment by rahavard01** [comment]
> شما README رو خوندید؟
> 
> این بخش بهتون کمک نمیکنه؟ ![image](https://user-images.githubusercontent.com/60854595/260314823-8dc9f35e-71ba-4858-8ea2-fca7c37f8870.png)

بله خوندم، تمامی مطالب برای تغییرات در xray هستش یا اعمال تغییرات روی پنل xui هست. من هنوز نتونستم این کار رو روی پنل v2board یا روی xrayr انجام بدم ، هیچ جایی تغییرات رو ننوشته چجوری باید اعمال کنیم. اگر اطلاعاتی توی این زمینه دارید ممنون میشم راهنمایی کنین

**Comment by bootmortis** [comment]
اگر امکانش هست آموزش ها و سوالات مرتبط با کانفیگ کردن لیست روی سرور رو در ریپوی توسعه دهنده‌ی خود سرور بپرسید.
این ریپو تمرکزش روی کلاین هاست و برای کانفیگ سرور صرفا ارجا داده به ریپوی دیگه همونطور که در readme هست.
