### ISSUE TITLE
حضور 35 دامنه در هر دو لیست

### ISSUE THREAD

**Issue by liketolivefree** [bootmortis/iran-hosted-domains#110]
این 35 دامنه هم تو لیست دایرکت ها هستن و هم تو لیست ریجکت ها
0098sms.com
adnegah.net
adsima.net
adwised.com
backority.ir
chabok.io
clickyab.com
deema.agency
eads.ir
kaprila.com
kimiaonline.com
landin.ir
magnetadservices.com
mahshar.com
mediaad.org
metrix.ir
mitranet.ir
mitrarank.ir
mootanroo.com
najva.com
netbina.com
newagahi.ir
persianrank.ir
popgozar.ir
popupplus.ir
pushe.co
sabavision.com
salamatism.com
tapsell.ir
tavoos.net
toppopup.com
utop.ir
vatanshop.com
wideads.com
zarpop.com

**Comment by bootmortis** [comment]
فکر نکنم مشکلی باشه اگر کسی از لیست تبلیغات برای ریجکت کردن استفاده کنه اولویت کلاینت ها با ریجکت هست.

**Comment by liketolivefree** [comment]
اوه، بله بله. درسته. حواسم نبود.
اول رول های ریجکت رو میخونه و اگر یک مورد سازگار پیدا کنه، خواندن رول ها رو متوقف میکنه.
