### ISSUE TITLE
Add these domains to the "ad list".

### ISSUE THREAD

**Issue by liketolivefree** [bootmortis/iran-hosted-domains#111]
این 197 دامنه ریجکتی از 2 منبع «مسترکیا» و «وب آموز» جمع شدن (تکراری هاشون همه حذف شده).
24d.ir
ad.technews-iran.com
adengine.telewebion.com
adexo.ir
adro.co
ads.akairan.com
ads.akaup.com
ads.alaatv.com
ads.beytoote.com
ads.dabi.ir
ads.farakav.com
ads.karzar.net
ads.safarme.ir
adskav.com
adverge.ir
advn.ir
adwised.azureedge.net
affili.ir
affiliate.digikala.com
affiliate.malltina.com
affilio.ir
affstat.digikala.com
amaroid.net
analysis.faradars.org
analyt.ir
analytic.magland.ir
analytics.aasaam.com
analytics.asiatech.ir
analytics.digikala.com
analytics.dunro.com
analytics.football360.ir
analytics.irancell.ir
analytics.nastooh.ir
analytics.plaza.ir
analytics.zoomit.ir
api.footballi.net
api.karpishe.com
api2.zoomit.ir
apm.bama.ir
apptracking.irancell.ir
ayyaar.ir
backlink.ir
behinava.com
behtarinseo.ir
boorantech.com
cashback.takhfifan.com
cayot.ir
cdn.onesignal.com
ck.chavosh.org
click.digiato.com
clickaval.com
congoro.com
congoro.ir
counter.mahanmusic.net
counter.toolsir.com
daartads.com
daneshin.ir
davedbux.ir
deemaagency.ir
denutility.com
dsp.aparat.com
error-tracking.arvancloud.com
farakav.com
farsbux.ir
fb-gw.bef.rest
geoip.imber.live
hantana.org
hiads.hidoctor.ir
intrack.ir
ipsite.ir
ir.mihanstore.net
jetbux.ir
kajads.com
l.24d.ir
linkfars.com
lnk.amaroid.net
metrix.behtarino.com
new-sentry.digikala.com
news-view-api.varzesh3.com
newswidget.net
offers.sapra.ir
on-click.ir
oscaranimation.in
p30rank.ir
pantatec.ae
partclick.ir
phonroid.com
pooye-ads.com
popina.ir
popunder.ir
promizer.com
publica.ir
radar.bayan.ir
rankirani.ir
rssbank.ir
rubika.ir
sabaidea.cloud
scripts-ads.s3.ir-thr-at1.arvanstorage.com
sentry.cafebazaar.org
sentry.footballiapp.com
sentry.hamravesh.com
sentry.malltina.com
sentry.namava.ir
sentry.quera.org
sentry-new.divar.ir
slideskin.ir
spellads.com
statsfa.com
system-notify.app
tabligheirani.ir
talapop.ir
tbli.ir
te1.ir
track.mailerlite.com
tracker.digikala.com
triboon.net
userfriendly.ir
video-view-api.varzesh3.com
vidomusic.org
web.webpushs.com
xjs.lol
xmlx.lol
yekbux.com
yektanet.com
yelloadwise.ir
zarpop.ir
aitrades.com
artanlife.club
aryacoin.io
aryana.io
asaccoin.com
axotrade.com
bahatoken.site
bemchain.io
bixbcoin.com
bnbmatrix.io
bridge.link
coinohit.com
coinstwf.com
coinwallet.biz
cryptoland.com
dagcoin.org
defigroups.com
espadannet.ir
frzss.com
guhtoken.org
hamyarminer.net
healour.com
ai.marketing
arongroups.co
coinsmining.energy
dedino.ir
emway.ir
general.tradings.ir
gpm.ltd
liyamtoken.com
mrdigicoin.io
wiseling.com
ww1.traderbully.com
coin-hash.com
ecompanypoll.com
persia.exchange
soodland.com
teeth1.info
unifunds.com
yoozbit.com
impero.solutions
irancloudmining.com
irancoinmine.com
kingmoney.io
laqira.io
leumia.io
minepi.com
mtabdil.com
mttcoin.com
nokontoken.com
portal.gpm.ltd
propertiq.io
quahl.com
shamining.com
smartgalaxy.finance
synchrobit.io
tastenfts.com
utbyte.io
waykingroup.com
wintap.io
behkamcoin.com
bixb.exchange
denatoken.com
excoino.com
farda.exchange
icbroker.com
imsmining.com
orbitnetwork.net
pcoinglobal.com
ratinbank.com
treenvest.com

**Comment by bootmortis** [comment]
تعداد دومین ها زیاد هست
اگر امکانش هست PR بزنید

**Comment by liketolivefree** [comment]
به روی چشم

**Comment by MasterKia** [comment]
> این 197 دامنه ریجکتی از منبع «مسترکیا»

فورک "[Iran Hosted Domains + PersianBlocker](https://github.com/MasterKia/iran-hosted-domains/)" رو برای این ناچار شدم بزنم که @bootmortis [نمی‌خواست در لایسنس AGPLv3 مشکلی به وجود بیاد](https://github.com/bootmortis/iran-hosted-domains/issues/27). اگه قرار هست لایسنس لیست این‌طوری دور زده بشه خب مستقیم از خود [PersianBlocker](https://github.com/MasterKia/PersianBlocker) توی پروژه کنونی استفاده کنید تا هممون راحت‌تر کنار هم زندگی کنیم.

من همچنان هم موافق استفاده مستقیم از لیست PersianBlocker توی لیست شما هستم (حتی با وجود تداخل لایسنس‌ها) -- فقط توی README یه attribute انجام بدید کافیه.

cc @bootmortis

**Comment by bootmortis** [comment]
به خط اول دقت نکردم الان دیدم منبع رو ممنون بابت اطلاع رسانی
