### ISSUE TITLE
how did you generated iran.dat file

### ISSUE THREAD

**Issue by qfewzz** [bootmortis/iran-hosted-domains#118]
how did you generated iran.dat file? I read the code and couldn't file the the part you generated iran.dat file.

**Comment by bootmortis** [comment]
This was generated through GitHub Actions:
https://github.com/bootmortis/iran-hosted-domains/blob/9936fefe074e13a3bd8c6416e25ae5baa4f73265/.github/workflows/main.yml#L63-L76

To see the full manual, please refer to the following link:
https://github.com/bootmortis/iran-hosted-domains#create-dat-file-manually-tutorial
