### ISSUE TITLE
استفاده در سابکریپشن لیست surfboard

### ISSUE THREAD

**Issue by Mhosseinn** [bootmortis/iran-hosted-domains#119]
سلام وقت بخیر
ممنون بابت زحمات شما
برای نرم افزار surfboard یه مشکلی دارم . کدی که دادید فقط برای وقتی هست که پروفایل قابل ویرایش باشه
وقتی مثلا یه سابسکرایب تعریف میکنیم ما دسترسی به کدش نداریم که بتونیم کد شما رو ادد کنیم
راهی هست مثل v2rayng یه بار قوانین رو برای کل پروفایل ها تعریف کرد؟
تو تنظیمات یه external resource هست ولی نمیدونم چطور باید ازش استفاده کرد
ممنون میشم راهنمایی بفرمایید

**Comment by Tirbod** [comment]
خود surfboard قابلیتی نداره که برای همه پروفایل ها قوانین تعریف کرد و اون External resources برای کنترل و آپدیت منابعی که تو پروفایل ها ازشون استفاده شده.
 اگه پروفایلی که به صورت سابسکریپشن اضافه کردید را نمیخواید آپدیت کنید میتونید clone اش کنید قابل ادیت میشه ولی اگه میخواید آپدیتش کنید و فقط لیست سرور هاش براتون مهمه میتونید یه پروفایل خودتون بسازید و یه گروه پروکسی تعریف کنید و با `policy-path` لیست سرورای پروفایلی که میخواید رو به پروفایلیتون اضافه کنید و از طریق همون `External resources>Policy Path` اپدیت کنید لیست سرور هارو:

```
[Proxy Group]
GroupName = select, policy-path=url
```
اون url همون لینک سابسکریپشن پروفایل را وارد کنید سرور هارو خودش جدا میکنه.
