### ISSUE TITLE
beacons5.gvt3.com:443 [http -> proxy]

### ISSUE THREAD

**Issue by carbon248** [bootmortis/iran-hosted-domains#120]
### beacons5.gvt3.com
please take a look at this;

2023/08/17 18:48:22 127.0.0.1:10356 accepted //beacons5.gvt2.com:443 [http -> block]
2023/08/17 18:48:22 127.0.0.1:10357 accepted //beacons5.gvt3.com:443 [http -> proxy]

looks like the beacons5.gvt3.com:443 should be in the block list.
thanks.

**Comment by bootmortis** [comment]
We are not maintaining and focusing on blocklists. However, the domain you mentioned, "gvt3.com", is not related to Iran (It is owned by [google](https://www.netify.ai/resources/domains/gvt3.com)), so it's not included in our repository. Please use additional blocklists like [v2fly](https://github.com/v2fly/domain-list-community).

**Comment by Chocolate4U** [comment]
This domain along with gvt1.com and gvt2.com are for android updates for some devices such as google pixels and should not get blocked.
If you want to block foreign advertisement domains with low to none false positive, you can check out my repository:
[Iran-v2ray-rules](https://github.com/Chocolate4U/Iran-v2ray-rules)  
`geosite:ads` blocks both persian and foreign advertisement domains.

**Comment by carbon248** [comment]
> This domain along with gvt1.com and gvt2.com are for android updates for some devices such as google pixels and should not get blocked. If you want to block foreign advertisement domains with low to none false positive, you can check out my repository: [Iran-v2ray-rules](https://github.com/Chocolate4U/Iran-v2ray-rules) `geosite:ads` blocks both persian and foreign advertisement domains.

I've checked your repository. thank you for the good work. As I'm not an expert, I'm gonna ask how to apply it on V2rayN if possible.

**Comment by Chocolate4U** [comment]
> > This domain along with gvt1.com and gvt2.com are for android updates for some devices such as google pixels and should not get blocked. If you want to block foreign advertisement domains with low to none false positive, you can check out my repository: [Iran-v2ray-rules](https://github.com/Chocolate4U/Iran-v2ray-rules) `geosite:ads` blocks both persian and foreign advertisement domains.
> 
> I've checked your repository. thank you for the good work. As I'm not an expert, I'm gonna ask how to apply it on V2rayN if possible.

sorry for late reply, i did not see this. just copy and replace `geoip.dat` and `geosite.dat` to `v2rayN\bin` directory and `geoip.db` and `geosite.db` to `v2rayN\guiConfigs` directory. Also remember to set `Automatic update interval of Geo (hours)` to `0` to avoid geo files getting replaced by original files. Then go to `RoutingSetting > Advanced Function > Add > Rule Add` , set `outboundTag` to `direct`  and add `geosite:ir` to Domain section and `geoip:ir` to IP section and click Confirm. redo this process for `outboundTag` set to `block` with `geosite:ads` or other categories like `geosite:malware` (each on separate line) in Domain section.
I will write a detailed guide with screenshots on this later when i was free.
If you need further assistance, please open an issue in respective repository.
