### ISSUE TITLE
مشکل shadowroucket

### ISSUE THREAD

**Issue by miladrajabi2002** [bootmortis/iran-hosted-domains#121]
از اخرین ورژن استفاده یکنم با shadowroucket اشتباه direct میکنه
![photo_2023-08-19_23-14-15](https://github.com/bootmortis/iran-hosted-domains/assets/51949453/9a18180e-f9ba-4cf8-ba6f-20d680dc0727)

https://thugiping.info

این سایت فیلتر هستش ولی direct میکنه

**Comment by bootmortis** [comment]
طبق شاتی که دادید بنظر میاد از روی geoip تشخیص داده باید دایرکت بشه
به ریپوی ما که فقط دامنه هست ربطی نداره فکر کنم

اگر امکانش هست تنظیمات DNS رو روی گوگل یا کلود فلیر ست کنید ببینید مشکل حل میشه یا خیر

- google:
  - `8.8.8.8`
  - `8.8.4.4`
- cloudflare:
  - `1.1.1.1`
  - `1.0.0.1`

**Comment by miladrajabi2002** [comment]
توی قسمت dns override گذاشتم هر جفتشو تست کردم ولی تغییری نکرد

**Comment by miladrajabi2002** [comment]
این مشکل حل نشد؟

**Comment by Tirbod** [comment]
این مشکل ربطی به کانفیگی که استفاده میکنید نداره و مربوط به دیتابیس geoip که shadowrocket استفاده میکنه .برا حل مشکلم میتونید از یه دیتابیس دیگه استفاده کنید. برای تغییرش برید قسمت تنظیمات بعد قسمت GeoLite2 Database، بعد قسمت Country > URL لینک فایل mmdb  یا db را وارد کنید بعد بزنید Update تا جایگزین بشه برای برگشت به حالت قبل هم reset. 
چندتا جایگزینی که میتونید استفاده کنید:

[Clash](https://github.com/Dreamacro/maxmind-geoip):
`https://github.com/Dreamacro/maxmind-geoip/raw/release/Country.mmdb`
[Meta](https://github.com/MetaCubeX/meta-rules-dat):
`https://github.com/MetaCubeX/meta-rules-dat/raw/release/country.mmdb`
[Loyalsoldier](https://github.com/Loyalsoldier/geoip):
`https://github.com/Loyalsoldier/geoip/raw/release/Country.mmdb`
