### ISSUE TITLE
افزودن سورس: لیست تحریم

### ISSUE THREAD

**Issue by mmrabbani** [bootmortis/iran-hosted-domains#122]
هر شرکتی که آمریکا تحریم میکنه، مجبور هست که سایتش را داخل ایران نگه دارد. چون هیچ هاست خارجی به او سرویس نمی‌دهد.
حالا میتوان از این موضوع استفاده کرد و از لیست تحریم، هر کدام که مربوط به ایران بود، سایتشان را در لیست قرار داد.
لیست شرکت های تحریم شده در همه فرمت ها از جمله csv و xml قابل دانلود است
https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schemas

**Comment by mmrabbani** [comment]
اگه حوصله اتوماتیک کردن استخراج از لیست رو ندارید، من لیست رو بررسی کردم و ۱۸۰ تا دامین جدید داخلش وجود داره. میتونید همین لیست رو اضافه کنید. طبیعتا این لیست هر روز تغییرات زیادی نداره
[SDN-new.xlsx](https://github.com/bootmortis/iran-hosted-domains/files/12446750/SDN-new.xlsx)

**Comment by bootmortis** [comment]
ممنون
در اولین فرصت اضافه می‌کنم الان وقت ندارم
اگر کس دیگه‌ای می‌تونه اضافه کنه خوشحال می‌شم PR بزنه

**Comment by bootmortis** [comment]
لیست رو بررسی کردم
دومین غیر ایرانی زیاد هست حتی تو لیستی که شما هم فرستادید زیاده مثل 
![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/677c7591-d6e6-4030-96e9-f4acfd3b8139)


تا روشی دقیق و مشخص برای پیدا کردن دومین‌هایی که مستقیما مربوط به ایران هستن پیدا نشه ایشو رو میبندم

این کدی بود که تا اینجا روش کار کردم:
```python
def sdn() -> Iterable[str]:
    rsp = requests.get(consts.sdn_url)
    rsp.raise_for_status()

    text = rsp.text
    text = text.splitlines()

    urls = []
    for line in text:
        if 'iran' in line.lower():
            urls.extend(re.findall(r'Website (.+?);', line))

    # remove all russia, china, cuba, north korea, syria, venezuela, zimbabwe, belarus domains
    urls = filter(lambda x: not re.search(r'\.(ru|cn|cu|kp|sy|ve|zw|by)', x), urls)

    return list(set(urls))
```
