### ISSUE TITLE
حذف دامنه های اضافی

### ISSUE THREAD

**Issue by mmrabbani** [bootmortis/iran-hosted-domains#123]
سلام
حدودا ۱۰ درصد دامین های لیست برای خرید آزاد هستند. یعنی مالک آنها دامنه خود را در اینماد یا سایت های نیم بها یا ... ثبت کرده، ولی بعدا آن را تمدید نکرده است.

حالا میتوان دو روش برای حذف آن داشت. یکی استفاده از API چک کردن آزاد بودن دامنه و دیگری چک کردن دستی. مثلا من ۱۰ هزار دامنه اول غیر IR رو در سایت گوددی در
آدرس زیر چک کردم و حدود هزار دامنه آزاد پیدا کردم که در این درخواست پیوست کردم.
https://www.godaddy.com/domains/bulk-domain-search
لیست ۱۰۰۰ دامنه از ۱۰۰۰۰ دامنه چک شده
[mc-free domains of first 10k domains.ods](https://github.com/bootmortis/iran-hosted-domains/files/12446757/mc-free.domains.of.first.10k.domains.ods)

حالا اینکار چه فایده داره؟ برای بیشتر موبایل ها یا کامپیوترهایی که توان پردازشی کافی دارند تاثیر کمی داره. ولی برای دستگاه های با توان پایین مثل روترها باعث افزایش سرعت میشه. حتی برای کامپیوترها هم بعضی برنامه ها مثل warp یا foxyproxy محدودیت تعداد دامنه دارند و کوچکتر بودن لیست می‌تونه به اونها هم کمک کنه.

اگر تصمیم گرفتید این issue را از طریق دستی اجرا کنید، من میتونم بقیه دامنه ها را چک کنم. البته گوددی دامنه های ir رو پشتیبانی نمیکنه

**Comment by mmrabbani** [comment]
شاید نشه API مناسب و رایگان پیدا کرد که بتونه به صورت اتوماتیک این تعداد دامنه رو چک کنه. یه راه که به ذهنم رسید DNS query برای دامنه مورد نظر هست. اگر پاسخی گرفته نشد یعنی یا چنین دامنه ای مالک ندارد یا مالک آن چیزی روی آن بارگزاری نکرده است. چنین کاری قابل اتوماتیک کردن هم هست.

**Comment by bootmortis** [comment]
سلام
به صورت دستی که امکانش نیست چون لیست داینامیکه
به صورت اتومات راه حل DNS هم زیاد قابل اعتماد نیست و همینطور کوئری گرفتن حدود ۹۶ هزار دامنه روی اکشن گیتهاب کار جالبی نیست

ایشو رو باز می‌زارم اگر کسی راه حلی داشت بحث بشه

**Comment by Chocolate4U** [comment]
راجع به این موضوع، من یه اسکریپت نوشتم که دامنه ها رو بر اساس 4 روش مختلف بررسی میکنه. [Domain-Health-Checker](https://github.com/Chocolate4U/Domain-Health-Checker)
بهترین روش که دیفالت اسکریپت هم هست اینه که یه کانکشن TCP روی پورت 80 با سرور وبسایت مورد نظر ایجاد کنی، اگر موفقیت آمیز بود یعنی دامنه فعاله در غیر اینصورت دامنه به اصطلاح مرده. مسلما این تست باید با IP ایران انجام بشه، چون بعضی از سایت ها ایران اکسس هستن و با IP خارج از کشور به کانکشن پاسخی نمیدن.
روش DNS هم همونطور که گفته شد زیاد دقیق نیست چون بعضی رجیسترار ها برای دامنه های پارک شده هم رکورد DNS میفرستن در حالی که اون دامنه اصلا فعال نیست و یا دامنه های غیرفعال پشت CDN . البته با این روش میشه با IP خارج از کشور هم دامنه ها رو تست کرد. فقط نسبت به روش اول false-positive بیشتری داره. توی اسکریپت هم با DNS غیر رمزنگاری شده و هم DNS-over-HTTPS میشه این تست رو انجام داد که خب DOH قابل اعتماد تره.
یه راه دیگه هم ارسال Ping به سرور مورد نظره که بازم زیاد قابل اعتماد نیست چون بعضی سایت ها کلا Ping رو غیرفعال میکنن. این تست هم باید با IP ایران باشه فقط.
من با همین اسکریپت با روش TCP دامنه ها رو (به علاوه سورس iwmf) چک کردم که حدود 28 هزارتا دامنه مرده توشون وجود داشت که عملا میشه 25 درصد لیست. نتایج هم توی این gist میزارم. [Results-TCP.csv](https://gist.github.com/Chocolate4U/2d1cf666c6ab90ba344e18322a9ebd5a)
با سخت افزار خوب و اینترنت استیبل و پرسرعت با concurrency 100 (تست 100 دامنه همزمان) به بالا کل تست بین 5 الی 15 دقیقه طول میکشه.(برای 112000 تا دامنه)

**Comment by mmrabbani** [comment]
> راجع به این موضوع، من یه اسکریپت نوشتم که دامنه ها رو بر اساس 4 روش مختلف بررسی میکنه. [Domain-Health-Checker](https://github.com/Chocolate4U/Domain-Health-Checker) بهترین روش که دیفالت اسکریپت هم هست اینه که یه کانکشن TCP روی پورت 80 با سرور وبسایت مورد نظر ایجاد کنی، اگر موفقیت آمیز بود یعنی دامنه فعاله در غیر اینصورت دامنه به اصطلاح مرده. مسلما این تست باید با IP ایران انجام بشه، چون بعضی از سایت ها ایران اکسس هستن و با IP خارج از کشور به کانکشن پاسخی نمیدن. روش DNS هم همونطور که گفته شد زیاد دقیق نیست چون بعضی رجیسترار ها برای دامنه های پارک شده هم رکورد DNS میفرستن در حالی که اون دامنه اصلا فعال نیست و یا دامنه های غیرفعال پشت CDN . البته با این روش میشه با IP خارج از کشور هم دامنه ها رو تست کرد. فقط نسبت به روش اول false-positive بیشتری داره. توی اسکریپت هم با DNS غیر رمزنگاری شده و هم DNS-over-HTTPS میشه این تست رو انجام داد که خب DOH قابل اعتماد تره. یه راه دیگه هم ارسال Ping به سرور مورد نظره که بازم زیاد قابل اعتماد نیست چون بعضی سایت ها کلا Ping رو غیرفعال میکنن. این تست هم باید با IP ایران باشه فقط. من با همین اسکریپت با روش TCP دامنه ها رو (به علاوه سورس iwmf) چک کردم که حدود 28 هزارتا دامنه مرده توشون وجود داشت که عملا میشه 25 درصد لیست. نتایج هم توی این gist میزارم. [Results-TCP.csv](https://gist.github.com/Chocolate4U/2d1cf666c6ab90ba344e18322a9ebd5a) با سخت افزار خوب و اینترنت استیبل و پرسرعت با concurrency 100 (تست 100 دامنه همزمان) به بالا کل تست بین 5 الی 15 دقیقه طول میکشه.(برای 112000 تا دامنه)

ممنون. خیلی کار تمیزی انجام دادی و این کار لیست رو خیلی تمیز میکنه. یه ایده دیگه برای تمیزتر کردن لیست هست. ببین اگر راحت هست میتونی به پروژه ات اضافه کنی. وقتی اینطوری دامنه ها رو چک میکنی، IP پشت دامنه ها رو هم بدست میاری. حالا اگه IP whois استفاده کنی میتونی دامنه هایی که دیگه ایران نیستند رو هم شناسایی و حذف کنی. متاسفانه هیچ لیست دقیق و قابل اعتمادی از IP های ایران وجود نداره. ولی مالک IP در IP whois دقیق هست. کافیه چندین cloud provider معروف (آمازون، آژور، کلودفلر، OVH، گوگل، فستلی، آکامای، هاستینگر، IONS) رو در نظر بگیری به عنوان IP های خارج. چون اکثر سایت ها از همین چندتا سرویس میگیرند، خارجی هایی که باقی میمونند نباید زیاد باشند.

**Comment by mmrabbani** [comment]
> 



> با سخت افزار خوب و اینترنت استیبل و پرسرعت

مشکل اینترنت صرفا سرعت و پایداری نیست. به دلیل اشکالات فیلترینگ، ممکنه کانکشن TCP برقرار نشه. این مشکل برای روش DNS هم وجود داره. راه حل اینه که دو سه بار در زمان‌های مختلف اجرا بشه و اشتراکش در نظر گرفته بشه.

**Comment by Chocolate4U** [comment]
> > راجع به این موضوع، من یه اسکریپت نوشتم که دامنه ها رو بر اساس 4 روش مختلف بررسی میکنه. [Domain-Health-Checker](https://github.com/Chocolate4U/Domain-Health-Checker) بهترین روش که دیفالت اسکریپت هم هست اینه که یه کانکشن TCP روی پورت 80 با سرور وبسایت مورد نظر ایجاد کنی، اگر موفقیت آمیز بود یعنی دامنه فعاله در غیر اینصورت دامنه به اصطلاح مرده. مسلما این تست باید با IP ایران انجام بشه، چون بعضی از سایت ها ایران اکسس هستن و با IP خارج از کشور به کانکشن پاسخی نمیدن. روش DNS هم همونطور که گفته شد زیاد دقیق نیست چون بعضی رجیسترار ها برای دامنه های پارک شده هم رکورد DNS میفرستن در حالی که اون دامنه اصلا فعال نیست و یا دامنه های غیرفعال پشت CDN . البته با این روش میشه با IP خارج از کشور هم دامنه ها رو تست کرد. فقط نسبت به روش اول false-positive بیشتری داره. توی اسکریپت هم با DNS غیر رمزنگاری شده و هم DNS-over-HTTPS میشه این تست رو انجام داد که خب DOH قابل اعتماد تره. یه راه دیگه هم ارسال Ping به سرور مورد نظره که بازم زیاد قابل اعتماد نیست چون بعضی سایت ها کلا Ping رو غیرفعال میکنن. این تست هم باید با IP ایران باشه فقط. من با همین اسکریپت با روش TCP دامنه ها رو (به علاوه سورس iwmf) چک کردم که حدود 28 هزارتا دامنه مرده توشون وجود داشت که عملا میشه 25 درصد لیست. نتایج هم توی این gist میزارم. [Results-TCP.csv](https://gist.github.com/Chocolate4U/2d1cf666c6ab90ba344e18322a9ebd5a) با سخت افزار خوب و اینترنت استیبل و پرسرعت با concurrency 100 (تست 100 دامنه همزمان) به بالا کل تست بین 5 الی 15 دقیقه طول میکشه.(برای 112000 تا دامنه)
> 
> ممنون. خیلی کار تمیزی انجام دادی و این کار لیست رو خیلی تمیز میکنه. یه ایده دیگه برای تمیزتر کردن لیست هست. ببین اگر راحت هست میتونی به پروژه ات اضافه کنی. وقتی اینطوری دامنه ها رو چک میکنی، IP پشت دامنه ها رو هم بدست میاری. حالا اگه IP whois استفاده کنی میتونی دامنه هایی که دیگه ایران نیستند رو هم شناسایی و حذف کنی. متاسفانه هیچ لیست دقیق و قابل اعتمادی از IP های ایران وجود نداره. ولی مالک IP در IP whois دقیق هست. کافیه چندین cloud provider معروف (آمازون، آژور، کلودفلر، OVH، گوگل، فستلی، آکامای، هاستینگر، IONS) رو در نظر بگیری به عنوان IP های خارج. چون اکثر سایت ها از همین چندتا سرویس میگیرند، خارجی هایی که باقی میمونند نباید زیاد باشند.

> 

متاسفانه این کار شدنی نیست، اول اینکه سرور های whois رایگان به شدت rate limit سخت گیرانه ای دارن و امکان نداره این همه دامنه رو توی مدت کوتاه بدون بن شدن بتونی کوئری بگیری. API های 3rd party هم رایگان نیستن و هزینه بالایی دارن.
دوم اینکه خیلی از همین سایت های داخل از CDN های خارجی استفاده میکنن و به دست آوردن IP سرورشون ممکن نیست، مثلا ممکنه سرور داخل ایران باشه اما پشت کلودفلر
همین سایت `iwmf.ir` رو در نظر بگیر:
```
whois iwmf.ir
% This is the IRNIC Whois server v1.6.2.
% Available on web at http://whois.nic.ir/
% Find the terms and conditions of use on http://www.nic.ir/
%
% This server uses UTF-8 as the encoding for requests and responses.

% NOTE: This output has been filtered.

% Information related to 'iwmf.ir'


domain:         iwmf.ir
ascii:          iwmf.ir
nserver:        blakely.ns.cloudflare.com
nserver:        norm.ns.cloudflare.com
source:         IRNIC # Filtered
```
اصلا هیچ اطلاعات به درد بخوری ازش درنمیاد جز اینکه پشت کلودفلره. اگر IP ها رو هم بخوای resolve کنی:
```
dig iwmf.ir +short
188.114.96.3
188.114.97.3
```
که باز هم جفتشون IP کلودفلر هستن و بسته به زمان کوئری ممکنه IP متفاوتی برگردونده بشه.
مثال دیگه سایت `www.bazicenter.com` هست. این سایت هم سرورش هتزنر هست و کارهای بالا رو هم انجام بدی فقط به IP های هتزنر میرسی
حالا آیا اینجور دامنه ها باید حذف بشن؟ به نظر من نه. درسته که پشت CDN خارجی هستن و یا سرورشون خارج از کشوره و در یک کلام ایران اکسس نیستن، اما هنوز هم سایت های **ایرانی فارسی زبان مجاز** هستن که از داخل ایران قابل دسترسن. همچنین هر لحظه ممکنه سرورشون رو بیارن ایران یا از CDN های ایرانی استفاده کنن.

> > 
> 
> > با سخت افزار خوب و اینترنت استیبل و پرسرعت
> 
> مشکل اینترنت صرفا سرعت و پایداری نیست. به دلیل اشکالات فیلترینگ، ممکنه کانکشن TCP برقرار نشه. این مشکل برای روش DNS هم وجود داره. راه حل اینه که دو سه بار در زمان‌های مختلف اجرا بشه و اشتراکش در نظر گرفته بشه.

آره اصولا اینجور تست ها زیاد دقیق نیستن چون به شرایط مختلف زیادی بستگی دارن، اما بله یکی از راه هاش برای دقیق شدن نسبی همینه که شما گفتی + تایم اوت بالا که خب زمان تست رو میبره بالا.
در ضمن کلا برای همچین کاری نیازه که مرتبا و هر روز این تست ها انجام و نتایج آپدیت بشه، که برای این ریپو که هفتگی آپدیت میشه اصلا مناسب نیست.

**Comment by bootmortis** [comment]
> با سخت افزار خوب و اینترنت استیبل و پرسرعت با concurrency 100 (تست 100 دامنه همزمان) به بالا کل تست بین 5 الی 15 دقیقه طول میکشه.(برای 112000 تا دامنه)

مرسی از روشی که گفتی، شدنی هست ولی برای این ریپو ارزش نداره. بیشتر پردازش این ریپو روی اکشن گیتهاب هست. تنها چیزی که خارج از ریپو پردازش می‌شه میرور مربوط به ITO هست که اون جداگانه تو یک روز مجزا از اپدیت این ریپو داره اپدیت میشه. ولی برای حذف دومین باید همزمان بلافاصله بعد از اکشن گیتهاب باشه که داره دومین هارو سر جمع میکنه و خب شدنی نیست مگر اینکه یک روش خودکار بشه براش نوشت. مزیت این ریپو همین سیستم اپدیت خودکارشه و اگر قراره چیزی به صورت دستی صورت بگیره بهتره توی فورک مجزا توسعه داده بشه.

**Comment by Chocolate4U** [comment]
> > با سخت افزار خوب و اینترنت استیبل و پرسرعت با concurrency 100 (تست 100 دامنه همزمان) به بالا کل تست بین 5 الی 15 دقیقه طول میکشه.(برای 112000 تا دامنه)
> 
> مزیت این ریپو همین سیستم اپدیت خودکارشه

چک کردن DNS رکورد دامنه ها رو میشه اتومات کرد روی اکشن گیت هاب (مثل [اینجا](https://github.com/Chocolate4U/Iran-v2ray-rules/blob/main/.github/workflows/findredundant.yml) که برای `geosite-lite` استفاده میشه توی اون ریپو)، دقت کمترش توی اینه که به اندازه TCP نمیتونه دامنه های غیرفعال رو حذف کنه، ولی بازهم تعداد قابل توجهی از دامنه ها حذف میشن. فقط همونجوری که گفتم اینجور تست ها زیاد دقیق نیستن و برای fail-proof کردنش بهتره هر روز دامنه ها تست بشن که برای این ریپو که هفتگی آپدیت میشه زیاد مناسب نیست، مگر اینکه ریلیز به روزانه تغییر کنه

**Comment by bootmortis** [comment]
> مگر اینکه ریلیز به روزانه تغییر کنه

چون میرور ITO هفتگی اپدیت میشه معنی نداره این کار. 
بنظر من مناسب تر این هست که یک حالت lite طور فورک بخوره از ریپو و اونجا حذف بشه

**Comment by MasterKia** [comment]
اگه بنابر فورک هست برای این‌که جلوی پراکندگی بیش از حد گرفته بشه پیشنهاد می‌کنم تغییرات رو به اینجا بفرستید:
https://github.com/MasterKia/iran-hosted-domains/

**Comment by Chocolate4U** [comment]
> > مگر اینکه ریلیز به روزانه تغییر کنه
> 
> چون میرور ITO هفتگی اپدیت میشه معنی نداره این کار. بنظر من مناسب تر این هست که یک حالت lite طور فورک بخوره از ریپو و اونجا حذف بشه



> اگه بنابر فورک هست برای این‌که جلوی پراکندگی بیش از حد گرفته بشه پیشنهاد می‌کنم تغییرات رو به اینجا بفرستید: https://github.com/MasterKia/iran-hosted-domains/

به نظرم بیشتر هدف این بود که به این مخزن، به عنوان سورس اصلی، این مورد اضافه بشه. وگرنه اگر قرار بر فورک جداگانه هست که خب من ریپو جداگانه زدم و این مورد اونجا [هندل](https://github.com/Chocolate4U/Iran-v2ray-rules#geosite-lite) شده، اضافه کردن این مورد توی یه فورک دیگه یه جورایی دوباره کاری میشه و جز پیچیده شدن و پراکندگی دستاورد دیگه ای نداره.

**Comment by Chocolate4U** [comment]
حالا که بحث سبک شدن لیست هست، به نظرم که کار قشنگ دیگه میتونه این باشه که کلا دامنه های `ir.` رو از لیست حذف کنید و فقط این دو مورد رو به `iran.dat:ir` اضافه کنید
```
ir
xn--mgba3a4f16a # .ایران
```
از اونجایی که هر دامنه ای به صورت `xx.yy.ir` عملا یک ساب دومین از `ir.` حساب میشه، همین دو مورد تمامی دامنه های با TLD های ایران رو بایپس میکنه و دیگه نیازی به استفاده از regular expression هم توی کلاینت ها نیست. توی ریپو [domain-list-community](https://github.com/v2fly/domain-list-community) هم به همین صورت هست [cn](https://github.com/v2fly/domain-list-community/blob/master/data/cn)  [tld-cn](https://github.com/v2fly/domain-list-community/blob/master/data/tld-cn)
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
اگر اوکی هست که PR بدم

**Comment by bootmortis** [comment]
> حالا که بحث سبک شدن لیست هست، به نظرم که کار قشنگ دیگه میتونه این باشه که کلا دامنه های `ir.` رو از لیست حذف کنید و فقط این دو مورد رو به `iran.dat:ir` اضافه کنید

تو تمام ورژن ها این حالت ساپورت می‌شه؟

**Comment by Chocolate4U** [comment]
> > حالا که بحث سبک شدن لیست هست، به نظرم که کار قشنگ دیگه میتونه این باشه که کلا دامنه های `ir.` رو از لیست حذف کنید و فقط این دو مورد رو به `iran.dat:ir` اضافه کنید
> 
> تو تمام ورژن ها این حالت ساپورت می‌شه؟

بله، هم هسته v2ray و هم هسته sing-box به طور ساختاری از این قابلیت پشتیبانی میکنن (چون واقعا چیز خاصی هم نیست و مثل یه ساب دامین باهاش برخورد میشه). تو همه کلاینت های این دوتا هسته هم تست کردم و هیچ مشکلی با بایپس کردن دامنه های `ir.` نداشتن.

**Comment by mmrabbani** [comment]
حذف دامنه های ir فایل رو کوچک میکنه. ولی ارزشی که قرار بود ایجاد کنه (امکان استفاده در دستگاه‌های ضعیف و نرم افزارهای دارای محدودیت) رو ایجاد نمیکنه. چون همین الان هم دسته ir و  other جدا هست و کاربر میتونه فقط دسته other به علاوه کل دامنه های ir رو انتخاب کنه. اینجوری حتی دامنه های ir که بعدا ساخته میشن هم توی روتینگ قرار میگیرند.
اگر میشد دسته other را کوچک کرد ارزش بیشتری ایجاد میشد. مثلا یکی از روش‌های پیشنهادی @Chocolate4U صرفا روی دسته other پیاده میشد و اینطوری توان محاسباتی مورد نیاز نصف میشد. چون نصف دامنه های لیست ir هستند.

**Comment by MasterKia** [comment]
> من ریپو جداگانه زدم و این مورد اونجا [هندل](https://github.com/Chocolate4U/Iran-v2ray-rules#geosite-lite) شده


پس پراکندگی از قبل رخ داده.

فورک Iran-Hosted-Domains+PersianBlocker رو کاربران لیست PersianBlocker دارن ازش در حال حاضر استفاده می‌کنن.

**Comment by Chocolate4U** [comment]
> > من ریپو جداگانه زدم و این مورد اونجا [هندل](https://github.com/Chocolate4U/Iran-v2ray-rules#geosite-lite) شده
> 
> پس پراکندگی از قبل رخ داده.
> 
> فورک Iran-Hosted-Domains+PersianBlocker رو کاربران لیست PersianBlocker دارن ازش در حال حاضر استفاده می‌کنن.

البته بیشتر روی صحبتم در مورد فورک جدید بود، اگر که کاربران در حال حاضر دارن از اون فورک استفاده میکنن، اضافه کردن این مورد میتونه مفید باشه.
https://github.com/MasterKia/iran-hosted-domains/pull/1
سعی کردم چیزی رو تغییر ندم و فقط به صورت اضافه کردن باشه، تا در آینده برای merge از upstream به مشکل conflict بر نخورید.
لطفا بررسی کنید اگه مشکلی نداشت merge کنید.
با توجه به این که فورک شما هم به صورت هفتگی آپدیت میشه، اکیدا توصیه میکنم به روزانه تغییر بدین، چون ممکنه در یک روز دامنه ای به اشتباه حذف بشه، در این صورت تا هفته بعد به همون شکل باقی میمونه که اصلا خوب نیست.
اگر میخواید تست دامنه ها روی فورک خودتون انجام بشه، این [workflow](https://github.com/Chocolate4U/Iran-v2ray-rules/blob/main/.github/workflows/findredundant.yml) رو به فورکتون اضافه کنین و آدرس فایل `redundant-domains.txt` رو به تناسب در `main.yml` تغییر بدین.

**Comment by MasterKia** [comment]
براتون دعوت فرستادم، لطفاً قبولش کنید تا خودتون اگه خواستید بتونید انجام بدید.

**Comment by Chocolate4U** [comment]
> براتون درخواست فرستادم، لطفاً قبولش کنید تا خودتون اگه خواستید بتونید انجام بدید.

ممنون بابت دعوت، ریلیز رو تغییر دادم به روزانه.

**Comment by bootmortis** [comment]
بعد از بررسی با یک عده و مقایسه چند ریپوی دیگه که فایل هایی حدود ۵ مگابایتی داشتن، کل نهایت چیزی که ما اینجا به دست میاریم تبدیل فایل از ۲ مگ به ۱ مگه که تاثیر خاصی نداره در مقایسه با مثلا[ geoip عه حدود ۱۰ مگابایتی](https://github.com/v2fly/geoip/releases/tag/202309140037) 
در نتیجه این ایشو رو میبندم که بقیه ایشو ها بیشتر مورد توجه قرار بگیره
