### ISSUE TITLE
افزودن سورس: جشنواره وب و موبایل ایران

### ISSUE THREAD

**Issue by Chocolate4U** [bootmortis/iran-hosted-domains#124]
وبسایت [جشنواره وب و موبایل ایران](https://directory.iwmf.ir) حاوی تعداد زیادی دامنه ایرانی هست که تو لیست فعلی موجود نیست، اضافه کردن این دامنه ها میتونه به کامل تر شدن هرچه بیشتر لیست کمک کنه.
من این لیست رو استخراج کردم که در این مخزن در دسترسه. اگر خواستین از همین میتونین استفاده کنین [iwmf.ir-Mirror](https://github.com/Chocolate4U/iwmf.ir-Mirror)
بعد از مرتب کردن دامین ها، استانداردسازی و حذف ساب دامین ها
```
cat iwmf.csv | awk -F"," '{print $2}' | awk -F'//' '{print $2}' | rev | cut -d . -f -2 |  rev | sed '/^\s*$/d' | awk '{$1=$1};1' | dos2unix | idn2 --no-alabelroundtrip --no-tr46 | sort -u > iwmf.txt
```
و مقایسه با لیست فعلی و حذف تکراری ها
```
comm -23 iwmf.txt domains.txt > diff.txt
```
این لیست به دست اومد که حاوی 16095 دامنه هست که تو لیست فعلی موجود نیستن

[diff.txt](https://gist.github.com/Chocolate4U/d87a09293b898eee1d0c94a6731c3777)

**Comment by mmrabbani** [comment]
امکانش هست اینکه چنین دامنه ای وجود داره رو هم چک کنید؟ من یه تعدادی از دامنه های غیر ir رو از سایت زیر چک کردم و ۴۰ درصدشون آزاد بودند و یعنی مالک دامنه اونها رو تمدید نکرده
https://www.godaddy.com/domains/bulk-domain-search/
شاید یه راه راحت DNS check این دامنه ها باشه و اگر هیچ DNS ای براشون تنظیم نشده حذف بشوند.

**Comment by bootmortis** [comment]
ممنون
لیست خوبیه
فقط الان فرصت اضافه کردن ندارم تا یک ماه دیگه
اگر امکانش هست PR بدید اگر نه بعدا اضافه می‌کنم

**Comment by Chocolate4U** [comment]
> ممنون لیست خوبیه فقط الان فرصت اضافه کردن ندارم تا یک ماه دیگه اگر امکانش هست PR بدید اگر نه بعدا اضافه می‌کنم

#128

**Comment by Chocolate4U** [comment]
> امکانش هست اینکه چنین دامنه ای وجود داره رو هم چک کنید؟ من یه تعدادی از دامنه های غیر ir رو از سایت زیر چک کردم و ۴۰ درصدشون آزاد بودند و یعنی مالک دامنه اونها رو تمدید نکرده https://www.godaddy.com/domains/bulk-domain-search/ شاید یه راه راحت DNS check این دامنه ها باشه و اگر هیچ DNS ای براشون تنظیم نشده حذف بشوند.

https://github.com/bootmortis/iran-hosted-domains/issues/123#issuecomment-1703334074

**Comment by WickedSick277** [comment]
سلام، میخواستم ایشو جدید باز کنم گفتم شاید خیلی پخش و پلا بشه، اینکارو نکنم.
دو دامین کلا توی لیست نیستن:
konkur.in
konkur.us
