### ISSUE TITLE
اضافه کردن آی پی های کلودفلر 

### ISSUE THREAD

**Issue by smsalehi** [bootmortis/iran-hosted-domains#127]
وقتی پروکسی از نوع vless رو روی کلودفلر راه اندازی کنیم، سایت های پشت کلودفلر باز نمیشه(مگر اینکه تو ورکر پروکسی بشه). اگه IP های کلودفلر به geoip.db اضافه بشه، می تونیم از طریق روت bypass کنیم که دیگه سایت های پشت کلودفلر مستقیم باز بشه و از پروکسی عبور نکنه.
geoip:cloudflare
لیست IPهای کلودفلر

https://github.com/vfarid/cf-ip-scanner-py/blob/main/ipv4.txt
https://github.com/vfarid/cf-ip-scanner-py/blob/main/ipv6.txt

**Comment by bootmortis** [comment]
ریپوی ما تمرکزش روی ای پی ها و دومین های مرتبط با ایران هست
برای اینجور کاربرد ها فورک بزنید
