### ISSUE TITLE
استفاده از `ir` در فایل .dat 

### ISSUE THREAD

**Issue by bootmortis** [bootmortis/iran-hosted-domains#129]
حالا که بحث سبک شدن لیست هست، به نظرم که کار قشنگ دیگه میتونه این باشه که کلا دامنه های `ir.` رو از لیست حذف کنید و فقط این دو مورد رو به `iran.dat:ir` اضافه کنید
  
```
ir
xn--mgba3a4f16a # .ایران
```
از اونجایی که هر دامنه ای به صورت `xx.yy.ir` عملا یک ساب دومین از `ir.` حساب میشه، همین دو مورد تمامی دامنه های با TLD های ایران رو بایپس میکنه و دیگه نیازی به استفاده از regular expression هم توی کلاینت ها نیست. توی ریپو [domain-list-community](https://github.com/v2fly/domain-list-community) هم به همین صورت هست [cn](https://github.com/v2fly/domain-list-community/blob/master/data/cn)  [tld-cn](https://github.com/v2fly/domain-list-community/blob/master/data/tld-cn)
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains
اگر اوکی هست که PR بدم

_Originally posted by @Chocolate4U in https://github.com/bootmortis/iran-hosted-domains/issues/123#issuecomment-1712728213_

**Comment by bootmortis** [comment]
@Chocolate4U  
  
ایشو رو بزار تا آخر هفته باز باشه اگر موردی بود اعلام کنن بقیه، اگر نبود بیزحمت PR بزن. ممنون

**Comment by Chocolate4U** [comment]
> @Chocolate4U
> 
> ایشو رو بزار تا آخر هفته باز باشه اگر موردی بود اعلام کنن بقیه، اگر نبود بیزحمت PR بزن. ممنون

خواهش میکنم. مشکلی نیست.

**Comment by Chocolate4U** [comment]
ظاهرا مشکلی نیست، #134
