### ISSUE TITLE
Windscribe

### ISSUE THREAD

**Issue by abulfa** [bootmortis/iran-hosted-domains#132]
راهی هست که برای split tunneling ویند اسکرایب ، بشه این لیست دامین های ایرانی رو اضافه کرد؟

**Comment by mmrabbani** [comment]
برنامه windscribe قابلیت split tunneling بر اساس دامنه رو نداره و فقط میشه برنامه روانتخاب کرد که داخل VPN نباشه. در نیتجه نمیتونه از این پروژه استفاده کنه

**Comment by abulfa** [comment]
![photo_2023-09-20_12-33-54](https://github.com/bootmortis/iran-hosted-domains/assets/86102526/641e85b0-6b2d-4271-84e8-5d55681b03b0)

بخش آی پی و هاست نیم داره

**Comment by bootmortis** [comment]
جایی برای ایمپورت کردن داره؟
اگر نداره امکانش نیست چون حدود ۱۱۰ هزار دومین رو باید دستی وارد کنید

**Comment by 123SONIC321** [comment]
یک ایده‌ای به ذهنم رسید @bootmortis 
 در برنامه گزینه‌ی خروجی گرفتن از تنظیمات به صورت فایل وجود داره، میتونیم اون فایل بکاپ خروجی رو ادیت کنیم (اون 110هزار دومین رو اضافه کنیم) و بعدش به برنامه وارد کنیم

> جایی برای ایمپورت کردن داره؟ اگر نداره امکانش نیست چون حدود ۱۱۰ هزار دومین رو باید دستی وارد کنید

**Comment by 123SONIC321** [comment]
github.com و aparat.com 
رو بصورت دستی در برنامه وارد کردم وبعدش از تنظیمات برنامه خروجی (اکسپورت) گرفتم
اون قسمتی که مربوط به این بخش از تنظیمات هست رو براتون آوردم 👇



```
        "splitTunneling": {
            "apps": [
            ],
            "networkRoutes": [
                {
                    "name": "github.com",
                    "type": 1
                },
                {
                    "name": "aparat.com",
                    "type": 1
                }
            ],
```

و بعدش یک دامنه دیگه، مثلا gothub.com رو به این فایل خروجی اضافه کردم و فایل رو سیو کردم
حالا این فایل رو به برنامه ایمپورت کردم و دیدم که دامنه gothub.com به لیست اضافه شده
پس این تئوری تایید میشه
تنها مشکل اینه که لازمه تمامی دامنه‌ها به این صورت باشند تا بشه به برنامه ایمپورت کرد (درضمن نمیدونم آیا برنامه کشش ایمپورت فایل به اون بزرگی رو داره یا نه)

                {
                    "name": "domain.name",
                    "type": 1
                },

**Comment by abulfa** [comment]
من با کمک chat gpt تونستم یه لیست از دامنه ها رو تبدیل کنم به این قالب ، ولی کار نمیکنه متاسفانه
[bk.json](https://github.com/user-attachments/files/15510067/bk.json)

**Comment by 123SONIC321** [comment]
> من با کمک chat gpt تونستم یه لیست از دامنه ها رو تبدیل به این قالب ، ولی کار نمیکنه متاسفانه [bk.json](https://github.com/user-attachments/files/15510067/bk.json)

از آخرین ورژن استفاده می‌کنید؟

**Comment by 123SONIC321** [comment]
> من با کمک chat gpt تونستم یه لیست از دامنه ها رو تبدیل به این قالب ، ولی کار نمیکنه متاسفانه [bk.json](https://github.com/user-attachments/files/15510067/bk.json)

فایل بکاپتون رو وارد کردم، برای من هر 51 دامنه اضافه شد D:
فقط بعد از وارد کردن گزینه اسپلیت تانلینگ خاموش شد، دوباره باید روشنش کنید
![image](https://github.com/bootmortis/iran-hosted-domains/assets/99527351/f7d2a7c2-2a27-4339-ba22-86f2bef9b321)

**Comment by abulfa** [comment]
بله مثل اینکه مشکل از من بود ، البته برنامه اجازه اضافه کردن بیشتر از 50 تا دامنه نمیده

**Comment by 123SONIC321** [comment]
> بله مثل اینکه مشکل از من بود ، البته برنامه اجازه اضافه کردن بیشتر از 50 تا دامنه نمیده

بله منم دیشب توی [این ایشو](https://github.com/Windscribe/Desktop-App/issues/145) خونده بودم
ولی الان من 53 تا دامنه اضافه کردم و ارور خاصی نمیده؟

**Comment by abulfa** [comment]
توی اخرین نسخه تونستین بیشتر از 50 تا اضافه کنین؟

**Comment by 123SONIC321** [comment]
بله بکاپ شمارو ایمپورت کردم (51عدد دامنه بود) میتونستم خودمم هم اضافه کنم
ویژگی نسخه پرو فکر نکنم باشه
