### ISSUE TITLE
Tutorial for v2rayN

### ISSUE THREAD

**Issue by amir-fo** [bootmortis/iran-hosted-domains#14]
سلام، 

اگر به آخر هر دامنه توی فایل دامنه ها کاما ( , ) اضافه بشه میشه توی v2rayN از طریق منوی settings -> routing settings -> advance functions - > add وبعد انتخاب یک نام و کلیک توی قسمت خالی و انتخاب Rule Add و کپی کردن تمام دامنه ها در قسمت دامنه و انتخاب direct، ارتباط مستقیم با دامنه ها گرفت. 
من کاما رو اضافه کردم وفایل نوت رو پیوست کردم که اگر خواستید اضافه کنید.
[domains.txt](https://github.com/bootmortis/iran-hosted-domains/files/10729724/domains.txt)

**Comment by MasterKia** [comment]
@bootmortis I just randomly checked the [`domains.txt`](https://github.com/bootmortis/iran-hosted-domains/releases/download/202302131354/domains.txt) file and found some adservers/trackers (there's probably more):
```
adwised.com
toppopup.com
yektanet.com
```

Do you know why they are in the list?

**Comment by amir-fo** [comment]
No idea.
I got the list from [here](https://github.com/bootmortis/iran-hosted-domains/releases) but i think it originated from https://eservices.ito.gov.ir/page/iplist#
domains you mentioned are in the list from the Iranian website.
Just FYI, the link shows domain that are hosted inside Iran.

**Comment by MasterKia** [comment]
Well that means these adservers/trackers will get to see the user's real Iranian IP, I don't find that to be good for privacy.

**Comment by amir-fo** [comment]
True. We could always select “block” in v2rayN (or any other proxy app) for these domains.

**Comment by hawshemi** [comment]
For v2rayN software, you can use the `iran.dat` file.
Place the `iran.dat` file in the v2rayN directory and add the rules like the image:

![v2rayn - Copy](https://user-images.githubusercontent.com/16742123/219044401-1996f0f4-58f1-48c5-a1f8-d6af8f06fae8.png)

**Comment by amir-fo** [comment]
> سلام، با چه کدی به همه‌ی لاین‌ها یه کاما اضافه کردی؟ و برای حذف کردن مثلن یه ستون از کل فایل چه کدی استفاده می‌شه ؟ ممنون

توی برنامه مایکروسافت وورد به راحتی میشه. ctrl+h رو با هم بزنید و در خط اول ^p و در خط دوم ,^p رو بزنید، در اخر هر خط کاما اضافه میکنه. البته اینجا ظاهرا داره کد ها رو برعکس نشون میده بخاطر راستچین شدن کامنت. دقیقا متوجه نمیشم منظورتون از حذف یه ستون چیه. دامنه ها هر کدوم در یک خط جدا هستند و ستونی نیست. ولی مطمنم میشه تو گوگل پیداش کرد




> For v2rayN software, you can use the `iran.dat` file. Place the `iran.dat` file in the v2rayN directory and add the rules like the image:

Thank you. Learnt something new today! (iran.dat file should go in bin folder in v2rayN directory for anyone else trying this methode)

**Comment by bootmortis** [comment]
بنظرم یک اسکریپت ساده برای این کار کفایت می‌کنه، هدف ما از اینکه فایل خام رو دادیم این بود که کاربر نهایی بتونه هر پردازشی که بخواد رو روش انجام بده نیازی به اینکه فایل جدید به رلیز ها اضافه کنیم نیست و فایل هم باید همینطور که هست خام باشه.

```bash
wget -qO- https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/domains.txt | sed 's/$/,/' > domains-with-comma.txt
```

من با این نرم افزار کار نکردم و امکانش رو ندارم که تست کنم برای آموزش، اگر براتون مقدور هست از این دستوری که نوشتم یک بخش آموزش اضافه کنید و PR بدید.

البته این اسکریپت برای لینوکس و مک کار می‌کنه فقط و نیازه که wget هم نصب باشه. برای ویندوز اگر می‌تونید دستور مشابهش رو بنویسد لطفا بگید.

**Comment by amir-fo** [comment]
نیازی به اسکریپت نیست. روشی که @hawshemi عزیز گفتن خیلی راحت تره و دیگه به فایل دامنه و کاما اضافه کردن نیازی نیست. PR هم اضافه شد.
