### ISSUE TITLE
همراه بانک صادرات

### ISSUE THREAD

**Issue by farzadmaham** [bootmortis/iran-hosted-domains#141]
### Description

Please provide a clear and concise description of the bug.

### Steps to Reproduce

Please provide the steps you took to encounter the bug.

### Expected Outcome

What did you expect to happen?

### Actual Outcome

What actually happened?

### Additional Information

- Version of the repository you are using
- Relevant details about your environment (operating system, browser, etc.)
- Screenshots or other relevant information to help us understand the bug

**Comment by farzadmaham** [comment]
همراه بانک صادرات ف. ی . ل .ت .ر شکن را با اکثر اپهای اندروید چک کردم تنظیمات را هم دقیقا اعمال کردم ولی تشخیص میده دایرکت نمیشه.

**Comment by bootmortis** [comment]
اپلیکیشن بانک صادرات رو به صورت جداگانه در کلاینتتون بای‌پس کنید. پیشنهاد‌ما استفاده از کلاینت‌هایی مثل nekobox یا sagernet هست.
