### ISSUE TITLE
لیست اپلیکیشن‌ها در nekobox

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#143]
من تنظیمات geosite.db رو در طبق راهنمای خودتان در nekobox اعمال کردم سایت های داخلی به خوبی باز میشه بدون مشکل اما نرم افزار های ایرانی مثل همراه بانک ها جواب گو نیست آیا راهی داره مثل clash meta اوکی ش کرد از طریق همین فایل db ؟ یا باید نرم افزار ها رو در بخش bypass app وارد کرد به صورت دستی؟

**Comment by bootmortis** [comment]
فایل geosite.db صرفا شامل آدرس سایت و دامنه‌ها هستش و شامل لیست نرم‌افزار ها نمی‌شه. لیست نرم‌افزار ها از حیطه این مخزن خارج هست و این مخزن صرفا بر روی دامنه‌های مرتبط با ایران تمرکز داره.

**Comment by bootmortis** [comment]
related #131 #80
