### ISSUE TITLE
Windscribe

### ISSUE THREAD

**Issue by hosseinc** [bootmortis/iran-hosted-domains#144]
## Feature Request
ضاافه شدن دامنه های ایرانی به قسمت custom ROBERT Rule تو وینداسکرایب
### Description
علاوه بر اینکه بعضی از سرورای خود اپ وصل میشه، چون میشه بهش کانفیگ وایرگارد هم اضافه کرد، اینجوری میشه با کانفیگ وایرگارد هم rule تعریف کرد
Please provide a clear and concise description of the feature you would like to request.

### Motivation

Why do you want this feature? What problem does it solve or what use case does it support?

### Example

If possible, provide an example of how the feature would be used.

### Suggested Solution

If you have a suggestion for a solution to this feature request, please share it here.

### Alternative Workarounds

Are there any alternative workarounds or solutions you have tried that you would like to share?

### Additional Information

Any additional information you would like to provide.

**Comment by bootmortis** [comment]
چک کردم شدنی نبود
