### ISSUE TITLE
Add My Irancell PWA app

### ISSUE THREAD

**Issue by omidshojaee** [bootmortis/iran-hosted-domains#147]
### Domain Name

The PWA app of My Irancell (my.irancell.ir) is not loading when connected through Shadowrocket. It detects that we are connected to VPN and asks to disconnect.

### Reason for Add/Remove

So we don't need to disconnect the VPN when using this app.

### Supporting Evidence

If possible, please provide any relevant supporting evidence for your request (e.g. screenshot).

### Additional Information

Any additional information you would like to provide.

**Comment by Phoenix-999** [comment]
> my.irancell.ir

Hi @omidshojaee,

**my.irancell.ir**, appears to use **Cloudflare IP** addresses, which may pose an issue with the current routing mechanism set as `regexp:.*\.ir$` and `ext:iran.dat:ir` or `geosite:category-ir`.

To address this problem, consider adding `Cloudflare.com` to the direct section of routing, and additionally, adding`Googletagmanager.com` in the Direct section might help too. 

This adjustment should resolve the issue with my.irancell.ir by bypassing the proxy server and connecting directly. However, please note that if you are using Warp, this recommendation may not apply.

Hope that helps.

**Comment by omidshojaee** [comment]
I can confirm adding ```cloudflare.com``` to the ```Direct``` rule as ```DOMAIN-SUFFIX``` solved the issue.

Thank you.
