### ISSUE TITLE
Add `websecret.ir`

### ISSUE THREAD

**Issue by Phoenix-999** [bootmortis/iran-hosted-domains#149]
`websecret.ir`

Thank you In advance

**Comment by bootmortis** [comment]
بنظرم بهتره که سرویس‌هایی که ip رو نشون می‌دن دایرکت نشن، چرا که خیلیا شاید بخوان از این سرویس ها برای مشخص کردن ip شون استفاده کنن که به سرور متصل هستند یا نه. هر چند که به طور کلی طبق بیشتر اموزش‌های ما کل دومین های ir دایرکت میشن.

**Comment by Phoenix-999** [comment]
> بنظرم بهتره که سرویس‌هایی که ip رو نشون می‌دن دایرکت نشن، چرا که خیلیا شاید بخوان از این سرویس ها برای مشخص کردن ip شون استفاده کنن که به سرور متصل هستند یا نه. هر چند که به طور کلی طبق بیشتر اموزش‌های ما کل دومین های ir دایرکت میشن.

حق با شماست @bootmortis جان ,
ولی تقریبا ۲ هفته ای هست که بعضی از وبسایت ها IR. جدیدا با قوانین regexp:.*\.ir$ و geosite:category-ir درست کار نمیکنند 
 مثلا  divar.ir و حتا همین websecret.ir درست از اپلیکیشن کاربرbypass نمیشند 

نتونستم دلیل قانع کننده براش پیدا کنم,  بر روی اپلیکیشن کاربر iPhone  و android  هم هر دو امتحان کردم ولی مشکل یکسان هست!!

**Comment by bootmortis** [comment]
روی چه کلاینتی مشکل داره؟
ترجیحا از کلاینت‌های مبتنی بر xray یا v2ray استفاده کنید و آخرین نسخه‌ی `iran.dat` رو دانلود و رول `ext:iran.dat:all` رو روی `direct` قرار بدید، نیازی به regex نداره این حالت.

**Comment by Phoenix-999** [comment]
@bootmortis 
تقریبا بیشتر اپلیکیشن ها روی هر دو پلتفرم تست کردم 
V2BOX, Streisand,  بر روی iPhone 
V2rayNG و NekoBox بر روی Android
البته بعضی از اپلیکیشن ها  کارایی اضافه کردن dat. را ندارند و اجباری باید از regexp:.*.ir$ و geosite:category-ir استفاده بشه 

حالا آپدیت میکنم و تست جدید میگیرم خبرت میدم
 دم شما گرم برای همه زحمتهای که میکشی ✌🏾

**Comment by hawshemi** [comment]
اصولا اگر regex بزنید باید همه ی ir هارو بدون هیچ قید و شرطی دایرکت کنه.
مگر اینکه کلاینت یه مشکلی داشته.
چک کنید Domain Strategy روی IPIfNotMatch باشه.

**Comment by Phoenix-999** [comment]
@hawshemi جان 
تمام ستینگ ها درست هست, مدتی ۲ هفته میشه که regexp:.*.ir$ و geosite:category-ir درست کار نمیکنند. روی اپلیکیشن های کلاینت مختلف امتحان کردم, همه به روز رسانی شده اند و هسته به آخرین ورژن تغییر به روز شدند.  و برای اطمینان کارهایی مثل پاک کردن cache و dns flush هم انجام شده حتا بروی سرور های مختلف هم امتحان شده. ولی نتیجه یکی هست.

مطمئن نیستم, حدس میزنم سیستم فیلترینگ ممکنه داره تغیراتی میده بروی بازی از ISP  ها.
مشکل جدید هم این هست که حتا با وجود استفاده از warp اپلیکیشن هایی مثل spotify و OpenAI هم به مشکل خوردند و باز نمیشند.

اگه کسی راه حل اساسی داره ممنون میشم به اشتراک بگذاره

**Comment by hawshemi** [comment]
فکر نمیکنم ربطی به فیلترینگ داشته باشه.
احتمالا مشکل DNS باید باشه. یا روی کلاینت یا روی سرور یا حالت FakeDNS یا حالت Domain Strategy و ...

وارپ هم با لایسنس، پلاس کنید. با تنظیمات درست عالی کار میکنه.

**Comment by MasterKia** [comment]
>  مثلا divar.ir و حتا همین websecret.ir درست از اپلیکیشن کاربرbypass نمیشند

دیوار یک سری درخواست‌ها به دامنه‌ی divarcdn.com میزنه که اگه bypass نشه به مشکل می‌خوره.
البته اون دامنه هم توی لیست دامنه‌های ایرانی هست.
