### ISSUE TITLE
درخواست اضافه کردن لینک ثابت شدوراکت

### ISSUE THREAD

**Issue by emranovin** [bootmortis/iran-hosted-domains#153]
### Description
اگه بتونید یه لینک URL ثابت اضافه کنید که همیشه آخرین لیست رو برگردونه عالی میشه. این اپ URL هم میگیره و اینطوری فقط کافیه آپدیت کنیم داخل اپ و نیاز به انتقال فایل و.. نیست.

**Comment by bootmortis** [comment]
https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/shadowrocket.conf

با این لینک کار نمی‌کنه؟ فرمت خاصی داره؟

**Comment by emranovin** [comment]
با همین لینک کار میکنه. من فکرکردم همیشه تاریخ ریلیز جزئی از لینکه ولی متوجه کلید واژه latest نبودم
ممنون
