### ISSUE TITLE
How to add iran.dat into xray_config.json

### ISSUE THREAD

**Issue by m0x61h0x64i** [bootmortis/iran-hosted-domains#154]
Hi, i want client to connect to use xray config while they can directly connect to the sites which are in iran.dat file 

How can i add the following rules into the xray_config.json file ?
ext:iran.dat:all in bypass section
ext:iran.dat:ads in block section

**Comment by bootmortis** [comment]
check theses: 
- https://github.com/bootmortis/iran-hosted-domains/issues/58
- [iranxray/hope](https://github.com/iranxray/hope/blob/main/routing.md#%D9%85%D8%B3%D8%AF%D9%88%D8%AF%D8%B3%D8%A7%D8%B2%DB%8C-%D8%A7%D8%B2-%D8%B3%D9%85%D8%AA-%D8%B3%D8%B1%D9%88%D8%B1)

but use direct instead of block
