### ISSUE TITLE
Nekoray

### ISSUE THREAD

**Issue by sinascorpion** [bootmortis/iran-hosted-domains#161]
توی توضیحات قسمت تنظیمات Routing برای برنامه Nekoray باید یه $ اضافه بشه اولش والا کار
![Screenshot 2023-11-24 181401](https://github.com/bootmortis/iran-hosted-domains/assets/29574131/bf7ef5ec-b7a8-41ca-a8bd-0775cd7abb0d)
 نمی کنه

https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md

اینجا برای xray core وقسمت Direct, Domain

ext:iran.dat:all
باید تغییر کنه به
$ext:iran.dat:all

**Comment by bootmortis** [comment]
cc: @Chocolate4U
