### ISSUE TITLE
We need your expertise

### ISSUE THREAD

**Issue by Phoenix-999** [bootmortis/iran-hosted-domains#163]
Sorry to drop the message like this here but we would like you to join our private group to discuss the issue with the gfw in Iran

https://github.com/XTLS/Xray-core/issues/2778#issuecomment-1837245571

Here is my email,be in touch 
Ronin.Parsi@proton.me

Ps: our private group is in telegram

**Comment by bootmortis** [comment]
Please avoid spamming in the issues section. You can find my contact info in my bio if you need to reach out to me. I won't be joining any Telegram private group, but feel free to mention me in any GitHub discussion. Thanks for understanding.

**Comment by Phoenix-999** [comment]
I do apologize, @bootmortis.
