### ISSUE TITLE
تغییر در فرمت فایل های جئو از هسته جدید 1.8

### ISSUE THREAD

**Issue by Graveyard9988** [bootmortis/iran-hosted-domains#164]
درود
ظاهرا فرمت و ساختار فایل های geo سینگ باکس از هسته 1.8 تغییر کرده است. مثال:
https://github.com/ZloZloe39/new-sing-geo
لطفا نسبت به ایجاد فایل های جدید (علاوه بر فایل های قبلی) بررسی و اقدام کنید

سپاس

**Comment by bootmortis** [comment]
PRs are welcome

**Comment by bootmortis** [comment]
اگر بخوایم برای نسخه جدید اپدیت بدیم ترجیح من اینه که کلا نسخه‌ی قدیمی رو حذف کنیم چرا که همینجوریش به یک ریپو یعنی 
https://github.com/bootmortis/sing-geosite

دیپندسی داریم و این دیپندسی حذف یا جایگزین نسخه جدید بشه بهتره تا اینکه دو تا ریپوی مجزا برای دو ورژن داشتیه باشیم، مدیریتش سخته

**Comment by Graveyard9988** [comment]
همه کاربران ممکنه تا مدتی از نسخه جدید مطلع نباشن پس بنابراین بهتره فرمت فعلی و فرمت جدید در کنار هم باشند و پس از مدتی، فرمت فعلی (قدیمی) حذف شود

تا مدتی این مساله زحماتی به دنبال دارد، ولی ارزشمند است

**Comment by bootmortis** [comment]
باید در دل ریپوی https://github.com/bootmortis/sing-geosite این کار رو انجام داد من فعلا فرصت ندارم، می‌تونید به اون ریپو PR بزنید اول بعد اینجا اپدیت بشه

**Comment by Graveyard9988** [comment]
با برنامه نویسی اشنایی ندارم اگه کار دیگه ای در این خصوص از من ساخته ست بفرمایید؟

**Comment by bootmortis** [comment]
نسخه 1.8 استیبل که بشه اضافه می‌کنم
شایدم زودتر مشخص نیست

**Comment by Graveyard9988** [comment]
سپاس

**Comment by ashaghal** [comment]
سلام، امروز نسخه stable ورژن 1.8.0 ارائه شد. ممنون میشم فرمت جدید هم ارائه بدین

**Comment by Graveyard9988** [comment]
> نسخه 1.8 استیبل که بشه اضافه می‌کنم شایدم زودتر مشخص نیست

ریپو شکلات با فرمت جدید اقدام به انتشار فایل های srs کرده است. لطفا با الگوی این مجموعه اقدام به همگام سازی با سینگ باکس 1.8 کنید

**Comment by bootmortis** [comment]
@ashaghal @Graveyard9988 

اگر امکانش هست این هارو تست کنید:

[rule-set.zip](https://github.com/bootmortis/iran-hosted-domains/files/13850539/rule-set.zip)

**Comment by ashaghal** [comment]
سلام
من تست کردم مشکلی نداشت 
![image](https://github.com/bootmortis/iran-hosted-domains/assets/39614484/72e9b550-8d55-47c4-881b-54ac2fa1ff3b)
الان این قابلیت هست که لینک رو بدیم و با یک اینتروال خودش آپدیت کنه.

**Comment by bootmortis** [comment]
> الان این قابلیت هست که لینک رو بدیم و با یک اینتروال خودش آپدیت کنه.

رلیز میدم یکی دو ساعت دیگ

**Comment by bootmortis** [comment]
@ashaghal 
https://github.com/bootmortis/sing-geosite/releases/tag/202401061809

لینکی که همیشه بخوای اپدیت کنی میشه این  

`https://github.com/bootmortis/sing-geosite/releases/latest`

با اسم فایل:  

`https://github.com/bootmortis/sing-geosite/releases/latest/download/geosite-ir.srs`

**Comment by ashaghal** [comment]
> لینکی که همیشه بخوای اپدیت کنی میشه این

عالی، مرسی

**Comment by Graveyard9988** [comment]
> @ashaghal https://github.com/bootmortis/sing-geosite/releases/tag/202401061809
> 
> لینکی که همیشه بخوای اپدیت کنی میشه این
> 
> `https://github.com/bootmortis/sing-geosite/releases/latest`
> 
> با اسم فایل:
> 
> `https://github.com/bootmortis/sing-geosite/releases/latest/download/geosite-ir.srs`

لطفا geoip ها و سایر رو تکمیل کنید...سپاس

در ضمن، در افغانستان سایت های بسیاری مسدود است و مردم ناچارند vpn استفاده کنن از طرفی geoip کاملی برای این کشور وجود ندارد تا آیپی های داخلی را دور بزنند، ریپو chocolate4u جئو ایپی افغانستان را تدارک دیده اما کاستی هایی دارد، اگر ممکنه شما نیز چنین زحمتی را متقبل شوید

**Comment by bootmortis** [comment]
> لطفا geoip ها و سایر رو تکمیل کنید...سپاس

این مخزن همونطور که از اسمش پیداست تمرکزش روی دامنه‌است و geoip رو شامل نمیشه.

**Comment by Graveyard9988** [comment]
> > لطفا geoip ها و سایر رو تکمیل کنید...سپاس
> 
> این مخزن همونطور که از اسمش پیداست تمرکزش روی دامنه‌است و geoip رو شامل نمیشه.

برای geosite افغانستان کمکی می توانید بکنید؟

**Comment by bootmortis** [comment]
> برای geosite افغانستان کمکی می توانید بکنید؟

متاسفانه خیر
