### ISSUE TITLE
Add/Remove `zabanshenas.com` and `zabanshenas.app`

### ISSUE THREAD

**Issue by shahramdll** [bootmortis/iran-hosted-domains#168]
### Domain Name
please add these two to iran bypass list,
`zabanshenas.com` and `zabanshenas.app`

### Reason for Add/Remove
these two are related to zabanshenas application that hosted in iran.

**Comment by bootmortis** [comment]
`zabanshenas.com` is already in the list
![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/98e2527d-0736-464a-af68-6a295a5e19a5)

and I can't find anything about `zabanshenas.app`
![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/d69a55b6-d1e7-4f1b-a66c-e829d5fd35ce)
