### ISSUE TITLE
nekoray mac

### ISSUE THREAD

**Issue by hosseinc** [bootmortis/iran-hosted-domains#171]
infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:iran.dat:ads > infra/conf: failed to load external sites: ads from iran.dat > infra/conf: failed to load file: iran.dat > infra/conf: failed to open file: iran.dat > open /Applications/nekoray_amd64.app/Contents/MacOS/iran.dat: no such file or directory

![Screenshot 2023-12-16 at 6 42 43 PM](https://github.com/bootmortis/iran-hosted-domains/assets/40062051/a1ed3d53-51b5-4662-a362-6bb9400ddd11)

سلام
لطفا راهنمایی کنین
فایل وجود داره ولی پیدا نمیکنه و این ارور رو میده

**Comment by bootmortis** [comment]
طبق متن خطا باید فایل رو تو مسیر `/Applications/nekoray_amd64.app/Contents/MacOS/iran.dat` بزارید
