### ISSUE TITLE
Streisand

### ISSUE THREAD

**Issue by hosseinc** [bootmortis/iran-hosted-domains#173]
## Feature Request
اضافه شدن این اپ به لیست
### Description
![image](https://github.com/bootmortis/iran-hosted-domains/assets/40062051/53d3bf3b-0e51-4180-b936-d1ff8effe809)

قسمت geo داره که امکان اضافه کردن فایل جدید هم هست
لطفا بررسی کنین
معمولا از shadowrocket بهتر عمل میکنه

**Comment by bootmortis** [comment]
از سایر اموزش‌های مبتنی بر فایل `iran.dat` استفاده کنید.
