### ISSUE TITLE
how can i make custom .dat file

### ISSUE THREAD

**Issue by DgithubA** [bootmortis/iran-hosted-domains#178]
i use bellow rules to bypass proxy(direct), but i have some problem.
At the moment, geosite.dat size is 5MB and geoip.dat is 10.2MB .
in mobile V2rayNG app when we i use this custom rules, It takes a long time to start xray service and when we dont use any ruls of `geosite:` or `geoip:` , This time is greatly reduced.
Now i want to custom this rules and put all of them in one file to Reduce file size and execution time, and use it with `ext:cutom.bat:direct` and `ext:custom.bat:block` .
Obviously, the size of the file is reduced because there are no additional data and lists that are not necessary(like other geo domain and ips), so as a result, we have better speed.
now i have question. how can i do this? how can make my custom .dat file with tags(direct,block,etc)

my rules:
* direct:
`geoip:ir,
geoip:private,
geosite:cloudflare,
geosite:github,
geosite:category-ir`
* block:
`geosite:category-ads-all`

**Comment by bootmortis** [comment]
https://github.com/bootmortis/iran-hosted-domains?tab=readme-ov-file#create-dat-file-manually-tutorial
