### ISSUE TITLE
update_iran_dat.ps1

### ISSUE THREAD

**Issue by w0l4i** [bootmortis/iran-hosted-domains#179]
درود وقتی پاور شل رو باز میکنم با دسترسی ادمین و طبق اموزش میخوام تست کنم این ارور رو میگیریم 
این گزینه رو هم وارد کردم
Set-ExecutionPolicy unrestricted
ولی با این حال

![image](https://github.com/bootmortis/iran-hosted-domains/assets/52799129/3f5cf09a-3383-4ca5-9385-468b3057ccb0)

اخرین ورژن ویندوز 11 و پاور شل اخرین ورژن

**Comment by Phoenix-999** [comment]
@realartin 

Here 
https://github.com/iranxray/hope/issues/107
