### ISSUE TITLE
📢 Sing-box v1.8 (Rule-set `srs` files)

### ISSUE THREAD

**Issue by bootmortis** [bootmortis/iran-hosted-domains#180]
فایل‌های srs مربوط به نسخه‌ی ۱.۸ سینگ باکس به صورت هفتگی و خودکار همزمان با آپدیت شدن این مخزن، در [بخش رلیز](https://github.com/bootmortis/sing-geosite/releases/latest) مخزن زیر منتشر می‌شن:

[bootmortis/sing-geosite](https://github.com/bootmortis/sing-geosite)

فرمت آخرین نسخه‌ی فایل‌ها برای استفاده با قابلیت آپدیت خودکار در سمت کلاینت در [بخش توضیحات](https://github.com/bootmortis/sing-geosite?tab=readme-ov-file#usage) ریپو‌ی بالا آورده شده.

برای افزودن توضیحات و آموزش کامل مربوط به فایل‌های srs لطفا به همین ریپوی فعلی PR بزنید. پذیرای PR شما هستیم ;)

مرتبط: #164 

### Documents:
- [Migrate Geosite to rule sets](https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets)

**Comment by admiralhr99** [comment]
سلام
میشه لطفا نحوه استفادشو سمت سرور هم توضیح بدید
برای این https://github.com/mack-a/v2ray-agent

**Comment by bootmortis** [comment]
> سلام میشه لطفا نحوه استفادشو سمت سرور هم توضیح بدید برای این https://github.com/mack-a/v2ray-agent


به داکیومنت رسمی مراجعه کنید:
https://sing-box.sagernet.org/
