### ISSUE TITLE
Add `sjdcbjddbcsjhbsbjhcjbsdjshcdcjbsdsj.buzz`

### ISSUE THREAD

**Issue by demarcush** [bootmortis/iran-hosted-domains#187]
### Domain Name

`sjdcbjhdbscjnbsdjcbjsd.sjdcbjddbcsjhbsbjhcjbsdjshcdcjbsdsj.buzz`

### Reason for Add/Remove

Domain for download servers of f2m.top; should be added to bypass list as it's not accessible without IR IPs.

### Supporting Evidence

![image](https://github.com/bootmortis/iran-hosted-domains/assets/146051763/d44f25e3-5ed7-4a9b-834f-959226c13ba9)

### Additional Information

It would be better to just add the domain as a DOMAIN-SUFFIX rule type and not with the subdomain as a DOMAIN, as they might use another random string for another subdomain later to avoid detection/censorship. It would also make the maintenance easier.
e.g:
```yaml
rules:
    - DOMAIN-SUFFIX,sjdcbjddbcsjhbsbjhcjbsdjshcdcjbsdsj.buzz,DIRECT
```

**Comment by bootmortis** [comment]
this looks like a random dynamic domain so not worth adding to the list.

**Comment by demarcush** [comment]
It's not something ephemeral. They've been using it for almost 3 years now.
Yet, it's your choice.
