### ISSUE TITLE
Adaway support

### ISSUE THREAD

**Issue by iman8852** [bootmortis/iran-hosted-domains#189]
Hi buddy tnx for your nice work
Can u support a link for adaway as well?

**Comment by bootmortis** [comment]
AdAway is an open source ad blocker. It's not related to this repository and bypassing Iran domains!
Please pay attention that this repository is not responsible for blocking Iran ads

**Comment by bootmortis** [comment]
AdAway is an open source ad blocker. It's not related to this repository and bypassing Iran domains!
Please pay attention that this repository is not responsible for blocking Iran ads

**Comment by bootmortis** [comment]
AdAway is an open source ad blocker. It's not related to this repository and bypassing Iran domains!
Please pay attention that this repository is not responsible for blocking Iran ads
