### ISSUE TITLE
Sing-box supported domains list

### ISSUE THREAD

**Issue by m0ck1nGuY** [bootmortis/iran-hosted-domains#19]
Hello 
hope all is well, 
it would be highly appreciated if you could publish the domain list in the sing-box format (db file) 
e.g. https://github.com/SagerNet/sing-geosite/

thanks

**Comment by bootmortis** [comment]
I checked [the repo](https://github.com/SagerNet/sing-geosite/) and modify it a little,
Can you test this file and let me know if it is OK?
[iran-geosite.zip](https://github.com/bootmortis/iran-hosted-domains/files/10774185/iran-geosite.zip)

**Comment by m0ck1nGuY** [comment]
I tested it but it doesn't work, are the categories same as other formats ? (ir, other, ads)

**Comment by bootmortis** [comment]
Yes, it does precisely the same thing as the SagerNet repo does
https://github.com/bootmortis/sing-geosite

**Comment by m0ck1nGuY** [comment]
Ok! my bad it works perfectly.
Apparently Im using an older version of the list in my phone (sagernet) in that list ipnumberia.com was one of the iranian domains but it is no longer exist in the new domain list.
As a suggestion can it be merged with loyalsoldier domain lists ? (https://github.com/Loyalsoldier/v2ray-rules-dat)
Because AFAIK sing-box doesnt let you load more than one geosite file.

**Comment by bootmortis** [comment]
> As a suggestion can it be merged with loyalsoldier domain lists ? (https://github.com/Loyalsoldier/v2ray-rules-dat)
Because AFAIK sing-box doesnt let you load more than one geosite file.

Merging with non-Iran-related domain lists is out of the context of this repository's purpose; you could open an issue on sing-box to support multiple files or create a separate repository and merge them yourself.  
That aside, can you open a PR and add docs about sing-box in the readme files?

**Comment by m0ck1nGuY** [comment]
Yea I understand that
Just asked it because I dont have go skills.
Ofc, I will add that asap.
Thanks
