### ISSUE TITLE
It doesn't work for passwall

### ISSUE THREAD

**Issue by mmddks** [bootmortis/iran-hosted-domains#193]
Hi.
It doesn't work for passwall, please change the steps

**Comment by bootmortis** [comment]
you need to give me more info
it's working pretty well on my setup

**Comment by mmddks** [comment]
![Uploading IMG_1457.png…]()
This geoip:ir section that I add will be completely disconnected from the proxy

**Comment by bootmortis** [comment]
عکس درست اپلود نشده
فایل iran.dat رو در مسیر درست قرار دادید؟

**Comment by mmddks** [comment]
![SSH](https://github.com/bootmortis/iran-hosted-domains/assets/117828229/f03becf3-7b48-43e4-9752-14c32ea66ade)
![UI](https://github.com/bootmortis/iran-hosted-domains/assets/117828229/c3796874-8320-4551-8a71-79adf17952a6)
![UI1](https://github.com/bootmortis/iran-hosted-domains/assets/117828229/8b0b9f5c-644e-48ea-85f9-8f6643d5e2d0)

بله فایل توی مسیر پیش فرض قرار دادم، همه تنظیمات اوکیه ، فقط بخش geoip:ir وارد میکنم همچی قط میشه ، با بقیه تنظیمات بخوبی کار میکنه.

**Comment by bootmortis** [comment]
geoip مرتبط با این ریپو نیست
ای پی ها از منابع عمومی گرفته میشه 
باید فایل geoip.dat رو بگیرید از منابع
