### ISSUE TITLE
Add/Remove `ninioffmeson.ir.`

### ISSUE THREAD

**Issue by parsianmag** [bootmortis/iran-hosted-domains#196]
### ninioffmeson.ir

Please provide the name of the domain you would like to add or remove.
Also, specify whether you want to add/remove this domain from the **Bypass List** or the **Block List**.

**Comment by bootmortis** [comment]
توی لیست هست

![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/932ef2c5-2181-4cba-bef9-4a49c4d94099)
