### ISSUE TITLE
Add "tgju.org" to Bypass List enhancement

### ISSUE THREAD

**Issue by underdog-03** [bootmortis/iran-hosted-domains#215]
Hi @bootmortis,

Firstly, I want to express my gratitude for your hard work and consistency.

Could you please add `tgju.org` to the list? However, I noticed that this domain might use the `yektanet.com` CDN service and `googletagmanager.com`.

Despite adding `tgju.org` to the direct domain rules, it still recognizes your VPN connection and won't bypass it.
Do you have any suggestions for resolving this issue?

Thank you in advance for your assistance.

**Comment by bootmortis** [comment]
It's already there
![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/8affef52-d004-4ba4-b4bd-28dc85b6cbe7)
