### ISSUE TITLE
نحوه اضافه کردن یکسری دامین اختصاصی به دستورات

### ISSUE THREAD

**Issue by BenyaminMoadab** [bootmortis/iran-hosted-domains#222]
### Description

سلام وقت بخیر
قبلا وقتی این فایل ایران اکسس رو فعال میکردم میتونستم پنل کاربری رو باز کنم اما‌ تازگیا نمیشه خواستم ببینم به چه صورت باید اضافه کنم به قوانین تا بتونم پنل هایی که پشت دامین دارم باز کنم.....

### Steps to Reproduce

Please provide the steps you took to encounter the bug.

### Expected Outcome

What did you expect to happen?

### Actual Outcome

What actually happened?

### Additional Information

- Version of the repository you are using
- Relevant details about your environment (operating system, browser, etc.)
- Screenshots or other relevant information to help us understand the bug

**Comment by bootmortis** [comment]
پنل کاربری چی هست؟ از چه ورژنی از فایل استفاده می‌کنید؟

**Comment by BenyaminMoadab** [comment]
تو آخرین آپدیت فایلی که دادین مشکل حل شد
اما برای دامین اختصاصی به چه صورت باید اضافه کرد؟
بنده از پنل ثنایی و آخرین ورژن استفاده میکنم

**Comment by bootmortis** [comment]
با این پنل‌ها آشنایی ندارم به ریپوی خود پنل مراجعه کنید.
