### ISSUE TITLE
اضافه شدن دامنه جامانده

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#23]
سلام وقت بخیر این دامنه ها هنوز اضافه نشدن باتشکر
pmlm.ir
pay98.app
giftcardgo.ir
qr-code.ir
javab24.com
opizo.com
hard-repair.com
masterkala.com
mobone.ir
androidkade.com
datisnetwork.com
hivanetwork.com
webhostingtalk.ir
sarvdata.com
parsdev.com
mehrafarinorg.ir
mehrafarinorg.com

_Originally posted by @matador7495 in https://github.com/bootmortis/iran-hosted-domains/issues/7#issuecomment-1436586367_

**Comment by patterniha** [comment]
همچنین:
aparatsport.com

**Comment by varathongue** [comment]
www.refah-bank.ir
fansadco.com
salamatedari.ict.gov.ir

**Comment by iranopenwrt** [comment]
www.refah-bank.ir
salamatedari.ict.gov.ir

**Comment by hooman-nourbakhsh** [comment]
license-market.ir
اضافه کنید

**Comment by Sabrali** [comment]
tarafdari.com
shad.ir
iranlms.ir

اینا هم هستن

**Comment by hooman-nourbakhsh** [comment]
نمیدونم دوستان وقت می کنند بررسی کنند این issues رو یا نه ! ولی با توجه به اینکه همچنان باز هست و 1 هفته از آخرین اپدیت گذشته فک کنم باید خودم اقدام کنم و در گیت هاب خودم این پروژه رو گسترش بدم

**Comment by hooman-nourbakhsh** [comment]
> 

من نگاه کردم 2 3 تا از دامنه ها الان مثلا در فایل clash وجود داره سرچ کنید

**Comment by bootmortis** [comment]
> نمیدونم دوستان وقت می کنند بررسی کنند این issues رو یا نه ! ولی با توجه به اینکه همچنان باز هست و 1 هفته از آخرین اپدیت گذشته فک کنم باید خودم اقدام کنم و در گیت هاب خودم این پروژه رو گسترش بدم

تعداد دومین‌ها برای بررسی زیاده، ما نمی‌تونیم بدون بررسی دومین اضافه کنیم نیاز به مدرک داره که این دومین‌ها مشکل دارن با ip خارج.
و اینکه می‌تونید به همین ریپو PR بزنید، نیازی به فورک نیست.

**Comment by papampi** [comment]
zoodfood.com

**Comment by M-Sadegh-M** [comment]
fardayeeghtesad.com

**Comment by bootmortis** [comment]
این ایشو رو برای اینکه از این شلوغ تر نشه می‌بندم.
لطفا اگر دومینتون شرایطی که گفتم رو داره یک ایشوی جدا برای هر دومین بزنید.

> تعداد دومین‌ها برای بررسی زیاده، ما نمی‌تونیم بدون بررسی دومین اضافه کنیم نیاز به مدرک داره که این دومین‌ها مشکل دارن با ip خارج.
و اینکه می‌تونید به همین ریپو PR بزنید، نیازی به فورک نیست.
