### ISSUE TITLE
آپشن برای ویندوز

### ISSUE THREAD

**Issue by MohammadAminDHM** [bootmortis/iran-hosted-domains#234]
سلام، لطفا در توضیحات درباره نسخه ویندوز هم بگید چطور فعال میشه

**Comment by bootmortis** [comment]
توضیحات کلاینت‌های موجود در readme فارسی و انگلیسی مرتبط با نسخه‌های مختلف هست. اکثرشون نسخه‌ی ویندوز هم دارن.

**Comment by MohammadAminDHM** [comment]
![image](https://github.com/user-attachments/assets/ce31ba02-eb68-4a89-94ab-d0151473cacb)

الان کجای این اپ برم من گیج شدم 😫

**Comment by bootmortis** [comment]
این بخش رو دنبال کنید:
https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md#v2rayn
