### ISSUE TITLE
لینک دانلود دائمی برای خروجی های مختلف

### ISSUE THREAD

**Issue by M-Sadegh-M** [bootmortis/iran-hosted-domains#236]
سلام میشه ساختار لینک فایلی که دانلود می‌کنیم را به شکل یک لینک دائمی تغییر بدید تا بشه به برنامه های مختلف از طریق url اضافه کرد

الان v2rayng این قابلیت را داره
![image](https://github.com/user-attachments/assets/5c824520-08c2-4158-885f-91985455d7dd)

الان اینجوری هست:
https://github.com/bootmortis/iran-hosted-domains/releases/download/**202408120030**/iran.dat

در نتیجه هر نسخه جدید که میاد یک لینک جدید داره و نمیشه به برنامه اضافه کرد، ولی مثلا اگه اینجوری باشه دائمی میشه و همیشه اخرین نسخه را دانلود میشه

https://github.com/bootmortis/iran-hosted-domains/releases/download/**latest**/iran.dat

مثل فایل های زیر که لینکی که گذاشته همیشه اخرین نسخه دانلود میشه

![image](https://github.com/user-attachments/assets/4a7d7785-bd05-4cbd-a38f-f11d5b72b7c2)

**Comment by bootmortis** [comment]
در تمامی لینک‌های رلیز گیتهاب کافیه ورژن رو پاک کنید و قبل از `/download/` عبارت `/latest/` رو اضافه کنید تا همیشه آخرین نسخه رو بگیرید:

نمونه:
```
https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
```

**Comment by M-Sadegh-M** [comment]
ممنون
