### ISSUE TITLE
لیست بهینه از سایت هایی که ترافیک داخلی نصف دارند

### ISSUE THREAD

**Issue by ahpourani** [bootmortis/iran-hosted-domains#240]
### Description
لیست بهینه ای که ۵۰۰یا ۱۰۰۰ سرویس برتر فقط باشند و نه ۶۵۰۰۰ هزار سایت

**Comment by bootmortis** [comment]
نگهداری چنین لیستی باید به صورت دستی صورت بگیره و برای ما مقدور نیست
