### ISSUE TITLE
V2rayng نسخه جدید

### ISSUE THREAD

**Issue by dreamboxone** [bootmortis/iran-hosted-domains#242]
در نسخه ۱.۹.۲ به 
برنامه v2rayng  بعد سبک برنامه عوض شده و کاستم رول نداره

**Comment by bootmortis** [comment]
Duplicate of #241

**Comment by Ahmadtamimi313** [comment]
> در نسخه ۱.۹.۲ به برنامه v2rayng بعد سبک برنامه عوض شده و کاستم رول نداره

سلام.

ابتدا فایل [iran.dat](https://github.com/bootmortis/iran-hosted-domains/releases/download/202410140035/iran.dat) را دانلود کنید

بعد از دانلود فایل، کلاینت V2RayNG رو باز کرده

سپس وارد صفحه همبرگری بشید.

در قسمت Routing Settings وارد بشید

سه نقطه عمودی رو بزنید

در قسمت geo asest file فایل ایران دات [iran.dat](https://github.com/bootmortis/iran-hosted-domains/releases/download/202410140035/iran.dat) که قبلا دانلود کردین و در پوشه Download دیوایس هست رو انتخاب کنید


دوباره در قسمت Routing Settings وارد بشید
گزینه domain strategy روی IPifNonMatch قرار دهید

دکمه بیضافه + بالا رو برنید در قسمت remark بنويسيد iran
در قسمت domain این عبارت رو کپی کنید و آنجا بزارید

`ext:iran.dat:all`

بقیه خانه ها خالی باشه

در  پایین‌ترین قسمت بنام  outboundTag
گزینه direct رو انتخاب کنید.

تیک بالا رو بزنید تا تغییرات ذخیره بشه.

سپس تمام کانفیگ های بیرون که از قبل وجود داشته رو غیرفعال یا حذف کنید و فقط اون کانفیگ که خودتون درست کردین بنام iran رو فعال بگذارید.

الان اگه سرور دارید متصل بشید و از مرورگر کروم وارد سایت تامین اجتماعی از لینک پایین بشین اگه باز شد یعنی کار بدرستی انجام شده
[سایت تامین اجتماعی](https://account.tamin.ir/auth/login)

**Comment by Mehdiv97** [comment]
> > در نسخه ۱.۹.۲ به برنامه v2rayng بعد سبک برنامه عوض شده و کاستم رول نداره
> 
> سلام.
> 
> ابتدا فایل [iran.dat](https://github.com/bootmortis/iran-hosted-domains/releases/download/202410140035/iran.dat) را دانلود کنید
> 
> بعد از دانلود فایل، کلاینت V2RayNG رو باز کرده
> 
> سپس وارد صفحه همبرگری بشید.
> 
> در قسمت Routing Settings وارد بشید
> 
> سه نقطه عمودی رو بزنید
> 
> در قسمت geo asest file فایل ایران دات [iran.dat](https://github.com/bootmortis/iran-hosted-domains/releases/download/202410140035/iran.dat) که قبلا دانلود کردین و در پوشه Download دیوایس هست رو انتخاب کنید
> 
> دوباره در قسمت Routing Settings وارد بشید گزینه domain strategy روی IPifNonMatch قرار دهید
> 
> دکمه بیضافه + بالا رو برنید در قسمت remark بنويسيد iran در قسمت domain این عبارت رو کپی کنید و آنجا بزارید
> 
> `ext:iran.dat:all`
> 
> بقیه خانه ها خالی باشه
> 
> در پایین‌ترین قسمت بنام outboundTag گزینه direct رو انتخاب کنید.
> 
> تیک بالا رو بزنید تا تغییرات ذخیره بشه.
> 
> سپس تمام کانفیگ های بیرون که از قبل وجود داشته رو غیرفعال یا حذف کنید و فقط اون کانفیگ که خودتون درست کردین بنام iran رو فعال بگذارید.
> 
> الان اگه سرور دارید متصل بشید و از مرورگر کروم وارد سایت تامین اجتماعی از لینک پایین بشین اگه باز شد یعنی کار بدرستی انجام شده [سایت تامین اجتماعی](https://account.tamin.ir/auth/login)

مهندس این کارهارو انجام دادم اما فایده ای نداشت

**Comment by dreamboxone** [comment]
روش کار بسیار ساده است. وارد routing setting میشوید. دکمه سه نقطه بالا سمت راست را فشار میدهید و گزینه Import ruleset را انتخاب میکنید. پیامی خواهید دید مبنی بر اینکه تنظیمات فعلی پاک خواهند شد. دکمه OK را فشار دهید سپس گزینه Iran white list را انتخاب کنیدو تمام. تمامی سایت های ایرانی را دایرکت میکند

**Comment by Phoenix-999** [comment]
FYI @dreamboxone @Ahmadtamimi313 @Morteza561  

شما میتوانید از ربات آموزشی تلگرام برای دریافت این آموزش ها نیز استفاده کنید
[@IRAN_VPN_Guide_bot](https://t.me/IRAN_VPN_Guide_bot)

(Android) - V2RayNG برنامه Routing آموزش نصب و تنظیمات https://github.com/bootmortis/iran-hosted-domains/issues/88
https://github.com/iranxray/hope/issues/88
