### ISSUE TITLE
مشکل route

### ISSUE THREAD

**Issue by EsrflPk** [bootmortis/iran-hosted-domains#244]
توی ورژن جدید v2rayng چه دستوری باید بزنیم. ببخشید جواب پیدا نکردم تاپیک باز کردم

**Comment by Ahmadtamimi313** [comment]
سلام.

ابتدا فایل [iran.dat](https://github.com/bootmortis/iran-hosted-domains/releases/download/202410140035/iran.dat) را دانلود کنید

بعد از دانلود فایل، کلاینت V2RayNG رو باز کرده

سپس وارد صفحه همبرگری بشید.

در قسمت Routing Settings وارد بشید

سه نقطه عمودی رو بزنید

در قسمت geo asest file فایل ایران دات [iran.dat](https://github.com/bootmortis/iran-hosted-domains/releases/download/202410140035/iran.dat) که قبلا دانلود کردین و در پوشه Download دیوایس هست رو انتخاب کنید


دوباره در قسمت Routing Settings وارد بشید
گزینه domain strategy روی IPifNonMatch قرار دهید

دکمه بیضافه + بالا رو برنید در قسمت remark بنويسيد iran
در قسمت domain این عبارت رو کپی کنید و آنجا بزارید

`ext:iran.dat:all`

بقیه خانه ها خالی باشه

در  پایین‌ترین قسمت بنام  outboundTag
گزینه direct رو انتخاب کنید.

تیک بالا رو بزنید تا تغییرات ذخیره بشه.

سپس تمام کانفیگ های بیرون که از قبل وجود داشته رو غیرفعال یا حذف کنید و فقط اون کانفیگ که خودتون درست کردین بنام iran رو فعال بگذارید.

الان اگه سرور دارید متصل بشید و از مرورگر کروم وارد سایت تامین اجتماعی از لینک پایین بشین اگه باز شد یعنی کار بدرستی انجام شده
[سایت تامین اجتماعی](https://account.tamin.ir/auth/login)

**Comment by bootmortis** [comment]
Duplicate of #241
