### ISSUE TITLE
Add: https://saipa.iranecar.com

### ISSUE THREAD

**Issue by Mehdiv97** [bootmortis/iran-hosted-domains#246]
### Domain Address

https://saipa.iranecar.com

### Add or Remove

Added ✅

### Reason

Please add https://saipa.iranecar.com this site

### Verify Existing Domains

- [X] I have checked the list and confirmed the domain is not included

**Comment by bootmortis** [comment]
![image](https://github.com/user-attachments/assets/a2db31dc-9dc9-4bdf-92f4-c724293f84f2)
