### ISSUE TITLE
v2rayn نسخه مخصوص برای نرم افزار ویندوزی

### ISSUE THREAD

**Issue by mojit00l** [bootmortis/iran-hosted-domains#25]
سلام ممنون میشم یه کانفیگ هم برای این برنامه ویندوزی بسازین که بشه راحت ست کرد و قابلیت آپدیت هم داشته باشه

**Comment by mojit00l** [comment]
سلام ممنون میشم یه کانفیگ هم برای این برنامه ویندوزی بسازین که بشه راحت ست کرد و قابلیت آپدیت هم داشته باشه

**Comment by bootmortis** [comment]
https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md#v2rayn 

آموزشش اینجا هست
