### ISSUE TITLE
تغییر ساختار route 

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#26]
## Feature Request
https://github.com/iranxray/hope/blob/main/routing.md#%D9%85%D8%B3%D8%AF%D9%88%D8%AF%D8%B3%D8%A7%D8%B2%DB%8C-%D8%A7%D8%B2-%D8%B3%D9%85%D8%AA-%D8%B3%D8%B1%D9%88%D8%B1
### Description
مورد که وجود دارد اینکه در آموزش مطرح شده زمانیکه vpn روشن می باشد هر سایت ایرانی که باز شود از سمت سرور مسدود می شود و کاربر با vpn نمی تواند وارد سایت ایرانی شود. 

### Suggested Solution

اما عملکرد اصلی ک در برنامه مثل v2rayng و امثال اینها برای گزینه direct تعریف شده باز کردن سایت یا برنامه ایرانی با ایپی ایران است یا همان real ip بهتر هست کانفیگ را جوری تغییر دهید که کاربر برای رفتن به سایت یا نرم افزار ایرانی نیاز به قطع کردن vpn نداشته باشد و با همان ایپی ایران بتواند به راحتی اینکار را انجام دهد در حالتی که vpn هم وصل می باشد و این تنظیمات هم از سمت سرور اعمال شده باشد.

**Comment by bootmortis** [comment]
ایشو رو توی ریپو‌ی اشتباهی باز کردید. سمت سرور هم راهی جز بلاک نیست.
