### ISSUE TITLE
⚠️ Change ADS source

### ISSUE THREAD

**Issue by bootmortis** [bootmortis/iran-hosted-domains#27]
اینطور که من [از اینجا](https://github.com/v2fly/domain-list-community/pull/1376#issuecomment-1436324710) تازه متوجه شدم لایسنس این پروژه با لایسنس سورس تبلیغات ما یعنی [MasterKia/PersianBlocker](https://github.com/MasterKia/PersianBlocker) سازگاری نداره.
از این جهت باید سورس تبلیغات به سورسی که سازگار باشه تغییر پیدا کنه.

طبق پیشنهادی که @MasterKia [در اینجا](https://github.com/v2fly/domain-list-community/pull/1376#issuecomment-1439471319) داد می‌تونیم از یکی از دو تا سورس زیر استفاده کنیم:
- https://github.com/nimasaj/uBOPa/blob/master/uBOPa_Pihole.txt 
- https://github.com/farrokhi/adblock-iran/blob/master/pihole.txt

این ایشو رو قبل از اینکه تغییرات اعمال بشه می‌زارم چند روز باز باشه تا اینکه ببینم سورس بهتری سراغ دارید یا نه و اینکه اطلاع رسانی بشه بابت تغییر سورس
پ.ن.: در نحوه‌ی استفاده از پروژه تغییر و ناسازگاری‌ای نداریم.

read more:
- https://github.com/v2fly/domain-list-community/pull/1376

**Comment by MasterKia** [comment]
درود بر شما.

با توجه به این‌که توی README شما به درستی attribution انجام دادید من با وضعیت کنونی مشکلی ندارم.
اون ریپوی V2fly حتی حاضر نبودن attribution انجام بدن.

فقط اگه بتونید در اوایل README یه جمله اضافه بکنید که «کاربران، تبلیغات سایت‌های پارسی‌زبان رو به ریپوی PersianBlocker گزارش بدن»، خیلی خوب میشه.
اینم صرفاً یه پیشنهاد بود، چون همکاری بین لیست‌ها به سود همه‌ست (هم کاربران و هم صاحبان لیست‌).

**Comment by MasterKia** [comment]
اون دو تا لیستی هم که پیشنهاد دادم در ادامه‌اش نوشتم که یکیشون خیلی وقته ازش نگهداری نمیشه (آخرین بروزرسانیش برای ۲ سال پیش بوده).
اون یکی لیست هم همه دامنه‌های تبلیغاتی و ردیاب رو نداره و ناقصه.

**Comment by bootmortis** [comment]
> اون دو تا لیستی هم که پیشنهاد دادم در ادامه‌اش نوشتم که یکیشون خیلی وقته ازش نگهداری نمیشه (آخرین بروزرسانیش برای ۲ سال پیش بوده). اون یکی لیست هم همه دامنه‌های تبلیغاتی و ردیاب رو نداره و ناقصه.

چاره ای نیست گزینه‌ها یا تغییره یا حذف کلی بخش تبلیغات

**Comment by MasterKia** [comment]
من copyright holder لیست PersianBlocker هستم و با استفاده شدنش در لیست شما (به همین شکل فعلی) مشکلی ندارم.

اگر یادتون باشه افزوده شدن لیست PersianBlocker به درخواست کاربران و به پیشنهاد من بود (در ریپوی قبلی).

**Comment by bootmortis** [comment]
> من copyright holder لیست PersianBlocker هستم و با استفاده شدنش در لیست شما (به همین شکل فعلی) مشکلی ندارم.

مینتینر ریپو عوض شده، از همون اول مشکل لایسنس بوده و نباید مرج می‌شده.
همچنان مشکل لایسنس هست و بدون relicense شدن امکان استفاده وجود نداره.
همچین جریانی رو سر فونت وزیر و گوگل فونت هم داشتیم
خود جناب راستی کردار که فونت وزیر رو نوشتن می‌گفتن مشکلی نداره اما همچنان گوگل می‌گفت مشکل ساز هست.

**Comment by MasterKia** [comment]
درودی دوباره.
اگر کاربران تمایل به استفاده از لیست ارزشمند شما به همراه PersianBlocker رو دارن، بنده لیست Iran-Hosted-Domains رو فورک کردم و لیست PersianBlocker رو بهش برگردوندم.

https://github.com/MasterKia/iran-hosted-domains/releases/latest

با سپاس از شما.

**Comment by bootmortis** [comment]
@MasterKia  

سابلایسنس کردن اکیه اما باید لایسنس MIT پروژه دست نخورده باقی بمونه توی fork

https://github.com/bootmortis/iran-hosted-domains/blob/adffbc08ba971ce30baba0826f7e6f29a04291e0/LICENSE#L12-L13

می‌تونید در کنار لایسنس MIT لایسنس خودتون رو هم داشته باشین مشکلی نیست. [اطلاعات بیشتر](
https://www.reddit.com/r/freesoftware/comments/t0cfrv/comment/i09ugeg/?utm_source=share&utm_medium=web2x&context=3)

**Comment by MasterKia** [comment]
Hi. The GNU GPL requires that all the derivative works and any larger works containing the GPL-licensed code to be licensed under the _same_ license (i.e. GNU GPL).

GNU GPL:
> c) You must license the entire work, as a whole, under this License.

https://opensource.stackexchange.com/questions/12064/which-license-for-a-project-combining-mit-libraries-and-gpl-modified-files:
> The project as a whole indeed needs to be under the GPL license, as you use (or depend on) some GPL code.

So, in effect the whole "Iran-Hosted-Domains + PersianBlocker" project (including the "releases" files) should be legally licensed under the GPL.

BUT all the individual files on the "Iran-Hosted-Domains + PersianBlocker" are still under the MIT license. Nothing has changed.

The project as a whole should now be under GPL because it contains a part that is GPL.

Hope you understand.

**Comment by MasterKia** [comment]
The reason v2fly didn't "want" to use PersianBlocker was that they had to change their project's license to GPL as well, that's the "copyleft" part of GPL.

**Comment by bootmortis** [comment]
> BUT all the individual files on the "Iran-Hosted-Domains + PersianBlocker" are still under the MIT license. Nothing has changed.

شما کپی رایت لایسنس رو به طور کامل پاک کردید در [این کامیت](https://github.com/MasterKia/iran-hosted-domains/commit/b95c95528a8950d0cb00238b2f2d579222106285)

من در مورد وایولیشن لایسنس gpl ریپوی PersianBlocker صحبت نکردم، فورک [MasterKia/iran-hosted-domains](https://github.com/MasterKia/iran-hosted-domains) بند زیر لایسنس MIT این پروژه رو با پاک کردن کامل copyright notice زیر پا گذاشته:
https://github.com/bootmortis/iran-hosted-domains/blob/adffbc08ba971ce30baba0826f7e6f29a04291e0/LICENSE#L12-L13

**Comment by MasterKia** [comment]
Added a notice here:
https://github.com/MasterKia/iran-hosted-domains/blob/main/README.md#sources--acknowledgements

**Comment by bootmortis** [comment]
ممنون
ممکنه با مشورت بقیه مینتیتر ها در آینده لایسنس این پروژه رو به WTFPL تغییر بدم که حتی همین محدودیت notice هم برداشته بشه
بشخصه با محدودیت‌هایی که لایسنس‌ها میارن میونه خوبی ندارم

**Comment by MasterKia** [comment]
خواهش می‌کنم.
یکی از علت‌های GPL بودن PersianBlocker اینه که همه‌ی لیست‌های پیش‌فرض uBlock Origin و AdGuard هم GPL هستن و شاید نیاز بشه یک فیلتری رو ازون لیست‌ها قرض بگیرم و اون‌طوری اگه لایسنس همه لیست‌ها یکسان باشه مشکلی پیش نمیاد.

اینجا لایسنس همه لیست‌های موجود در uBlock Origin ذکر شده و بیشترشون GPL یا Creative Commons ShareAlike هستن:
https://github.com/uBlockOrigin/uBlock-issues/wiki/Filter-list-licenses

***
یه مشکلی که شاید بهش در آینده بر بخورید اینه که یک نفر لیست Iran-Hosted-Domains شما رو برمی‌داره، کلی دامنه جدید بهش اضافه می‌کنه و بهبود میدتش و بعد اون لیست رو روی سرورش اجرا می‌کنه و کاربران به سرور ایشون وصل میشن و غیرمستقیم از لیست شما استفاده می‌کنن.
در این حالت اگر لایسنس لیست شما AGPL می‌بود، اون‌وقت قانوناً صاحب سرور باید تغییرات و بهبود هایی که روی لیست شما اعمال کرده رو در اختیار همه کاربران اون سرور قرار بده و منطقاً این موضوع باعث رشد بیشتر لیست شما میشه؛ در واقع upstream هم از تغییرات و بهبود ها بهره می‌بره و یک رابطه دوطرفه بین upstream و downstream شکل می‌گیره.

در کل مفهوم [Copyleft](https://www.gnu.org/licenses/copyleft.en.html) در لایسنس‌ها، چیز جالب و سودمندیه.
