### ISSUE TITLE
Shadowrocket not Working.

### ISSUE THREAD

**Issue by hawshemi** [bootmortis/iran-hosted-domains#30]
Shadowrocket after updating to support vision flow, is not working with the `shadowrocket.conf` file in this repo.
For example, it will proxy google.com but it will block Instagram and youtube.
something is wrong with the config file.

Thanks

**Comment by hawshemi** [comment]
Any response or idea?
Or anyone tested this?

**Comment by bootmortis** [comment]
@hawshemi please test the new config from [newest release](https://github.com/bootmortis/iran-hosted-domains/releases/tag/202304081539) and lemme know if that works.

**Comment by hawshemi** [comment]
Issue is fixed.
Thanks.
