### ISSUE TITLE
Add `google.com`

### ISSUE THREAD

**Issue by AlirezaMoseni** [bootmortis/iran-hosted-domains#34]
سلام وقت بخیر اولا ممنون بابت زحماتتون
یه پیشنهاد داشتم باتوجه به اینکه اخیرا گوگل آی پی سرور هارو بلاک کرده و اجازه نمیده از طریق فیترشکن سرچ انجام بشه، گوگل و بقیه سایت های خارجی که فیلتر نیستن رو هم اضافه و یا یه لیست دیگه ازشون تهیه کنید که bypass بشن

**Comment by hawshemi** [comment]
اصلا خوب نیست این اتفاق. خود گوگل اگر با ip ایران وصل بشی به شدت محدود میشه و safe-browsing روشن میشه- بخاطر فیلترینگ ایران.
اگر مشکل captcha دارید، راه حل داره.

**Comment by bootmortis** [comment]
اضافه کردن گوگل به لیست از کانتکست این ریپو خارجه چرا که این ریپو صرفا لیستی از دامین های هاست شده در ایران هستش. خود کاربر می‌تونه تصمیم بگیره گوگل رو خودش اضافه کنه یا نه.
لیست دومین‌های مرتبط با گوگل رو می‌تونید اینجا پیدا کنید:  

https://github.com/v2fly/domain-list-community/blob/master/data/google

**Comment by fakhamatia** [comment]
> سلام وقت بخیر اولا ممنون بابت زحماتتون یه پیشنهاد داشتم باتوجه به اینکه اخیرا گوگل آی پی سرور هارو بلاک کرده و اجازه نمیده از طریق فیترشکن سرچ انجام بشه، گوگل و بقیه سایت های خارجی که فیلتر نیستن رو هم اضافه و یا یه لیست دیگه ازشون تهیه کنید که bypass بشن

شما میتونی با `geosite:google` گوگل رو بایپس کنی ، ولی به مشکل میخوری چون بیشتر سرویس های گوگل هم فیلتر هم تحریم
