### ISSUE TITLE
Nekoray tutorial is not correct

### ISSUE THREAD

**Issue by shokolatha** [bootmortis/iran-hosted-domains#35]
### Description

Hi,
The Nekoray tutorial to add domains misses a point where each line of the domains should start with "domain:".
eg. "tci.ir" should be converted to "domain: tci.ir" and then placed under direct domain category on routing settings of Nekoray.

### Steps to Reproduce

Just copied the contents of domains.txt in direct domain category on routing settings of Nekoray without any change to the contents.

### Expected Outcome

Expected to open Iranian websites like tci.ir with Nekoray started.

### Actual Outcome

Couldn't open the websites.

### Additional Information

Used Notepad++ to add a "domain:" text to each line of domains.txt and then copied the contents to direct domain category on routing settings of Nekoray.
The problem was solved after the mentioned change to contents.
Find and Replace settings used in Notepad++ to add the "domain:" text:
![image](https://user-images.githubusercontent.com/8199331/231483131-0d017141-14af-4a8b-9ac0-5127f179b535.png)

**Comment by bootmortis** [comment]
I've checked with domains.txt content and it works perfectly
![image](https://user-images.githubusercontent.com/120013889/232286875-8c80f116-3ee8-4491-9ed4-caf8149bf9f8.png)
![image](https://user-images.githubusercontent.com/120013889/232286887-be5bf7f3-7e95-4a57-926c-ece06ffa765a.png)

**Comment by fakhamatia** [comment]
چرا لیست رو اینجوری اضافه میکنید؟ من به روش زیر انجام دادم یعنی کار نمیکنه؟ فایلش رو هم ریختم این آدرس
 `/opt/nekoray/iran.dat`

![image](https://user-images.githubusercontent.com/20030910/232289587-563d8994-b2b5-4790-9447-cad2821b7b04.png)

**Comment by shokolatha** [comment]
> I've checked with domains.txt content and it works perfectly ![image](https://user-images.githubusercontent.com/120013889/232286875-8c80f116-3ee8-4491-9ed4-caf8149bf9f8.png) ![image](https://user-images.githubusercontent.com/120013889/232286887-be5bf7f3-7e95-4a57-926c-ece06ffa765a.png)

I tried again and I can confirm that I was wrong. The tutorial is correct. Sorry about that.



> چرا لیست رو اینجوری اضافه میکنید؟ من به روش زیر انجام دادم یعنی کار نمیکنه؟ فایلش رو هم ریختم این آدرس `/opt/nekoray/iran.dat`
> 
> ![image](https://user-images.githubusercontent.com/20030910/232289587-563d8994-b2b5-4790-9447-cad2821b7b04.png)

Can't find the specified folder : /opt/nekoray/iran.dat
