### ISSUE TITLE
مشکل در v2rayng

### ISSUE THREAD

**Issue by Dal1200** [bootmortis/iran-hosted-domains#36]
وقتی که فایل iran.dot سرجاش کپی میشه و rule ها ست میشن، موقع وصل شدن ارور 
Start service failed 
رو میده و هیچ کانفیگی وصل نمیشه دیگه، مگر rule ها رو پاک کنی

**Comment by R0sc0e0** [comment]
منم همین مشکل رو دارم.

**Comment by Dal1200** [comment]
من وقتی که فایل رو دستی کپی می‌کردم توی پوشه‌ی برنامه این مشکل پیش میومد، فایل iran.dot رو از توی خود برنامه، قسمت geo asset files اضافه کن، احتمالا درست بشه

**Comment by bootmortis** [comment]
لطفا [طبق آموزش جدید](https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md#v2rayng) تنظیمات رو روی نسخه‌ی به‌روز v2rayng انجام بدید و نتیجه رو به من اعلام کنید.
