### ISSUE TITLE
Blocking ads and trackers in the Clash format

### ISSUE THREAD

**Issue by MasterKia** [bootmortis/iran-hosted-domains#39]
Currently the `clash_rules.yaml` file only has bypass domains.

**Comment by bootmortis** [comment]
gonna w8 to see what happens with #38

**Comment by quantom9696** [comment]
> Currently the `clash_rules.yaml` file only has bypass domains.

https://github.com/SonyaCore/V2RayGen/blob/main/geodata/ads.txt

این لیست را هم در نظر بگیرید

**Comment by quantom9696** [comment]
در لیست بلاک ، قالب کلی باید بدین صورت باشد:

**Comment by MasterKia** [comment]
> https://github.com/SonyaCore/V2RayGen/blob/main/geodata/ads.txt
> 
> این لیست را هم در نظر بگیرید


این لیست، برگرفته از [PersianBlockerHosts](https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt) هست و گردانندگان این ریپو به خاطر لایسنس AGPL-3.0 بودنش ازش استفاده نکردن.

**Comment by quantom9696** [comment]
> gonna w8 to see what happens with #38
در لیست بلاک ، قالب کلی باید بدین صورت باشد:

https://github.com/bootmortis/iran-hosted-domains/issues/38#issuecomment-1542876067

**Comment by quantom9696** [comment]
در لیست دامین های بلاک شده، قالب کلی باید بدین صورت باشد:

https://github.com/bootmortis/iran-hosted-domains/issues/38#issuecomment-1542876067

**Comment by quantom9696** [comment]
> > https://github.com/SonyaCore/V2RayGen/blob/main/geodata/ads.txt
> > این لیست را هم در نظر بگیرید
> 
> این لیست، برگرفته از [PersianBlockerHosts](https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt) هست و گردانندگان این ریپو به خاطر لایسنس AGPL-3.0 بودنش ازش استفاده نکردن.

بهتره لیست نامبرده اصلی با دیتاهای جدید به روز بشه
