### ISSUE TITLE
استفاده از لیست اینماد

### ISSUE THREAD

**Issue by mmrabbani** [bootmortis/iran-hosted-domains#43]
با سلام
استفاده از لیست اینماد، می‌تواند لیست را بسیار غنی تر کند. بسیاری فروشگاه های ایرانی برای عضویت در ترافیک نیم بها اقدام نکردند. ولی به دلیل اجبار درگاه پرداخت، مجبور هستند در سایت اینماد ثبت نام کنند. لذا اضافه کردن این لیست می‌تواند کمک کننده باشد
https://enamad.ir/DomainListForMIMT

به عنوان یک مثال، فروشگاه sarabara.com و banimode.com و bimebazar.com فروشگاه های داخل ایران هستند که در سایت نیم بها ثبت نام نکرده و در نتیجه در این مخزن لیست نشده اند.

باتشکر فراوان

**Comment by bootmortis** [comment]
اینماد اینکه سایت باید داخل ایران هاست شده باشه رو اجباری می‌کنه یا سایتی که رو سرور خارج باشه هم تو لیستاش هست؟

**Comment by mmrabbani** [comment]
قانونش رو نمی‌دونم. ولی دو تا نکته داره
1. سایت های فروشگاهی به دلیل اختلال اینترنت تقریبا همه داخل ایران آمدند.
2. سایت های فروشگاهی رو بخوان کاری بکنند فیلتر نمی‌کنند، امتیاز اینماد شون رو می‌گیرند. پس میشه گفت تمام اون لیست فیلتر نیستند و میشه از ترافیک vpn خارج کرد.

**Comment by bootmortis** [comment]
اگر نمی‌شه با اطمینان گفت که این سایت‌ها همشون هاست شده ایران هستن نمی‌تونیم از این لیست به عنوان سورس استفاده کنیم.

**Comment by bootmortis** [comment]
بعد از بررسی بیشتر، احتمالا این لیست رو به عنوان سورس اضافه کنیم در آینده.

**Comment by bootmortis** [comment]
به زودی به ریپو اضافه می‌شه.
https://github.com/bootmortis/enamad-mirror
