### ISSUE TITLE
تنظیمات در برنامه نکوباکس

### ISSUE THREAD

**Issue by gransa** [bootmortis/iran-hosted-domains#44]
سلام و سپاس. تنظیمات برنامه نکوباکس به چه صورت هست چون نکوباکس پسوند dat رو قبول نمیکنه!
ممنون میشم راهنمایی بفرمائید.

**Comment by Tirbod** [comment]
چون هسته sing-box از iran-geosite.db بجاش باید استفاده کرد، ولی با اینکه میشه به assets اضافه کرد  کار نمیکنه چون[ پشتیبانی نمیکنه](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/110#issuecomment-1528936685) از استفاده بیشتر از یک منبع، ولی میشه کانفیگ کاستوم ساخت که بجای استفاده از geosite پیشفرض از iran-geosite.db استفاده کنه

**Comment by Tirbod** [comment]
> چون هسته sing-box از iran-geosite.db بجاش باید استفاده کرد

با اینکه اضافه میشه کرد ولی کار نمیکنه چون[ پشتیبانی نمیکنه](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/110#issuecomment-1528936685) از استفاده بیشتر از یک منبع، ولی میشه کانفیگ کاستوم ساخت که بجای استفاده از geosite پیشفرض از iran-geosite.db استفاده کنه

**Comment by gransa** [comment]
ممنون از راهنمایی تون. اگه بخوام به جای geosite.db از iran-geosite.db استفاده کنم مشکلی پیش نمیاد ؟ و چطور کانفیگ کاستوم بسازم ؟

**Comment by Tirbod** [comment]
نه مشکلی پیش نمیاد فقط دیگه از دسته بندی های geosite نمیتونید استفاده کنید مثل category-ads-all ولی اگه کانفیگ کاستوم بسازید فقط رو همون تاثیر داره رو کل اپ تاثیر نمیذاره.
برای کانفیگ کاستوم هم میتونید دقیقا همون سرور/کانفیگ که دارید رو share بزنید configuaration بعد export to clipboard ، بعد manual میتونید custom config اضافه کنید outbound هم نباشه بعد همین کانفیگ فعلی تون رو پیست کنید اونجا فقط قسمت route رو با این عوض کنید اگه دقیقا میخواید مثل route آموزش sagernet بشه :
```
  "route": {
    "geosite": {
      "path": "iran-geosite.db",
      "download_url": "https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran-geosite.db"
    },
    "auto_detect_interface": true,
    "rules": [
      {
        "outbound": "dns-out",
        "port": [
          53
        ]
      },
      {
        "inbound": [
          "dns-in"
        ],
        "outbound": "dns-out"
      },
      {
        "geosite": [
          "other"
        ],
        "outbound": "bypass"
      },
      {
        "geosite": [
          "ads"
        ],
        "outbound": "block"
      },
      {
        "domain_suffix": [
          "ir"
        ],
        "outbound": "bypass"
      },
      {
        "geoip": [
          "ir"
        ],
        "outbound": "bypass"
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block",
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
      }
    ]
  }
```

**Comment by EndermanCo** [comment]
یک راه دیگری هم هست که احتمالا جواب میده.
فایل iran-geosite.db رو به فایل geosite.db تغییر نام بدید و وارد کنید. و اون ۲ تا rule برای ایران رو فعال کنید.

**Comment by gransa** [comment]
ببخشید اون کانفیگ شما رو جایگزین قسمت route کانفیگ کنم ؟ مثلا برای این کانفیگ چطور باید تغییر بدم؟
{
  "dns": {
    "rules": [
      {
        "domain": [
          "cdnjs.com"
        ],
        "server": "dns-direct"
      },
      {
        "disable_cache": true,
        "domain_suffix": [
          ".arpa.",
          ".arpa"
        ],
        "server": "dns-block"
      }
    ],
    "servers": [
      {
        "address": "https://77.88.8.8/dns-query",
        "address_resolver": "dns-direct",
        "tag": "dns-remote"
      },
      {
        "address": "underlying://0.0.0.0",
        "address_resolver": "dns-local",
        "detour": "direct",
        "tag": "dns-direct"
      },
      {
        "address": "underlying://0.0.0.0",
        "detour": "direct",
        "tag": "dns-local"
      },
      {
        "address": "rcode://success",
        "tag": "dns-block"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "listen_port": 6450,
      "override_address": "8.8.8.8",
      "override_port": 53,
      "tag": "dns-in",
      "type": "direct"
    },
    {
      "domain_strategy": "ipv4_only",
      "endpoint_independent_nat": true,
      "inet4_address": [
        "172.19.0.1/28"
      ],
      "sniff": true,
      "stack": "system",
      "tag": "tun-in",
      "type": "tun"
    },
    {
      "domain_strategy": "ipv4_only",
      "listen": "127.0.0.1",
      "listen_port": 2080,
      "sniff": true,
      "tag": "mixed-in",
      "type": "mixed"
    }
  ],
  "log": {
    "level": "panic"
  },
  "outbounds": [
    {
      "alter_id": 0,
      "packet_encoding": "",
      "security": "auto",
      "server": "cdnjs.com",
      "server_port": 443,
      "tls": {
        "enabled": true,
        "insecure": false,
        "server_name": "Dusseldorf.kotick.site"
      },
      "transport": {
        "headers": {
          "Host": "Dusseldorf.kotick.site"
        },
        "path": "/speedtest",
        "type": "ws"
      },
      "uuid": "6158F3F7-F3D1-4F5B-A725-FCE087782C33",
      "type": "vmess",
      "tag": "proxy",
      "domain_strategy": "ipv4_only"
    },
    {
      "tag": "direct",
      "type": "direct"
    },
    {
      "tag": "bypass",
      "type": "direct"
    },
    {
      "tag": "block",
      "type": "block"
    },
    {
      "tag": "dns-out",
      "type": "dns"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "outbound": "dns-out",
        "port": [
          53
        ]
      },
      {
        "inbound": [
          "dns-in"
        ],
        "outbound": "dns-out"
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block",
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
      }
    ]
  }
}

**Comment by Tirbod** [comment]
باید این قسمت رو از کانفیگ حذف و با قسمتی که فرستادم جایگزین کنید:
```
    "route": {
        "auto_detect_interface": true,
        "rules": [
            {
                "outbound": "dns-out",
                "port": [
                    53
                ]
            },
            {
                "inbound": [
                    "dns-in"
                ],
                "outbound": "dns-out"
            },
            {
                "ip_cidr": [
                    "224.0.0.0/3",
                    "ff00::/8"
                ],
                "outbound": "block",
                "source_ip_cidr": [
                    "224.0.0.0/3",
                    "ff00::/8"
                ]
            }
        ]
    }
```
که بعد از جایگذاری کانفیگی که فرستادید به این شکل باید باشه:
```
{
    "dns": {
        "rules": [
            {
                "domain": [
                    "cdnjs.com"
                ],
                "server": "dns-direct"
            },
            {
                "disable_cache": true,
                "domain_suffix": [
                    ".arpa.",
                    ".arpa"
                ],
                "server": "dns-block"
            }
        ],
        "servers": [
            {
                "address": "https://77.88.8.8/dns-query",
                "address_resolver": "dns-direct",
                "tag": "dns-remote"
            },
            {
                "address": "underlying://0.0.0.0",
                "address_resolver": "dns-local",
                "detour": "direct",
                "tag": "dns-direct"
            },
            {
                "address": "underlying://0.0.0.0",
                "detour": "direct",
                "tag": "dns-local"
            },
            {
                "address": "rcode://success",
                "tag": "dns-block"
            }
        ],
        "strategy": "ipv4_only"
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "listen_port": 6450,
            "override_address": "8.8.8.8",
            "override_port": 53,
            "tag": "dns-in",
            "type": "direct"
        },
        {
            "domain_strategy": "ipv4_only",
            "endpoint_independent_nat": true,
            "inet4_address": [
                "172.19.0.1/28"
            ],
            "sniff": true,
            "stack": "system",
            "tag": "tun-in",
            "type": "tun"
        },
        {
            "domain_strategy": "ipv4_only",
            "listen": "127.0.0.1",
            "listen_port": 2080,
            "sniff": true,
            "tag": "mixed-in",
            "type": "mixed"
        }
    ],
    "log": {
        "level": "panic"
    },
    "outbounds": [
        {
            "alter_id": 0,
            "packet_encoding": "",
            "security": "auto",
            "server": "cdnjs.com",
            "server_port": 443,
            "tls": {
                "enabled": true,
                "insecure": false,
                "server_name": "Dusseldorf.kotick.site"
            },
            "transport": {
                "headers": {
                    "Host": "Dusseldorf.kotick.site"
                },
                "path": "/speedtest",
                "type": "ws"
            },
            "uuid": "6158F3F7-F3D1-4F5B-A725-FCE087782C33",
            "type": "vmess",
            "tag": "proxy",
            "domain_strategy": "ipv4_only"
        },
        {
            "tag": "direct",
            "type": "direct"
        },
        {
            "tag": "bypass",
            "type": "direct"
        },
        {
            "tag": "block",
            "type": "block"
        },
        {
            "tag": "dns-out",
            "type": "dns"
        }
    ],
    "route": {
        "geosite": {
            "path": "iran-geosite.db",
            "download_url": "https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran-geosite.db"
        },
        "auto_detect_interface": true,
        "rules": [
            {
                "outbound": "dns-out",
                "port": [
                    53
                ]
            },
            {
                "inbound": [
                    "dns-in"
                ],
                "outbound": "dns-out"
            },
            {
                "geosite": [
                    "other"
                ],
                "outbound": "bypass"
            },
            {
                "geosite": [
                    "ads"
                ],
                "outbound": "block"
            },
            {
                "domain_suffix": [
                    "ir"
                ],
                "outbound": "bypass"
            },
            {
                "geoip": [
                    "ir"
                ],
                "outbound": "bypass"
            },
            {
                "ip_cidr": [
                    "224.0.0.0/3",
                    "ff00::/8"
                ],
                "outbound": "block",
                "source_ip_cidr": [
                    "224.0.0.0/3",
                    "ff00::/8"
                ]
            }
        ]
    }
}

```

**Comment by gransa** [comment]
پس منم درست انجام دادم ولی مشکل اینه که کانفیگ جدید اضافه نمیشه به کلاینت و ارور میده. میشه یه بار دیگه کد خودتون رو چک کنید؟ مرسی

**Comment by Tirbod** [comment]
الان من چک کردم دقیقا کانفیگ کامل بعد از جایگذاری رو کپی کردم و به کلاینت راحت اضافه شد ، الان این رو کامل کپی میکنید import from clipboard هم بزنید ارور میده و اضافه نمیشه؟

**Comment by gransa** [comment]
آره الآن اضافه شد!! ولی ارور میده وصل نمیشه !!
https://freeimage.host/i/HSnAbkP

**Comment by gransa** [comment]
به نظر نمیتونه به این آدرس وصل شه:
https://github.com/bootmortis/iran-hosted-domains/releases/download/202304210054/iran-geosite.db

**Comment by gransa** [comment]
با اینترنت شاتل وصل نشد ولی الآن با ایرانسل امتحان کردم اکی هست. خیلی خیلی ممنونم از راهنمایی تون.

**Comment by ghost** [comment]
یک راه دیگری هم هست که احتمالا جواب میده.
فایل iran-geosite.db رو به فایل geosite.db تغییر نام بدید و وارد کنید. و اون ۳ تا rule برای ایران رو فعال کنید.
این مورد برای من کار میکنه.

**Comment by gransa** [comment]
تغییر نام دادم و وارد کردم. کدام دو تا rule منظورتونه ؟

**Comment by gransa** [comment]
این دوتا منظورتونه ؟

Bypass Iran .ir Domains:
domain: regexp:.+\.ir$
outbound: Bypass

Bypass Iran geoip:
ip: geoip:ir
outbound: Bypass

**Comment by ghost** [comment]
> تغییر نام دادم و وارد کردم. کدام دو تا rule منظورتونه ؟



> یک راه دیگری هم هست که احتمالا جواب میده. فایل iran-geosite.db رو به فایل geosite.db تغییر نام بدید و وارد کنید. و اون ۲ تا rule برای ایران رو فعال کنید. این مورد برای من کار میکنه.

من یادم رفته بود بگم اون ruleها چیه. عذرخواهی میکنم.
این rule ها رو ایجاد کنید:
name=Bypass Iran non .ir Domains
domain=ext:geosite.db:other
outbound:bypass

name=Bypass Iran geoip
ip=geoip:ir
outbound:bypass

name=Bypass Iran .ir domains
domain=regexp:.+\.ir$
               ext:geosite.db:ir
outbound:bypass

name=Bypass category Iran
domain=geosite:category-ir
outbound:bypass

**Comment by gransa** [comment]
ببخشید rule دومی گزینه تو قسمت دومین باید اینه رو بنویسیم دیگه
regexp:.+.ir$ ext:iran-geosite.db:ir
چون انگار rule دومی چهار قسمتی هست!

**Comment by ghost** [comment]
> ببخشید rule دومی گزینه تو قسمت دومین باید اینه رو بنویسیم دیگه regexp:.+.ir$ ext:iran-geosite.db:ir چون انگار rule دومی چهار قسمتی هست!

4 rule هستن و بله اینجوری باید وارد کنید.
فقط یه نکته ای هست که توی rule سوم باید بعد از نوشتن بخش اول یه اینتر بزنین و بخش دوم دامنه(منظورم اونیه که با ext شروع میشه) رو بنویسید.

**Comment by gransa** [comment]
همین کار رو کردم. ممنونم.
یه تستی از این سایت گرفتم 

https://parspack.com/blog/hosting/what-is-my-ip

با تنظیمات کانفیگی تو نکوباکس و تنظیمات route ماتسوری چک کردم و آی پی رو ایران میزنه ولی با این تنظیمات route تو نکوباکس ( آخری ) آی پی سرور ( کانفیگ مورد استفاده ) رو میزنه ! 
اگه امکان داره یه تست کنین ببینم مشکل از تنظیمات route منه یا چیزی دیگه ای ( چند بار تنظیمات رو چک کردم ولی آی پی همون آی پی کانفیگه ). مرسی

**Comment by ghost** [comment]
سلام تست کردم اصلاحش میکنم. مجددا تست کنید با رول جدید

**Comment by gransa** [comment]
تست کردم ولی بازم آی پی سرور رو نشون میده و نه آی پی ایران

**Comment by ghost** [comment]
این سامانه باگ داره فکر کنم آیپی ها رو درست تشخیص نمیده. الان میزنه آی پی من مال ایرانه. اگر آیپی سرور باشه باید بنویسه که مال یه کشور دیگه است.

**Comment by gransa** [comment]
اکی. واقعا ممنون از کمکتون. لطف کردین 🙏🙏🙏

**Comment by fakhamatia** [comment]
> چون هسته sing-box از iran-geosite.db بجاش باید استفاده کرد، ولی با اینکه میشه به assets اضافه کرد کار نمیکنه چون[ پشتیبانی نمیکنه](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/110#issuecomment-1528936685) از استفاده بیشتر از یک منبع، ولی میشه کانفیگ کاستوم ساخت که بجای استفاده از geosite پیشفرض از iran-geosite.db استفاده کنه

چرا باید برای سایت های ایرانی یه ریپو جدید ساخته میشد؟ چرا لیست دامین هارو داخل ریپو اصلی `domain-list-community`  نذاشتید از اول؟
اخه فایل geosite تقریبا توی بیشتر کلاینت های v2ray از قبل هست و آپدیت راحت تری داره.
این مشکل عدم پشتیبانی از چند فایل هم مزاحم نمیشد.

**Comment by Tirbod** [comment]
> > چون هسته sing-box از iran-geosite.db بجاش باید استفاده کرد، ولی با اینکه میشه به assets اضافه کرد کار نمیکنه چون[ پشتیبانی نمیکنه](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/110#issuecomment-1528936685) از استفاده بیشتر از یک منبع، ولی میشه کانفیگ کاستوم ساخت که بجای استفاده از geosite پیشفرض از iran-geosite.db استفاده کنه
> 
> چرا باید برای سایت های ایرانی یه ریپو جدید ساخته میشد؟ چرا لیست دامین هارو داخل ریپو اصلی `domain-list-community` نذاشتید از اول؟ اخه فایل geosite تقریبا توی بیشتر کلاینت های v2ray از قبل هست و آپدیت راحت تری داره. این مشکل عدم پشتیبانی از چند فایل هم مزاحم نمیشد.

قبلا چندبار پیشنهاد دادن تو خود ریپو `domain-list-community` ولی چون ITO GOV که استفاده میشه کاملا قابل اعتماد نیست و دامنه های غیرمربوط به ایرانم داخلش هست مثل `googleapis.com` و لیست دامنه ها زیاده و نمیشه تک تک بررسی کنن که اشتباه هست یا نه اضافه نشده.

**Comment by bootmortis** [comment]
دوستان متاسفانه من سرم شلوغ هست و فرصت آزمون و خطا در مورد نکوباکس رو ندارم، لطفا اگر به نتیجه قطعی رسیدید PR بدید آموزشش رو اضافه کنید.

**Comment by Graveyard9988** [comment]
> دوستان متاسفانه من سرم شلوغ هست و فرصت آزمون و خطا در مورد نکوباکس رو ندارم، لطفا اگر به نتیجه قطعی رسیدید PR بدید آموزشش رو اضافه کنید.

https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/135

**Comment by Graveyard9988** [comment]
> دوستان متاسفانه من سرم شلوغ هست و فرصت آزمون و خطا در مورد نکوباکس رو ندارم، لطفا اگر به نتیجه قطعی رسیدید PR بدید آموزشش رو اضافه کنید.

اگر issue رو با عنوان not planned بست ، لطفا شما نیز درخواست دهید

**Comment by ghost** [comment]
سلام
۱.هسته sing-box از چند فایل geo پشتیبانی نداره بنابر این باید اول درخواست بدیم که sing-box پشتیبانی بکنه.
که در خواست دادم:
https://github.com/SagerNet/sing-box/issues/595
۲.به نظر میاد تا این مشکل حل بشه خیلی طول میکشه بنظرم بریم و درخواست ادغام دامنه‌ها رو در loyalsoldier بدیم.
 من با خود سازنده صحبت کردم گفت بهتره به‌ v2fly بفرستیم یا geosite اصلی دستکاری بشه تا اون موقع به هر دوی اینها این درخواستو بفرستیم چون نکوباکس از loyalsoldier استفاده میکنه
(البته خود این هم‌ بخشی از منابعش از v2flyئه پس اگر در v2 ادغام بشه تو اینم میاد.)
