### ISSUE TITLE
create geoip in addition to geosite

### ISSUE THREAD

**Issue by mmrabbani** [bootmortis/iran-hosted-domains#46]
سلام
نمیدونم این پیشنهادی که خدمتتون میدم، در حوزه این پروژه است یا خیر. اگر لیست IP های ایران را با دقت بیشتری داشته باشیم، تعداد زیادی دامنه را یکباره اضافه در نظر گرفتیم
پروژه v2ray لیست IP را از پروژه زیر می‌گیرد
https://github.com/v2fly/geoip
این پروژه هم لیست را از Maxmind می‌گیرد و آن را به فایل DAT برای استفاده v2ray تبدیل می‌کند.
https://dev.maxmind.com/geoip/geoip2/geolite2/
متاسفانه پروژه Maxmind چندان بر روی IP های ایران دقیق نیست.

این پروژه می‌تواند از همان کد v2fly/geoip استفاده کند و به جای دیتابیس Maxmind، از دیتابیس‌های دیگر استفاده کند تا لیست خیلی کامل‌تری از IP های ایران ایجاد کند. در این صورت سایت ها و سرویس های زیادی به یکباره در نظر گرفته می‌شوند.
چند دیتابیس که می‌تواند استفاده شود را در زیر نوشتم. طبیعتا لیست های دیگری هم میتوانند در نظر گرفته بشوند.
۱. دیتابیس IP2location
https://lite.ip2location.com/iran-(islamic-republic-of)-ip-address-ranges
این سایت اطلاعات را به صورت رایگان و در فرمت های مختلف مانند csv و txt برای دانلود قرار داده است.
۲. وبسایت nirsoft که دیتابیس را به فرمت csv در اختیار می‌گذارد. البته اطلاعات چندان جدید نیست
https://www.nirsoft.net/countryip/ir_date.html
۳. لیست IPهای آروان. بعضی از این لیست برای کشورهای مختلف ثبت شدند. البته که با استفاده از anycast این IP ها جای مشخصی ندارند و می‌توانیم آن را ایرانی در نظر بگیریم.
https://www.arvancloud.ir/fa/dev/ips
این لیست هم به صورت txt در دسترس است.

**Comment by bootmortis** [comment]
این ریپو همینطور که از اسمش مشخصه صرفا روی دومین ها تمرکز داره
برای ای پی می‌تونین از میررور زیر استفاده کنین:
https://github.com/bootmortis/ito-gov-mirror/
