### ISSUE TITLE
⚠️ اطلاعیه در مورد تغییر قوانین کلش⚠️

### ISSUE THREAD

**Issue by bootmortis** [bootmortis/iran-hosted-domains#49]
قوانین و فایل‌های مرتبط با Clash اخیرا تغییر کرده‌اند #45، لطفا از فایل‌ها و قوانین جدید [توضیح داده شده در داکیومنت](https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md#clash-like-clashx--clash_for_windows_pkg--clash-net--) استفاده کنید.

**Comment by hooman-nourbakhsh** [comment]
سلام این تغییرات اخیر برای این نسخه اندروید 
https://github.com/Kr328/ClashForAndroid/releases/tag/v2.5.12

که متاسفانه 1 سال آپدیت نشده کار نمی کند زیرا هسته آن بروزرسانی نمی شود.

![photo_2023-05-07_21-04-50](https://user-images.githubusercontent.com/30972110/236691939-6ea424db-1a40-4e22-a8d5-51020ce200b6.jpg)

**Comment by bootmortis** [comment]
@matador7495 
‮امکانش هست کلش متا رو تست کنید؟

https://github.com/MetaCubeX/Clash.Meta

**Comment by quantom9696** [comment]
لینک جدیدی که قرار دادید در اخرین نسخه از کلش متا 2.7.4 (گیتهاب) ایمپورت شد

**Comment by quantom9696** [comment]
لینک جدیدی که قرار دادید در اخرین نسخه از کلش متا 2.7.4 (گیتهاب) اندروید ایمپورت شد

**Comment by quantom9696** [comment]
> لینک جدیدی که قرار دادید در اخرین نسخه از کلش متا 2.7.4 (گیتهاب) ایمپورت شد

**Comment by bootmortis** [comment]
> لینک جدیدی که قرار دادید در اخرین نسخه از کلش متا 2.7.4 (گیتهاب) اندروید ایمپورت شد

پس توی کلش متا مشکلی نیست؟ ولی توی کلش اندروید هست؟ اگر می‌شه تایید کنید توی توضیحات می‌خوام بنویسم.

**Comment by hooman-nourbakhsh** [comment]
اوکی امروز تست میکنم فقط یک سوال در نسخه اندروید کلش متا فرق بین نسخه اندروید cgo با معمولی چیه؟

**Comment by quantom9696** [comment]
> > لینک جدیدی که قرار دادید در اخرین نسخه از کلش متا 2.7.4 (گیتهاب) اندروید ایمپورت شد
> 
> پس توی کلش متا مشکلی نیست؟ ولی توی کلش اندروید هست؟ اگر می‌شه تایید کنید توی توضیحات می‌خوام بنویسم.

در کلش متا تست شده برای احتیاط لینک ساب زیر را چک کنید و در کلش متا اندروید 2.7.4 خودتان هم اضافه کنید:

https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet_META_IRAN-Direct.yml


قوانین جدید شما در لینک فوق وجود داره و ایمپورت میشه

بایستی قالب لیست دامین های شما (چه بای پس و چه تبلیغاتی) بایستی به صورت زیر باشد:
https://github.com/bootmortis/iran-hosted-domains/issues/38#issuecomment-1542876067

**Comment by quantom9696** [comment]
> > لینک جدیدی که قرار دادید در اخرین نسخه از کلش متا 2.7.4 (گیتهاب) اندروید ایمپورت شد
> 
> پس توی کلش متا مشکلی نیست؟ ولی توی کلش اندروید هست؟ اگر می‌شه تایید کنید توی توضیحات می‌خوام بنویسم.

https://github.com/bootmortis/iran-hosted-domains/issues/38#issuecomment-1542876067

**Comment by bootmortis** [comment]
@matador7495 @quantom9696 
به لطف @Tirbod، ساپورت نسخه‌ی قدیمی در #54 مجددا به ریپو اضافه شد.

**Comment by bootmortis** [comment]
به لطف @Tirbod، ساپورت نسخه‌ی قدیمی در #54 مجددا به ریپو اضافه شد.

@matador7495 @quantom9696

**Comment by Graveyard9988** [comment]
> به لطف @Tirbod، ساپورت نسخه‌ی قدیمی در #54 مجددا به ریپو اضافه شد.
> 
> @matador7495 @quantom9696

لطفا علامت + را از پشت دامین ها حذف کنید ، در هیچ قالب چینی و منابع علامت + پشت دامین وجود ندارد!

**Comment by Graveyard9988** [comment]
> اوکی امروز تست میکنم فقط یک سوال در نسخه اندروید کلش متا فرق بین نسخه اندروید cgo با معمولی چیه؟

لطفا علامت + و نقطه را از پشت دامین ها حذف کنید ، در هیچ قالب چینی و منابع اصلی علامت + و نقطه پشت دامین وجود ندارد!

**Comment by hooman-nourbakhsh** [comment]
> > اوکی امروز تست میکنم فقط یک سوال در نسخه اندروید کلش متا فرق بین نسخه اندروید cgo با معمولی چیه؟
> 
> لطفا علامت + را از پشت دامین ها حذف کنید ، در هیچ قالب چینی و منابع اصلی علامت + پشت دامین وجود ندارد!

منم فک کنم به همین دلیل شاید با نسخه اندروید اوکی نبود برام !

**Comment by Graveyard9988** [comment]
باید پشت دامین بدون + و نقطه باشد و اول و آخر دامین ' قرار دهید

**Comment by Tirbod** [comment]
> > اوکی امروز تست میکنم فقط یک سوال در نسخه اندروید کلش متا فرق بین نسخه اندروید cgo با معمولی چیه؟
> 
> لطفا علامت + و نقطه را از پشت دامین ها حذف کنید ، در هیچ قالب چینی و منابع اصلی علامت + و نقطه پشت دامین وجود ندارد!

برای اینکه هم دامین اصلی هم تمام ساب دامین هاش مچ بشه [باید از + استفاده بشه](https://lancellc.gitbook.io/clash/clash-config-file/syntax#+-wildcard)
نمیدونم شما کدوم منبع یا قالبی رو چک کردید که ندیدید، میتونید [این ریپو ](https://github.com/Loyalsoldier/clash-rules) رو چک کنید برای نمونه های yaml، مثلا:
https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt

**Comment by Graveyard9988** [comment]
> > > اوکی امروز تست میکنم فقط یک سوال در نسخه اندروید کلش متا فرق بین نسخه اندروید cgo با معمولی چیه؟
> > 
> > 
> > لطفا علامت + و نقطه را از پشت دامین ها حذف کنید ، در هیچ قالب چینی و منابع اصلی علامت + و نقطه پشت دامین وجود ندارد!
> 
> برای اینکه هم دامین اصلی هم تمام ساب دامین هاش مچ بشه [باید از + استفاده بشه](https://lancellc.gitbook.io/clash/clash-config-file/syntax#+-wildcard) نمیدونم شما کدوم منبع یا قالبی رو چک کردید که ندیدید، میتونید [این ریپو ](https://github.com/Loyalsoldier/clash-rules) رو چک کنید برای نمونه های yaml، مثلا: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt

ایا برای دامین های غیر اپل هم همینطور است؟
لطفا برای سایر دامین ها هم لینک مشابه قبلی که لطف کردید، بفرستید تا بررسی کنم. 
چون معیار من کلش متا هم هست

و سوال دوم: آیا این قالب شما در کلش بای پس کرده؟

**Comment by Tirbod** [comment]
> > > > اوکی امروز تست میکنم فقط یک سوال در نسخه اندروید کلش متا فرق بین نسخه اندروید cgo با معمولی چیه؟
> > > 
> > > 
> > > لطفا علامت + و نقطه را از پشت دامین ها حذف کنید ، در هیچ قالب چینی و منابع اصلی علامت + و نقطه پشت دامین وجود ندارد!
> > 
> > 
> > برای اینکه هم دامین اصلی هم تمام ساب دامین هاش مچ بشه [باید از + استفاده بشه](https://lancellc.gitbook.io/clash/clash-config-file/syntax#+-wildcard) نمیدونم شما کدوم منبع یا قالبی رو چک کردید که ندیدید، میتونید [این ریپو ](https://github.com/Loyalsoldier/clash-rules) رو چک کنید برای نمونه های yaml، مثلا: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
> 
> ایا برای دامین های غیر اپل هم همینطور است؟ لطفا برای سایر دامین ها هم لینک مشابه قبلی که لطف کردید، بفرستید تا بررسی کنم. چون معیار من کلش متا هم هست
> 
> و سوال دوم: آیا این قالب شما در کلش بای پس کرده؟

اپل و غیر اپل چه فرقی داره؟ نمونه تو همون ریپو زیاده و لینک wiki هم گذاشتم.
برای کلش متا هم [wiki خودش](https://clash-meta.wiki/config/#_12) هست که فرقی نمیکنه.

**Comment by Graveyard9988** [comment]
اگر در قالب کلی کلش متا هم بدین صورته پس مشکلی نیست
پیش تر در قالب های چینی موجود در گیت هاب این مدلی ندیده بودم!

**Comment by bootmortis** [comment]
از اونجایی که مجددا نیازه که اطلاعیه برای تغییر قوانین بزنیم (#64) این ایشو رو می‌بندم و ایشوی جدیدی رو باز می‌کنم.
