### ISSUE TITLE
اسم ثابت برای فایل

### ISSUE THREAD

**Issue by hadiomid** [bootmortis/iran-hosted-domains#5]
سلام
اسم فایل ثابت باشه بهتره که بشه همیشه از یک آدرس مشخص فراخوانی کرد.

ممنون

**Comment by bootmortis** [comment]
سلام
متوجه منظورتون نشدم
اسم فایلها ثابته.

**Comment by hadiomid** [comment]
اشتباه متوجه شده بودم
اوکیه
