### ISSUE TITLE
Sanctioned websites

### ISSUE THREAD

**Issue by hiddify-com** [bootmortis/iran-hosted-domains#50]
## Feature Request
Add a category for sanctioned websites
### Description

[Please see this file](https://docs.google.com/spreadsheets/d/1cUfx4ZugjOnZC44FZx7ZXZwIHBASwp6G8nRj7bvSS10/edit?usp=share_link)

Even that it is not updated, it can be a good starting point

### Motivation
We can have whitelist and blacklist domains to help user to choose bypass or proxy specific domains

### Example

chatgpt is blocked in Iran

**Comment by bootmortis** [comment]
The repo name is **Iran Hosted** Domains, so this enhancement is out of this repository's context.

**Comment by hiddify-com** [comment]
but it is related to iran so there is no better place than your repository- i think

**Comment by bootmortis** [comment]
[freedomofdevelopers/fod](https://github.com/freedomofdevelopers/fod) already done this.

**Comment by hiddify-com** [comment]
Great you are so lovely ❤️
