### ISSUE TITLE
Add blocked webistes in Iran

### ISSUE THREAD

**Issue by hiddify-com** [bootmortis/iran-hosted-domains#51]
## Feature Request
If we have a list of well used blocked websites with their resources (e.g., css) we can easily choose only blocked websites to use proxy. This will help to have a seamless access to internet.  

We have a script that test blocked websites from ooni and extract the resources and external links.
Please checkout our repository: https://github.com/hiddify/filterchi_report

**Comment by bootmortis** [comment]
Thanks, but closed with the same reasons as #50. our focus is only on Iran-hosted domains for now.
