### ISSUE TITLE
SwitchyOmega Rule Set

### ISSUE THREAD

**Issue by elrazez** [bootmortis/iran-hosted-domains#57]
### Description

It would be great to have a switchyomega rule list as it is being widely used by iranians.

### Example

[https://github.com/dvershinin/switchy-rules](https://github.com/dvershinin/switchy-rules)

**Comment by bootmortis** [comment]
Hi, we already have that: https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/switchy_omega.txt
