### ISSUE TITLE
راهنمایی در مورد آموزش ریپوی iranxray/hope

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#58]
## Bug Report
سلام گویا فایل dat دچار تغییراتی شده که باعث شده این آموزش
https://github.com/iranxray/hope/blob/main/routing.md

دیگه جوابگو نباشه چون موقع استفاده خطا میده که category مورد استفاده پیدا نشد
### Description

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/f6de2fee-cc84-49e3-b8b6-125ffae6afc0)

            "regexp:.*\\.ir$",
            "ext:iran.dat:ir",
            "ext:iran.dat:other",
            "geosite:category-ir-gov",
            "geosite:category-ir-news",
            "geosite:category-ir-bank",
            "geosite:category-ir-tech",
            "geosite:category-ir-travel",
            "geosite:category-ir-shopping",
            "geosite:category-ir-insurance",
            "geosite:category-ir-scholar",

منظور بنده این بخش است.

اگر تغییراتی کرده لطفا سریعتر اطلاع رسانی کنید و آموزش مورد نظر هم بروزرسانی بشه

**Comment by bootmortis** [comment]
سلام
در مرحله اول ایشو رو باید در ریپو hope باز کنید.
ولی فایل .dat ریپوی ما تغییری نداشته.
البته من در مورد اصلاح آموزش اطلاع رسانی کردم خیلی وقت پیش: https://github.com/iranxray/hope/issues/66

**Comment by hooman-nourbakhsh** [comment]
> سلام در مرحله اول ایشو رو باید در ریپو hope باز کنید. ولی فایل .dat ریپوی ما تغییری نداشته. البته من در مورد اصلاح آموزش اطلاع رسانی کردم خیلی وقت پیش: [iranxray/hope#66](https://github.com/iranxray/hope/issues/66)

یعنی الان من به این صورت استفاده کنم اوکی هست و فقط فایل iran.dat دانلود کنم

      {
        "outboundTag": "blocked",
          "domain": [
            "regexp:.*\\.ir$",
            "ext:iran.dat:ir",
            "ext:iran.dat:other",
            "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
          ],
        "type": "field"
      }

**Comment by bootmortis** [comment]
بله نیازی به استفاده از دیتا‌های مربوط به ایران ریپوی v2fly نیست. لیست ما در حال حاضر دیتای v2fly هم شامل می‌شه.   
از اونجایی که در `regexp:.*\\.ir$` از regex برای کل دامنه‌‌های ir هم استفاده شده نیازی به `ext:iran.dat:ir` نیست.

**Comment by hooman-nourbakhsh** [comment]
عذر خواهی میکنم میشه الان کد اصلاح شده رو در اینجا قرار بدید که چک کنم ببینم درست متوجه منظور شما شدم یا نه

**Comment by bootmortis** [comment]
> عذر خواهی میکنم میشه الان کد اصلاح شده رو در اینجا قرار بدید که چک کنم ببینم درست متوجه منظور شما شدم یا نه

```
  {
    "outboundTag": "blocked",
      "domain": [
        "regexp:.*\\.ir$",
        "ext:iran.dat:other",
        "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
      ],
    "type": "field"
  }
  ```

**Comment by hooman-nourbakhsh** [comment]
یک سوال سایت هایی مثل اسنپ و دیجی کالا و.. ک در خط آخر نوشتن مگر در دیتابیس شما نیست که بصورت جداگانه نوشته شده ؟!

برای دانلود هم این یک خط کافیه؟

wget https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat

**Comment by bootmortis** [comment]
احتمال زیاد در دیتابیس ما هست، از ریپوی iranxray/hope بپرسید.

بله کافیه

**Comment by ghost** [comment]
@matador7495 سلام اون کدی که هست فقط یه موردی داره باید به جای regexp:.*\\.ir$
ext:iran.dat:ir استفاده بشه
چون بعضی از سایتا مثل ubuntu. ir دامنه ایرانی دارن ولی سرورشون در خارج قرار داده و با این کد همه دامنه های ir بلاک میشن

**Comment by nimaafallah** [comment]
> > عذر خواهی میکنم میشه الان کد اصلاح شده رو در اینجا قرار بدید که چک کنم ببینم درست متوجه منظور شما شدم یا نه
> 
> ```
>   {
>     "outboundTag": "blocked",
>       "domain": [
>         "regexp:.*\\.ir$",
>         "ext:iran.dat:other",
>         "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
>       ],
>     "type": "field"
>   }
> ```

سلام ارادت، 
من کد رو اضافه میکنم و ریست میکنم پنل میره تو ارور، میگه که فایل iran.dat رو نمیتونم پیدا کنم و بخونم، فایل هم دانلود کردم و تو فولدر /usr/local/x-ui/bin/ هست.

**Comment by farid220** [comment]
> > عذر خواهی میکنم میشه الان کد اصلاح شده رو در اینجا قرار بدید که چک کنم ببینم درست متوجه منظور شما شدم یا نه
> 
> ```
>   {
>     "outboundTag": "blocked",
>       "domain": [
>         "regexp:.*\\.ir$",
>         "ext:iran.dat:other",
>         "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
>       ],
>     "type": "field"
>   }
> ```

سلام وقتتون بخیر عذر میخوام اگه ایشو کلوز شده ریپلای میزنم. بنده یکم سردرگم شدم چون دیدم شما بقیه کتگوری ها رو حذف کردید و فقط Other مونده. آیا این Other شامل همه کتگوریا میشه یعنی ؟ بعد اینکه تو ورژن 1.8.1 Xray Core این مشکل نیست و کامل کار میکنه ولی تو ورژن 1.8.3 دیگه نمیتونه بقیه کتگوری ها رو بخونه.

**Comment by bootmortis** [comment]
@farid220  
> سلام وقتتون بخیر عذر میخوام اگه ایشو کلوز شده ریپلای میزنم. بنده یکم سردرگم شدم چون دیدم شما بقیه کتگوری ها رو حذف کردید و فقط Other مونده. آیا این Other شامل همه کتگوریا میشه یعنی ؟ بعد اینکه تو ورژن 1.8.1 Xray Core این مشکل نیست و کامل کار میکنه ولی تو ورژن 1.8.3 دیگه نمیتونه بقیه کتگوری ها رو بخونه.


سلام در #13 تمامی دومین‌های v2fly به پروژه ما اضافه شده در نتیجه نیازی نیست از لیست v2fly برای دومین‌های ایران استفاده کنید.

**Comment by squall297** [comment]
iran/hope 404 شده 

xray config and files for /usr/local/x-ui/bin
[Uploading usr-local-x-ui-bin.zip…]()


{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
          "domain": [
"regexp:.*\\.ir$",
"ext:iran.dat:ir",
"ext:iran.dat:other",
"ext:iran.dat:ads",
"geosite:category-ir",
"geosite:category-gov-ir",
"geosite:category-news-ir",
"geosite:category-media-ir",
"geosite:category-social-media-ir",
"geosite:category-bank-ir",
"geosite:category-payment-ir",
"geosite:category-insurance-ir",
"geosite:category-education-ir",
"geosite:category-tech-ir",
"geosite:category-travel-ir",
"geosite:category-shopping-ir",
"geosite:category-scholar-ir",
"geosite:category-bourse-ir",
"geosite:category-forums-ir",
"geosite:category-ads",
"geosite:category-ads-all",
            "123tel", "a4f3clien", "abankefarda", "abank", "afaco.formool", "ako", "alachiigh", "alibaba", "alibaba.ir", "amirza", "anardoni", "anonycoders", "app.appaagah", "app.char", "app.fori", "app7030", "aparatspor", "aparattv", "app.gapkids", "app.hamrah", "app.hamyan", "app.igap", "app.leido", "app.mamana", "app.mydars", "app.padars", "app.pinno", "appchar", "artemis", "asantelegram", "asanbar", "asanapps.ariyagraph", "asparproject.app", "aspardproject", "ava", "baham", "bajet", "bajit", "bale", "balemessenger", "balonet", "bank", "bankino", "behkhaan", "behkhan", "bente", "bento", "bki", "blu", "bonakchi", "bonakchi.app", "bpm", "bsinew", "buyko", "carenboo", "cafe.telegraph", "calculationreal", "can.sel", "can.sell", "cartoonflix", "chabokpassenge", "cheebachee", "cheebachee.app", "cicika", "com.bize.irr", "combize", "cyklet", "cyklet.app", "daybank", "digikala", "digikala.firebol", "digikala.jet", "digilam", "digilam.app", "divar", "doozbin", "dorsabarza", "eghamat24", "efarda", "efar.da", "eitaa", "ela.mlaak", "eligasht", "enove.lingojoo", "esam", "esam.app", "esasy.live.memberbegirrubika", "etc", "express.snapp", "ezpay", "fadiaapp", "fam", "faraketab", "farakav.anten", "factorsabz", "fanoos", "fanoospfm", "fidibo", "filmnet", "filmischool", "flytoday", "football360", "footballi", "formool", "gardeshgari", "gardeshpay", "gahvare", "gapfilm.app", "gapkids", "gajino", "gajmarket", "gapfilm", "gapkid", "hamrah_mechanic", "hamrahbank", "hamrahcard", "hamrahelm", "hamrahnovin", "hoorsa", "homsa", "homsa.snapptrip", "hyperchi", "icup", "imino", "imino.pc.child", "iranapp", "iranmodernbusinesses.netbarg", "itoll", "itoll.mycarapp", "jadeh", "jadeh.driver", "jadeh.loadowner", "jajiga", "jajiga.app", "jama.ba", "jan.ebi", "karafs", "kalabis.hassan", "karnameh", "keshavarzi", "kilid", "kilid.portal", "kimiabiz", "learnit", "lenz", "lenz.tv", "likotv", "luna", "lunaapp", "mamana", "masterkala", "masterkala.shop", "melal", "melkana", "mehr.iran", "mehriran", "melkplus", "mibini", "mihmansho", "mobilemancard", "mobillet", "mydars", "mydigipay", "myiran", "myirancell", "myirancellcorp", "myrightel", "myshatel", "namava", "namava.mobile", "nasim", "navaco", "netbarg", "neshan", "neshan.traffic", "nichijou.app", "niazmandiha", "nobitex", "noonqeshm", "novinappsaz", "novinsimorgh", "partsoftware", "pasaj", "pasazh", "patogh", "patoghe_ketab", "payamakdoon", "paypod", "peccharge", "persiandesigners", "persiancalendar", "pikaap", "pinno", "pinno.app", "pindopin", "pindo", "pindo.fletcher", "pindopin", "pinket", "pinket.app", "pishkhan24", "quran", "qurankriampishgaman", "rayanmehr", "rezagem", "rizhav", "ronaksoftware", "roomack.amlaak", "rubika", "rubika.a", "sad24", "sad24.app", "sadadpsp", "safarmarket", "saramed", "sarmaye", "sarmayeh", "sekeh", "sepehr360", "set", "setareyek", "sesoot", "shahab_zarrin.quiz", "shahab_zarrin.tikup", "shahbaz", "shahbaz.zarrin", "shahbaz.zarrin.quiz", "shahbaz.zarrin.tikup", "shafa.doc", "shatel", "shatelland", "shatelland.namava.mobile", "shatelland.namava.tv", "shmapp", "shipnow", "sinamobilebank", "snapp", "snapp_box", "snapp.driver", "snapp.passenger", "snappfood", "snappfood.vms", "snappfoodvms", "soroush", "soroushmessenger", "stts.etc", "stts", "sunsetcar", "taaghche", "tabastaz.ir", "takhfifan", "takhfifhot", "takhfifhot.app", "taaghche", "tapsi", "taxi.tap30", "taxi.tap30.passenger", "tap30", "tap30.passenger", "tapsi", "tejarapp", "tejaratmobilebank", "tgbs", "tgbs.app", "tgbsgame", "tosansoha", "toranj", "torob", "toujib", "toujib.app", "wepod", "wepod.app", "yaramobile.pishvaz", "yma", "yootopin", "yotopin", "zabanshenas", "zabe amooz", "zamin.balonet", "zillow", "zillowmap", "zireh", "zoodfood", "zoodroom", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org", "apparat.com", "eitaa.com", "emofid.com", "yektanet.com", "zhaket.com", "rtl-theme.com", "tgju.org", "iranecar.com", "tasnimnews.com", "netafraz.com", "blogfa.com", "faradars.org", "parspack.com", "mehrnews.com", "iranserver.com", "agah.com", "mizbanfa.net", "mihanwebhost.com", "shahrekhabar.com", "abzarwp.com", "niazerooz.com", "music-fa.com", "yasdl.com", "sheypoor.com", "mihanwp.com", "maktabkhooneh.org", "doostihaa.com", "arzdigital.com", "heyvagroup.com", "sarzamindownload.com", "banimode.com", "istgah.com", "uploadboy.com", "upmusics.com", "snapp.taxi", "sahamyab.com", "hamyarwp.com", "blogsky.com", "iranhost.com", "motamem.org", "irantalent.com", "abasmanesh.com", "talahost.com", "rayamarketing.com", "meghdadit.com", "alopeyk.com", "sariasan.com", "nahayatnegar.com", "khabarvarzeshi.com", "civilica.com", "parscoders.com", "khanoumi.com", "19kala.com", "Farsnews.com", "Varzesh3.com", "Namnak.com", "Aparat.com", "telewebion.com", "torob.com", "ninisite.com", "safarmarket.com",  "ticket-charter.com", "blitcharter.com", "mrbilit.com", "flightio.com", "snapptrip.com", "utravs.com", "tikban.com", "melicharter.com", "digicharter.com", "kishzoom.net", "rahbal.com", "melicharter.org", "irtour.org", "aracharter.com", "charter1.net", "melicharter.net", "samtik.com", "charter361.com", "3click.com", "amincharter.com", "ticketarzan.com", "mancharter.net", "app.irancharter.mobi", "simorgh24.com", "ba-charter.com", "sourtik.com", "deltaban.com", "charter724.vip", "mellicharter.org", "charter123.net", "mahancharter.com", "cheapcharter.net", "eligasht.com", "kish44.com"
          ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by squall297** [comment]
`{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
          "domain": [
"regexp:.*\\.ir$",
"ext:iran.dat:ir",
"ext:iran.dat:other",
"ext:iran.dat:ads",
"geosite:category-ir",
"geosite:category-gov-ir",
"geosite:category-news-ir",
"geosite:category-media-ir",
"geosite:category-social-media-ir",
"geosite:category-bank-ir",
"geosite:category-payment-ir",
"geosite:category-insurance-ir",
"geosite:category-education-ir",
"geosite:category-tech-ir",
"geosite:category-travel-ir",
"geosite:category-shopping-ir",
"geosite:category-scholar-ir",
"geosite:category-bourse-ir",
"geosite:category-forums-ir",
"geosite:category-ads",
"geosite:category-ads-all",
            "123tel", "a4f3clien", "abankefarda", "abank", "afaco.formool", "ako", "alachiigh", "alibaba", "alibaba.ir", "amirza", "anardoni", "anonycoders", "app.appaagah", "app.char", "app.fori", "app7030", "aparatspor", "aparattv", "app.gapkids", "app.hamrah", "app.hamyan", "app.igap", "app.leido", "app.mamana", "app.mydars", "app.padars", "app.pinno", "appchar", "artemis", "asantelegram", "asanbar", "asanapps.ariyagraph", "asparproject.app", "aspardproject", "ava", "baham", "bajet", "bajit", "bale", "balemessenger", "balonet", "bank", "bankino", "behkhaan", "behkhan", "bente", "bento", "bki", "blu", "bonakchi", "bonakchi.app", "bpm", "bsinew", "buyko", "carenboo", "cafe.telegraph", "calculationreal", "can.sel", "can.sell", "cartoonflix", "chabokpassenge", "cheebachee", "cheebachee.app", "cicika", "com.bize.irr", "combize", "cyklet", "cyklet.app", "daybank", "digikala", "digikala.firebol", "digikala.jet", "digilam", "digilam.app", "divar", "doozbin", "dorsabarza", "eghamat24", "efarda", "efar.da", "eitaa", "ela.mlaak", "eligasht", "enove.lingojoo", "esam", "esam.app", "esasy.live.memberbegirrubika", "etc", "express.snapp", "ezpay", "fadiaapp", "fam", "faraketab", "farakav.anten", "factorsabz", "fanoos", "fanoospfm", "fidibo", "filmnet", "filmischool", "flytoday", "football360", "footballi", "formool", "gardeshgari", "gardeshpay", "gahvare", "gapfilm.app", "gapkids", "gajino", "gajmarket", "gapfilm", "gapkid", "hamrah_mechanic", "hamrahbank", "hamrahcard", "hamrahelm", "hamrahnovin", "hoorsa", "homsa", "homsa.snapptrip", "hyperchi", "icup", "imino", "imino.pc.child", "iranapp", "iranmodernbusinesses.netbarg", "itoll", "itoll.mycarapp", "jadeh", "jadeh.driver", "jadeh.loadowner", "jajiga", "jajiga.app", "jama.ba", "jan.ebi", "karafs", "kalabis.hassan", "karnameh", "keshavarzi", "kilid", "kilid.portal", "kimiabiz", "learnit", "lenz", "lenz.tv", "likotv", "luna", "lunaapp", "mamana", "masterkala", "masterkala.shop", "melal", "melkana", "mehr.iran", "mehriran", "melkplus", "mibini", "mihmansho", "mobilemancard", "mobillet", "mydars", "mydigipay", "myiran", "myirancell", "myirancellcorp", "myrightel", "myshatel", "namava", "namava.mobile", "nasim", "navaco", "netbarg", "neshan", "neshan.traffic", "nichijou.app", "niazmandiha", "nobitex", "noonqeshm", "novinappsaz", "novinsimorgh", "partsoftware", "pasaj", "pasazh", "patogh", "patoghe_ketab", "payamakdoon", "paypod", "peccharge", "persiandesigners", "persiancalendar", "pikaap", "pinno", "pinno.app", "pindopin", "pindo", "pindo.fletcher", "pindopin", "pinket", "pinket.app", "pishkhan24", "quran", "qurankriampishgaman", "rayanmehr", "rezagem", "rizhav", "ronaksoftware", "roomack.amlaak", "rubika", "rubika.a", "sad24", "sad24.app", "sadadpsp", "safarmarket", "saramed", "sarmaye", "sarmayeh", "sekeh", "sepehr360", "set", "setareyek", "sesoot", "shahab_zarrin.quiz", "shahab_zarrin.tikup", "shahbaz", "shahbaz.zarrin", "shahbaz.zarrin.quiz", "shahbaz.zarrin.tikup", "shafa.doc", "shatel", "shatelland", "shatelland.namava.mobile", "shatelland.namava.tv", "shmapp", "shipnow", "sinamobilebank", "snapp", "snapp_box", "snapp.driver", "snapp.passenger", "snappfood", "snappfood.vms", "snappfoodvms", "soroush", "soroushmessenger", "stts.etc", "stts", "sunsetcar", "taaghche", "tabastaz.ir", "takhfifan", "takhfifhot", "takhfifhot.app", "taaghche", "tapsi", "taxi.tap30", "taxi.tap30.passenger", "tap30", "tap30.passenger", "tapsi", "tejarapp", "tejaratmobilebank", "tgbs", "tgbs.app", "tgbsgame", "tosansoha", "toranj", "torob", "toujib", "toujib.app", "wepod", "wepod.app", "yaramobile.pishvaz", "yma", "yootopin", "yotopin", "zabanshenas", "zabe amooz", "zamin.balonet", "zillow", "zillowmap", "zireh", "zoodfood", "zoodroom", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org", "apparat.com", "eitaa.com", "emofid.com", "yektanet.com", "zhaket.com", "rtl-theme.com", "tgju.org", "iranecar.com", "tasnimnews.com", "netafraz.com", "blogfa.com", "faradars.org", "parspack.com", "mehrnews.com", "iranserver.com", "agah.com", "mizbanfa.net", "mihanwebhost.com", "shahrekhabar.com", "abzarwp.com", "niazerooz.com", "music-fa.com", "yasdl.com", "sheypoor.com", "mihanwp.com", "maktabkhooneh.org", "doostihaa.com", "arzdigital.com", "heyvagroup.com", "sarzamindownload.com", "banimode.com", "istgah.com", "uploadboy.com", "upmusics.com", "snapp.taxi", "sahamyab.com", "hamyarwp.com", "blogsky.com", "iranhost.com", "motamem.org", "irantalent.com", "abasmanesh.com", "talahost.com", "rayamarketing.com", "meghdadit.com", "alopeyk.com", "sariasan.com", "nahayatnegar.com", "khabarvarzeshi.com", "civilica.com", "parscoders.com", "khanoumi.com", "19kala.com", "Farsnews.com", "Varzesh3.com", "Namnak.com", "Aparat.com", "telewebion.com", "torob.com", "ninisite.com", "safarmarket.com",  "ticket-charter.com", "blitcharter.com", "mrbilit.com", "flightio.com", "snapptrip.com", "utravs.com", "tikban.com", "melicharter.com", "digicharter.com", "kishzoom.net", "rahbal.com", "melicharter.org", "irtour.org", "aracharter.com", "charter1.net", "melicharter.net", "samtik.com", "charter361.com", "3click.com", "amincharter.com", "ticketarzan.com", "mancharter.net", "app.irancharter.mobi", "simorgh24.com", "ba-charter.com", "sourtik.com", "deltaban.com", "charter724.vip", "mellicharter.org", "charter123.net", "mahancharter.com", "cheapcharter.net", "eligasht.com", "kish44.com"
          ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
`

**Comment by nimaafallah** [comment]
سلام من دیدم تاپیک قدیمی شد مجدد سوال میپرسم.
روی سرور ایران پنل کافکا دارم و یوزرهام روش هستن و تانل شده به خارج از طریق اوتباند، میخواستم این کار رو انجام بدم، میشه لطفا راهنمایی بفرمایید؟

**Comment by Phoenix-999** [comment]
@nimaafallah 

📡 مرحله به مرحله راه‌اندازی Routing و کنترل ترافیک در VPS


این دستورها برای به‌روزرسانی لیست دامنه‌های ایرانی (iran.dat) و لیست دامنه‌های جهانی (dlc.dat) استفاده می‌شوند. همچنین با استفاده از یک اسکریپت و cronjob، به‌روزرسانی خودکار فایل‌ها تنظیم می‌گردد.

## این قسمت باید روی سرور VPS شما انجام شود

### 🧱 مرحله ۱: ورود به محیط ریشه (Root)

```
sudo -i
```
این دستور شما را وارد محیط root می‌کند تا تمام دستورات بعدی با سطح دسترسی بالا اجرا شوند.

### 📂 مرحله ۲: ورود به مسیر فایل‌های x-ui

```
cd /usr/local/x-ui/bin
```
به مسیر فایل‌های اجرایی x-ui وارد شوید.

### 🌐 مرحله ۳: دانلود فایل‌های موردنیاز دامنه‌ها

```
wget https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
```
این iran.dat لیست دامنه‌های میزبانی‌شده در ایران
```
wget https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
```
این dlc.dat لیست دامنه‌های عمومی برای استفاده در تنظیمات V2Ray/Xray.

### 🔄 مرحله ۴: تنظیم به‌روزرسانی خودکار فایل iran.dat

۱. دانلود اسکریپت بروزرسانی:

```
curl -LO https://raw.githubusercontent.com/bootmortis/iran-hosted-domains/main/scripts/update_iran_dat.sh
```

۲. اعطای اجازه‌ی اجرایی به اسکریپت:
```
chmod +x update_iran_dat.sh
```

###  ⏰ مرحله ۵: تنظیم کرون‌جاب (Cron) برای بروزرسانی هفتگی

```
crontab -e
```
در انتهای فایل کرون‌جاب، این خط را اضافه کنید:

```
#---------Update iran.dat File automatically------------#
0 0 * * 2 /usr/local/x-ui/bin/update_iran_dat.sh /usr/local/x-ui/bin/iran.dat
```

⬅️ این دستور باعث می‌شود که هر هفته روز سه‌شنبه ساعت ۰۰:۰۰ بامداد فایل iran.dat به‌صورت خودکار به‌روز شود.

###  ✅ مرحله ۶: بررسی فایل‌ها

```
ls
```

با این دستور مطمئن شوید که فایل‌های iran.dat، dlc.dat و update_iran_dat.sh در مسیر /usr/local/x-ui/bin وجود دارند.
🧠 نکته‌های مهم:

اگر از Xray / V2Ray استفاده می‌کنید، این فایل‌ها را در پیکربندی routing یا rules قرار دهید.
ترکیب iran.dat و dlc.dat کمک می‌کند تا دامنه‌های ایرانی به اینترنت داخلی و دامنه‌های بین‌المللی به سرورهای خارجی هدایت شوند.
مطمئن شوید crond یا cron فعال باشد.

_____________________________________________________

## این تنظیمات باید روی فایل پیکربندی X-UI انجام شود 

در ادامه، مراحل دقیق برای جایگزینی پیکربندی X-UI با متن موردنظر شما آورده شده است. این پیکربندی باعث می‌شود ترافیک سایت‌های ایرانی و محتوای نامناسب (مثل پورن) به‌درستی مسدود شده یا از مسیر داخلی هدایت شود و بقیه ترافیک جهانی از طریق VPS خارج شود.

الان وارد پنل X-UI شوید، به بخش تنظیمات بروید و متن زیر را به‌صورت کامل کپی کرده و جایگزین مقدار قبلی در تنظیمات X-UI کنید.
این بخش باید داخل قسمت "routing": { "rules": [ ... ] } از تنظیمات Xray یا X-UI قرار بگیرد.
دقیق‌تر بگوییم:
    داخل بخش rules که با براکت مربع [ ] شروع می‌شود قرار دهید.
    اگر قوانین دیگری هم دارید، با استفاده از ویرگول (,) بین هر قانون آن را جدا کنید.
    بهتر است آن را در انتهای لیست rules اضافه کنید یا کنار قوانین مسدودسازی دیگر قرار دهید.

``` JSON
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
"regexp:.*\\.ir$",
"ext:iran.dat:all",
"ext:iran.dat:ir",
"ext:iran.dat:other",
"ext:iran.dat:ads",
"geosite:category-ir",
"geosite:category-gov-ir",
"geosite:category-news-ir",
"geosite:category-media-ir",
"geosite:category-social-media-ir",
"geosite:category-bank-ir",
"geosite:category-payment-ir",
"geosite:category-insurance-ir",
"geosite:category-education-ir",
"geosite:category-tech-ir",
"geosite:category-travel-ir",
"geosite:category-shopping-ir",
"geosite:category-scholar-ir",
"geosite:category-bourse-ir",
"geosite:category-forums-ir",
        ]
      }
``` 

✅ نتیجه:
هر دامنه‌ای که با این لیست مطابقت داشته باشد، توسط Xray به مسیر blocked هدایت می‌شود و در عمل دسترسی به آن قطع می‌شود.

_____________________________________________________

در ضمن دوست عزیز پنل کافکا به علت شرایط امنیتی و مشکلات دیگری که داشت مدت‌هاست توسط دولوپر آپدیت نشده و هسته اکس ری به روز نیست. 
پیشنهاد می‌کنم از پنل‌های مجهز و آپدیت شده‌ای که این روزها بسیار فراوان هستند و حتی به زبان فارسی هم در دست کاربران هست استفاده کنید، که مجهز به تمام امکانات پیشرفته و آخرین ورژن هسته x-ui هست

چند نمونه رو اینجا برای شما می‌گذارم

> [MHSanaei/3x-ui](https://github.com/MHSanaei/3x-ui/blob/main/README.fa_IR.md)
> [Remnawave](https://github.com/remnawave/panel)
> [Marzban](https://github.com/Gozargah/Marzban)
> [Xray-UI](https://github.com/qist/xray-ui)
> [Hiddify](https://github.com/hiddify/Hiddify-Manager)
