### ISSUE TITLE
استفاده در Nekoray

### ISSUE THREAD

**Issue by MahdiAkrami01** [bootmortis/iran-hosted-domains#6]
سلام وقت بخیر 
نمیشه از فایل iran.dat توی Nekoray استفاده کرد ؟ من هر کاری میکنم لود نمیشه . فایل dat هم داخل پوشه assets که تنظیم کردم قرار دادم .

![image](https://user-images.githubusercontent.com/54323929/216800557-41c8e456-dbf7-44ef-994f-73950c46e241.png)

![image](https://user-images.githubusercontent.com/54323929/216800562-b433f2c1-5020-4bf1-be69-4863ca437529.png)

**Comment by papampi** [comment]
Nekoray error is in "iran.dat:ads" 
All others "iran.dat:ir" and "iran.dat:other" has no problems

When add "ext:iran.dat:ads" gives this error: 
![image](https://user-images.githubusercontent.com/1108483/218466070-c950a12c-fb74-4a06-a5b9-8ff0829dba4f.png)

**Comment by bootmortis** [comment]
> Nekoray error is in "iran.dat:ads" All others "iran.dat:ir" and "iran.dat:other" has no problems
> 
> When add "ext:iran.dat:ads" gives this error: ![image](https://user-images.githubusercontent.com/1108483/218466070-c950a12c-fb74-4a06-a5b9-8ff0829dba4f.png)

ممنون بابت اینکه متن اررور رو گفتی
مشکل از دامنه‌ی `bitbod_trading_club` بود.
اگر امکانش هست رلیز اخر هم تست کنید نتیجه رو بگید

**Comment by papampi** [comment]
> > Nekoray error is in "iran.dat:ads" All others "iran.dat:ir" and "iran.dat:other" has no problems
> > When add "ext:iran.dat:ads" gives this error: ![image](https://user-images.githubusercontent.com/1108483/218466070-c950a12c-fb74-4a06-a5b9-8ff0829dba4f.png)
> 
> ممنون بابت اینکه متن اررور رو گفتی مشکل از دامنه‌ی `bitbod_trading_club` بود. اگر امکانش هست رلیز اخر هم تست کنید نتیجه رو بگید

Fixed, thanks.

**Comment by MasterKia** [comment]
>  مشکل از دامنه‌ی bitbod_trading_club بود.

این مشکل ۱۰ روز پیش برطرف شده بوده:
https://github.com/MasterKia/PersianBlocker/commit/a3234e6f5ef6079475fccaa4de6385412f7b3fef

**Comment by bootmortis** [comment]
> > مشکل از دامنه‌ی bitbod_trading_club بود.
> 
> این مشکل ۱۰ روز پیش برطرف شده بوده: [MasterKia/PersianBlocker@a3234e6](https://github.com/MasterKia/PersianBlocker/commit/a3234e6f5ef6079475fccaa4de6385412f7b3fef)

همچنان در [این لاین](https://github.com/MasterKia/PersianBlocker/blob/6e97224e83c54f57fca730bbcfbbb68265f1a3b5/PersianBlockerHosts.txt#L525) وجود داره


دامنه نباید توش `_` وجود داشته باشه
برای اطلاعات بیشتر به این دو تا لینک مراجعه کنید:  

https://github.com/v2fly/v2ray-core/discussions/1275
https://www.rfc-editor.org/rfc/rfc952

**Comment by MasterKia** [comment]
`bitbod_trading_club.t.me` redirects to
`t.me/bitbod_trading_club` so it's a valid domain name.
Anyhow, I will remove it as it's unclear how someone will come across `bitbod_trading_club.t.me` in any way.

**Comment by bootmortis** [comment]
@MasterKia  ok thanks

I know about the redirection, but Nekoray and other kernels validate domains statically based on name, not dynamically with redirection, and according to [rfc952](https://www.rfc-editor.org/rfc/rfc952):
> A "name" (Net, Host, Gateway, or Domain name) is a text string up
> to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
> sign (-), and period (.).
> \- RFC 952

so `bitbod_trading_club.t.me` is an invalid domain name.
