### ISSUE TITLE
add new domain myirancell

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#61]
### Domain Name

tapture.ir

### Reason for Add/Remove

گویا در نسخه جدید مای ایرانسل آدرس جدیدی اضافه شده که برای ورود نیاز هست که با ایپی ایران باز بشه لطفا یک بررسی کنید مرسی

**Comment by bootmortis** [comment]
مطمئن هستید که این آدرس مال ایرانسل هست؟

**Comment by hooman-nourbakhsh** [comment]
خیر مطمئن نیستم چیزی که نرم افزار نشان داد گزارش کردم.

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/1cfb0558-b12b-4281-ab83-5b06bbf1ffca)

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/06f602f7-e02a-4139-a802-408b839029fd)

**Comment by MasterKia** [comment]
احتمالاً برای جمع‌آوری اطلاعات درباره کاربر یا دریافت لیست تبلیغات برای نمایش توی برنامه هست.

**Comment by hooman-nourbakhsh** [comment]
نمیدونم حقیقت اما باعث شده تا vpn قطع نکنی وارد برنامه نمیشه یک بررسی کنید ممنون

**Comment by Tirbod** [comment]
برای `tapture.ir` نیست ، برای `cloudflare.com` که مای ایرانسل براش درخواست میفرسته، میتونید این قانون را اضافه کنید که ببینید:
```INI
 DOMAIN-SUFFIX,cloudflare.com,DIRECT
```
برای حل مشکل یا میتونید `cloudflare.com` رو دایرکت کنید مثل بالا که جالب نیست یا کلا ترافیک مای ایرانسل را خارج کنید از طریق `tools>bypass config(black list mode)` یا این قانون را اضافه کنید برای دایرکت کردن:
```INI
PROCESS-NAME,com.myirancell,DIRECT
```

**Comment by hooman-nourbakhsh** [comment]
PROCESS-NAME,com.myirancell,DIRECT

مورد اخر فک کنم کم دردسر تر باشه در قوانین clash لحاظ کنم اوکی هست؟

**Comment by Tirbod** [comment]
اره تو کلش هم اینطوری اوکیه:
```yaml
  - PROCESS-NAME,com.myirancell,DIRECT
```

**Comment by hooman-nourbakhsh** [comment]
ممنونم مشکل حل شد. این رو در فایل های rule خودتان که منتشر می کنید نمیشه قرار داد درسته؟

**Comment by bootmortis** [comment]
> ممنونم مشکل حل شد. این رو در فایل های rule خودتان که منتشر می کنید نمیشه قرار داد درسته؟

ایده‌ی جالبیه که لیست اپ‌ها هم به ریپو اضافه کنیم، ولی بنظرم این ریپو خیلی شلوغ می‌شه، احتمالا ریپوی جدید زدن بهتر باشه. البته فکر کنم چند تا ریپو دیدم که اینکارو کردن الان به خاطر ندارم

**Comment by hooman-nourbakhsh** [comment]
به نظر من احتیاجی نیست به وسیله دستورات فعلی اکثریت نرم افزار ها پوشش داده میشه بعضی از نرم افزار ها قبلا مثل بلبل جان تشخیص اتصال وی پی ان میداد ک اونم حل شده جدیدا هم ایرانسل بود که با این ترفند اوکی شد. مگر اینکه تعداد نرم افزار های این دسته زیاد بشه.

سپاس از ریپو خوب تیم شما
