### ISSUE TITLE
Add `parsvds.com`

### ISSUE THREAD

**Issue by sinascorpion** [bootmortis/iran-hosted-domains#65]
### Domain Name

Please provide the name of the domain you would like to add or remove.
Also, specify whether you want to add/remove this domain from the **Bypass List** or the **Block List**.

### Reason for Add/Remove

Why do you want to add or remove this domain from the list?

### Supporting Evidence

If possible, please provide any relevant supporting evidence for your request (e.g. screenshot).

### Additional Information

Any additional information you would like to provide.

**Comment by bootmortis** [comment]
we already have this domain:
![WindowsTerminal_IGOhYYn7mM](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/313f13de-fdfa-4c66-9191-f38b5dedf2b0)
