### ISSUE TITLE
Add `kakohost.com`

### ISSUE THREAD

**Issue by sinascorpion** [bootmortis/iran-hosted-domains#69]
### Domain Name

Please provide the name of the domain you would like to add or remove.
Also, specify whether you want to add/remove this domain from the **Bypass List** or the **Block List**.

### Reason for Add/Remove

Why do you want to add or remove this domain from the list?

### Supporting Evidence

If possible, please provide any relevant supporting evidence for your request (e.g. screenshot).

### Additional Information

Any additional information you would like to provide.

**Comment by bootmortis** [comment]
we already have this:
![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/a27956ac-9c0d-4960-aceb-834615ece240)


please check domain.txt before opining new issues.
