### ISSUE TITLE
اضافه کردن سایت جدید

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#7]
sb24.ir
pmlm.ir
pay98.app
sdb247.com
iranicard.ir
giftcardgo.ir
arvancloud.ir
zoomit.ir
nextpay.org
qr-code.ir
javab24.com
opizo.com
zoomg.ir
hard-repair.com
masterkala.com
mobone.ir
apktops.ir
androidkade.com
numberland.ir
datisnetwork.com
hivanetwork.com
webhostingtalk.ir
sarvdata.com
parsdev.com
takhfifan.com
intrack.ir
mehrafarinorg.ir
mehrafarinorg.com

لطفا این لیست را اضافه کنید

**Comment by MasterKia** [comment]
`intrack.ir`

یک سایت ردیاب (tracking) هست.

**Comment by hooman-nourbakhsh** [comment]
اوکی سایر سایت ها را اضافه کنید

**Comment by patterniha** [comment]
بعلاوه:
aparatsport.com

**Comment by hooman-nourbakhsh** [comment]
سلام وقت بخیر این دامنه ها هنوز اضافه نشدن باتشکر
pmlm.ir
pay98.app
giftcardgo.ir
qr-code.ir
javab24.com
opizo.com
hard-repair.com
masterkala.com
mobone.ir
androidkade.com
datisnetwork.com
hivanetwork.com
webhostingtalk.ir
sarvdata.com
parsdev.com
mehrafarinorg.ir
mehrafarinorg.com
