### ISSUE TITLE
Add/Remove `digimovie.vip`

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#70]
اگر امکان پذیر هست این سایت رو بررسی کنید.

من با استفاده از این اموزش https://github.com/bootmortis/iran-hosted-domains/issues/58#issuecomment-1546984587

در سرور سایت های ایرانی رو مسدود کردم و برای باز کردن سایت های داخلی با ایپی ایران از clash استفاده میکنم.

ولی متاسفانه clash  این ادرس digimovie.vip در rule ها پیدا نمی کنه جهت direct کردن و باعث مسدودی و لود نشدن سایت میشه.

**Comment by bootmortis** [comment]
ممنون
ولی فکر نکنم اضافه کردن سایت‌های دانلود فیلم و سریال به لیست ایده‌ی خوبی باشه...
مگه دیجی‌مویی ایران اکسس هست؟

**Comment by hooman-nourbakhsh** [comment]
حقیقت منم اطلاع نداشتم به همین خاطر مطرح کردم تا بررسی بشه به نظر بنده هم قرار نگیره بهتر

اما مشکلی که اینجا هست بنده از این سورس استفاده کردم
https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat

و در سمت سرور سایت های داخلی رو مسدود کردم که گویا سایت دیجی مووی هم شامل شده

و در برنامه کلش هم از rule های شما استفاده کردم تا هر سایتی داخلی بود با ایپی حقیقی باز بشه اما گویا دیجی مووی در این رول ها وجود نداره و باعث شد کلش اونو تشخیص نده 

پس نتیجه میگیریم اگر قرار سایتی نباشه هم از dat حذف کنید هم از رول ها و اگر قرار باشه در جفتش قرار بدید تا اینجوری تناقض پیش نیاد

**Comment by bootmortis** [comment]
هم dat و هم rule از یک منبع استفاده می‌کنن
محتوای کانفیگ‌های مختلف تفاوتی نداره
در مورد دیجی‌مویی چیزی که احتمال می‌دم اینه که CDN هاش ایران‌اکسس باشن نه خود سایت.

**Comment by hooman-nourbakhsh** [comment]
بله دقیقا بنده هم چون از این موضوع مطلع بودم تعجب کردم چرا این اتفاق افتاده.  حالا باز اگر میشه ی بررسی کنید که بلکم حداقل با همان ایپی ایران باز بشه یعنی اگر داخل فایل dat هست برداشته بشه که اونجا مسدود نشه توسط سرور یا هر راه حل دیگه ای که خودتان بهتر می دونید.

**Comment by bootmortis** [comment]
فایل .dat در سمت کلاینت هم استفاده می‌شه ما نمی‌تونیم صرفا یک خروجی رو تغییر بدیم. سمت سرور خودتون تغییرات رو اعمال کنید.

**Comment by hooman-nourbakhsh** [comment]
بله متوجه هستم چه میفرمایید و سمت کاربری خودم اوکی کردم منتهی جای تعجب داشت و خواستم شما بررسی کنید شاید یک جایی اشتباه شده باشه بهرحال پیش میاد. وقتی در سمت سرور مسدود شده به وسیله فایل dat پس احتمالا وجود داره این ادرس اما چرا در rule های کلش نیست نمی دونم !
