### ISSUE TITLE
یک مشکل در برنامه clash meta

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#76]
![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/3cbc73f9-a3a1-4bd5-8983-df96e1bb1416)

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/6b8f3c21-2abf-4c55-a389-a80836a42cfb)

من در برنامه بلوبانک و مثلا مای شاتل خواستم ورود کنم اجازه نمیده به دلیل اینکه ایپی دایرکت نمیشه براشون و با ایپی سرور ورود میکنه

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/07c23262-9602-4e54-ad56-6f3ea2c044a3)

لاگ نگاه کردم دیدم برای این آدرس درخواست میره sdb247.com به فایل رول clash_rules_other.txt اضافه کردم برای yaml و سورف برد هم اضافه کردم ، در سورف برد و کلش اندروید کار میکنه اما در کلش متا جواب نمیده !!!

**Comment by quantom9696** [comment]
کلش متا (نسخه اندرویدی) خود را حتما به اپدیت امروز گیتهاب اش ارتقا داده و مجددا امتحان کنید

**Comment by quantom9696** [comment]
در ضمن دستور
DOMAIN-KEYWORD,sdb247,DIRECT
را نیز امتحان کنید


و اینکه، شاید نیاز به + نباشد

**Comment by quantom9696** [comment]
در ضمن دستور
DOMAIN-KEYWORD,sdb247,DIRECT
را نیز امتحان کنید

**Comment by hooman-nourbakhsh** [comment]
> کلش متا (نسخه اندرویدی) خود را حتما به اپدیت امروز گیتهاب اش ارتقا داده و مجددا امتحان کنید

اتفاقا 4 نسخه آخر رو تست کردم بدون نتیجه بود

**Comment by hooman-nourbakhsh** [comment]
https://github.com/bootmortis/iran-hosted-domains/releases/download/202305211852/clash_rules_other.txt

مشکل میخواهم اگر امکان پذیر باشه از طریق قوانین این فایل txt حل کنم و داخل کانفیگ rule های کلش چیزی اضافه نکنم . منظورم عدم استفاده از DOMAIN-KEYWORD است الان مورد + که فرمودید تست میکنم جالب تا چند وقت پیش اوکی بود نمیدونم یهو چی شده

**Comment by quantom9696** [comment]
پس به قول شما باید ریشه ای حلش کرد

**Comment by hooman-nourbakhsh** [comment]
آقا دست به گیرنده های خود نزنید سوتی از خودم بود امان از کپی پیست !

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/03560a6a-f608-4020-a11f-37d8a1ea9947)

format text 

را فراموش کرده بودم.

عذرخواهی میکنم از دوستان.
