### ISSUE TITLE
مرج کردن با لیست v2fly

### ISSUE THREAD

**Issue by quantom9696** [bootmortis/iran-hosted-domains#77]
درود

از انجایی که روتر های بسیاری به PassWall و هسته xray و هسته v2ray مجهزند، امکان افزودن فایل dat شما توسط افراد مبتدی وجود ندارد لذا با دولوپر های v2fly و همینطور loyalsoldier صحبت کنید تا دامین های ایرانی رو در لیستشون قرار بدند و پیگیر این مساله در هر دو ریپو نامبرده باشید

سپاس

**Comment by bootmortis** [comment]
سلام
بنا به دلایل بسیاری که بارها در این ریپو و در ریپوی v2fly/domain-list-community ذکر کردیم، ما با مرج کردن لیست iran-hosted-domains که دائما و به طور خودکار در حال آپدیت هست با لیست‌هایی که به صورت دستی آپدیت می‌شن (لیست‌هایی که ذکر کردید) مخالف هستیم.
