### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by quantom9696** [bootmortis/iran-hosted-domains#78]
7leecher.net
parsget.com

را به لیست بای پس بیفزایید لطفا

**Comment by bootmortis** [comment]
هر دو دامنه در لیست وجود دارن
لطفا قبل از درخواست لیست رو از فایل domains.txt چک کنید

![image](https://github.com/bootmortis/iran-hosted-domains/assets/120013889/60941e73-5193-4cf6-9843-f6e5615ffed9)
