### ISSUE TITLE
نرم افزار بلبل جان

### ISSUE THREAD

**Issue by hooman-nourbakhsh** [bootmortis/iran-hosted-domains#79]
یک مسئله برخورد کردم اگر حل بشه کمی شرایط شاید بهتر بشه خخخ

به نظرتان چرا این نرم افزار با rule های کاملا یکسان بین سورف برد و کلش 
به راحتی در سرف برد اجرا میشه اما در کلش نه عکس لاگ ها رو ارسال میکنم.
این لاگ سرف برد
![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/e7fde326-eabf-4139-9b9d-fa314627b6a7)

این لاگ کلش متا

![image](https://github.com/bootmortis/iran-hosted-domains/assets/30972110/9038f094-cfcf-467c-b63c-e79911fed7b6)

**Comment by Graveyard9988** [comment]
ممکنه دیتابیس geo کلاینت ها باهم متفاوت باشه
کانفیگ متا آزاد*نت رو ببین، جئو ها کاستومایز شده است در اول لینک سابشون و لینک های متفاوتی دارن
