### ISSUE TITLE
مشکل کانفیگ شدوراکت

### ISSUE THREAD

**Issue by hadiomid** [bootmortis/iran-hosted-domains#8]
سلام
فایل کانفیگ شدوراکت رو وقتی ست کردم، سایت های ایرانی رو باز میکنه ولی سایت های خارجی رو باز نمیکنه

**Comment by frezahc** [comment]
و توییتر رو هم باز نمیکنه

**Comment by freeforlife-star** [comment]
واسه من بیشتر جاهایی که تست کردم ، کار کرد ولی واتساپ از کار افتاده

**Comment by hadiomid** [comment]
نسخه جدید رو تست کردم مشکل قبلی حل شده اما سرویس های شرکت متا (اینستاگرام، واتس اپ و فیسبوک) کار نمیکنه با این کانفیگ

**Comment by bootmortis** [comment]
لطفا نسخه جدید رو تست کنید ببینید مشکل بر طرف شده یا نه

**Comment by hadiomid** [comment]
> لطفا نسخه جدید رو تست کنید ببینید مشکل بر طرف شده یا نه

فایل جدید رو تست کردم مشکل داره همچنان

**Comment by frezahc** [comment]
در نسخه جدید، توییتر باز میشه ولی هیچ مدیایی لود نمیشه
واتس‌اپ هم کلا وصل نمیشه

**Comment by mojit00l** [comment]
یه باگ های ریزی داره که یکیش دوستان اشاره کردن توییتر هست ولی در کل باید هی سوییچ کنیم بین دیفالت و این کانفیگ تا درست کار کنه به نظرم یه ویرایش و باگ یابی لازم داره

**Comment by bootmortis** [comment]
اگر امکانش هست کانفیگ جدید رو از [این رلیز](https://github.com/bootmortis/iran-hosted-domains/releases/tag/202304081539) بگیرید و تست کنید که کار می‌کنه یا نه

**Comment by hadiomid** [comment]
> اگر امکانش هست کانفیگ جدید رو از [این رلیز](https://github.com/bootmortis/iran-hosted-domains/releases/tag/202304081539) بگیرید و تست کنید که کار می‌کنه یا نه

سلام، این ورژن رو من تست کردم ظاهرا مشکلی نداره
