### ISSUE TITLE
اضافه کردن لیست اپلیکیشن‌ها

### ISSUE THREAD

**Issue by quantom9696** [bootmortis/iran-hosted-domains#80]
درود
ابتدا لینک زیر که شامل package name اپ های اندرویدی ایرانی هست را مشاهده بفرمایید:
https://github.com/hiddify/androidpackagenamelist/blob/master/direct_ir
سپس لیست فوق را بدین صورت دربیاورید:
payload:
PROCESS-NAME,app.rbmain.a

و لیست را برای بای پس در لینک های کلش اعمال کنید

و مرتبا از مخزن مذکور لیست را به روزرسانی کنید
با سپاس

**Comment by quantom9696** [comment]
payload:
 -PROCESS-NAME,app.rbmain.a
 -PROCESS-NAME,com.youmusic.magictiles.ir
 -PROCESS-NAME,com.amanotes.beathopper
 -PROCESS-NAME,com.youmusic.magictiles
 
مثال ها بصورت فوق می باشند

**Comment by quantom9696** [comment]
https://github.com/Infatuation-Fei/rule/blob/main/Clash/Rule/OtherProxy.yaml

نمونه ای برای مثال با فرض بای پس!

**Comment by Graveyard9988** [comment]
این process name هم برای اپ های اندروید و مک و ios و ویندوز به کار میره! خیلی جالبه (در داکیومنت های کلش بهش اشاره شده)

**Comment by bootmortis** [comment]
سلام، اسم مخزن iran hosted domain هست.
مدیریت لیست پکیج‌ها از اهداف این مخزن نیست. اگر در آینده نیاز باشه مخزن مجزا می‌زنیم اما فعلا تصمیمی نداریم.
