### ISSUE TITLE
اضافه کردن لیست ASN

### ISSUE THREAD

**Issue by quantom9696** [bootmortis/iran-hosted-domains#81]
درود
لطفا رول جدید برای شدوراکت و surge با نام ذیل ایجاد کنید:
RULE-SET,https://raw.githubusercontent.com/****/asniran.list,DIRECT

حال دیتابیس زیر را مشاهده کنید:
https://whois.ipinsight.io/countries/IR

سپس محتویات فایل asniran.list را به صورت ذیل در بیاورید:

 IP-ASN,42337 
 IP-ASN,49666 
 IP-ASN,43754 
 IP-ASN,58224 

و مرتبا از مخزن نامبرده لیست را مرتبا به روزرسانی کنید

مثال:
https://github.com/deezertidal/shadowrocket-rules/blob/main/rule/ASN-CN.list

**Comment by quantom9696** [comment]
.

**Comment by bootmortis** [comment]
لیست ASN هم به دلایلی که #80 بسته شد به مخزن اضافه نمی‌شه.
