### ISSUE TITLE
AsIs or IPIfNonMatch?

### ISSUE THREAD

**Issue by AlirezaSafari7** [bootmortis/iran-hosted-domains#83]
In Qv2ray, the default Domain Resolution Strategy is 'AsIs'. However, the README recommends setting it to 'IPIfNonMatch' for better routing. The screenshot in the README contradicts this recommendation by showing the Domain Strategy set as 'AsIs'. Can you confirm which setting is correct for Qv2ray - 'AsIs' or 'IPIfNonMatch'?

**Comment by bootmortis** [comment]
Thank you for bringing this to our attention. It's worth noting that both `AsIs` and `IPIfNonMatch` are suitable options, with `AsIs` having better performance and `IPIfNonMatch` offering better routing capabilities. Ultimately, the decision on which one to use should be based on your specific needs. I plan to clarify this in the README in the future, so I'll leave this issue open for now.

You can find more information [here](https://www.v2ray.com/en/configuration/routing.html#routingobject).
