### ISSUE TITLE
Latest Nekoray Documentation

### ISSUE THREAD

**Issue by manwithoutpant** [bootmortis/iran-hosted-domains#84]
### Description

there is different between your document for nekoray and the 3.5 version . i did follow your step but it didn't help me
### Steps to Reproduce

Please provide the steps you took to encounter the bug.

### Expected Outcome

What did you expect to happen?

bypass/direct the iranian domains
What actually happened?

### Additional Information

- Version of the repository you are using
- win 11 latest build nekoray 3.5 beta
- Screenshots or other relevant information to help us understand the bug
- 
![image](https://github.com/bootmortis/iran-hosted-domains/assets/39988728/055fb16f-9a5c-47a7-9537-126f363b25ad)

**Comment by bootmortis** [comment]
Could you please provide more details regarding the issue you're facing? Perhaps a screenshot of the error would be helpful.

**Comment by manwithoutpant** [comment]
i mean what step i should follow in the new nekoray interface?
only thing i can provide is knowong that Iranian domain for exmple www.speedcheck.ir can see my vps ip which means the directing is not working.
the interface you guys are you using is not helpful for me because latest nekoray has changed it.

**Comment by Chocolate4U** [comment]
راهنمای فعلی برای نسخه های جدید مناسب نیست. شما باید از `iran-geosite.db` (در صورت استفاده از هسته sing-box ) و یا `iran.dat` (در صورت استفاده از هسته v2ray ) استفاده کنید.
# در صورت استفاده از هسته sing-box
فایل `iran-geosite.db` رو دانلود کنید و به geosite.db تغییر نام بدید و در پوشه Nekoray قرار بدید. پیام جایگزینی رو تایید کنید و سپس قوانین زیر رو در برنامه ست کنید.
قسمت Direct, IP
```
geoip:ir
geoip:private
```
قسمت Direct, Domain 
```
regexp:.+\.ir$
geosite:other
```
 # در صورت استفاده از هسته v2ray
فایل `iran.dat` رو دانلود کنید و در پوشه Nekoray قرار بدید. سپس قوانین زیر رو در برنامه ست کنید.
قسمت Direct, IP
```
geoip:ir
geoip:private
```
قسمت Direct, Domain 
```
regexp:.+\.ir$
ext:iran.dat:other
```

**Comment by bootmortis** [comment]
@chocolate4u ممنون ازت

اگر امکانش هست بعد از اینکه تکلیف #86 مشخص شد این راهنما رو در readme اپدیت کنین و PR بدین

این ایشو فعلا تا اپدیت داکیومنت باز می‌مونه

**Comment by Chocolate4U** [comment]
آره حتما، همین قصد رو هم داشتم فقط به خاطر #86 دست نگه داشتم که بر اساس همون راهنما رو آپدیت کنیم.
