### ISSUE TITLE
Bypass and proxy some domains

### ISSUE THREAD

**Issue by ghost** [bootmortis/iran-hosted-domains#85]
## Add/Remove Domain

Bypass:
- `mimfarsi.com`
- `wiiz.ir`
- `shad.ir`
- `targoman.ir`

Proxy:
- `ubuntu.ir`
- `pcworms.ir`
- `archusers.ir`
- `debian.ir`

**Comment by Graveyard9988** [comment]
@bootmortis لطفا 
Wiiz.ir
را اعمال بفرمایید

**Comment by ghost** [comment]
دامنه هایی که باید پروکسی بشن بروزرسانی شد.

**Comment by Graveyard9988** [comment]
منظور من بای پس wiiz.ir بود که انجام نشده هنوز

**Comment by ghost** [comment]
پروکسی کردن اونها هم مثل بایپس کردن ویز اهمیت داره

**Comment by Graveyard9988** [comment]
درسته مهم اینه که ادمین ببینه و به تعویق نیندازه

**Comment by ghost** [comment]
یه نکته ای در مورد targoman این آدرسی که برای بایپس داده شده com اون فقط توی لیسته درحالی که targoman.com به targoman.ir ارجاع میشه.

**Comment by bootmortis** [comment]
دومین های بایپس اضافه شد.

دلیلتون برای دومین‌های پروکسی چیه؟

**Comment by ghost** [comment]
ممنونم.
دامنه های پروکسی اول اینکه سرورشون در خارج قرار داره وقتی از کانفیگ استفاده میکنم این دامنه ها بلاک میشن(لااقل توی موبایل) چون توی لیست نیست.

**Comment by bootmortis** [comment]
@aetoray 

<div dir='rtl'>

لیست پروکسی فقط برای qv2ray کاربرد داره الان، بخوایم به فایل .dat اضافه کنیم از نظر UX برای کاربر پیچیدگی داره. یک راه اینه که جای regex کل دومین‌های ir از لیست .dat استفاده کنین.

</div>

**Comment by MR-Pooya** [comment]
Bypass:
0-1.ir
127.0.0.1
192.168.0.1
filmkio.pro
snapp.express
nic.ir
upera.tv
agent.ag-translate.com
ssaa.tax.gov.ir
achareh.co
heydari.co
exnovin.io
sarmayegozarebartar.com
api.exnovin1.com
snapp.express
tetherland.com
panel.nikpardakht.com
dls.top-movies2filmha.tk
exnovin.io

**Comment by ghost** [comment]
من یه رایانامه ارسال کرده بودم ولی مثل اینکه گیت هاب اعمالش نکرده به هر صورت من این ایشو رو می ببندم ممنون از زحمات شما

**Comment by ghost** [comment]
> Bypass: 0-1.ir 127.0.0.1 192.168.0.1 filmkio.pro snapp.express nic.ir upera.tv agent.ag-translate.com ssaa.tax.gov.ir achareh.co heydari.co exnovin.io sarmayegozarebartar.com api.exnovin1.com snapp.express tetherland.com panel.nikpardakht.com dls.top-movies2filmha.tk exnovin.io

دوست عزیز اکثر این دامنه ها توی لیستن در ضمن ایناها رو در یه ایشوی دیگه مطرح کنید
