### ISSUE TITLE
پیشنهاد در مورد Sing-box, Nekobox و Nekoray

### ISSUE THREAD

**Issue by Chocolate4U** [bootmortis/iran-hosted-domains#86]
از اونجایی که sing-box و برنامه هایی که از هسته sing-box استفاده میکنن مثل دو مورد بالا، فقط از یک فایل geosite پشتیبانی میکنن، امکان استفاده از iran-geosite.db در کنار geosite پیشفرض وجود نداره، اکثرا به geosite پیش فرض هم برای بخش تبلیغاتش (`category-ads-all`) و یا شاید بخش های دیگه اش هم نیاز دارن. اینجا چندتا راه حل داریم:
1. مرج کردن این لیست با [domain-list-community](https://github.com/v2fly/domain-list-community) و استفاده از geosite پیشفرض، که با توجه به دلایلی که قبلا ذکر شده( مثل [#1375](https://github.com/v2fly/domain-list-community/pull/1375) یا [#1641](https://github.com/v2fly/domain-list-community/pull/1641) ) این مورد منتفی هست.
2. پشتیبانی sing-box از چندین فایل geosite که این مورد هم حداقل [فعلا](https://github.com/SagerNet/sing-box/issues/595) منتفیه.
3. صرفا تغییر نام iran-geosite.db به geosite.db در اسکریپت که کاربران هربار مجبور به تغییر نام نباشن و جایگزین کردن geosite پیشفرض با آن. مشکل این روش اینجاست که اکثرا از `geosite:category-ads-all` برای بستن تبلیغات سایت های غیر ایرانی استفاده میکنن که اینطوری این امکان از دست میره.
4. علاوه بر انجام مورد 3، میتونیم بخش `category-ads-all` و یا هر بخش دیگه ای رو هم از همون [domain-list-community](https://github.com/v2fly/domain-list-community) و یا حتی بهتر، از سورس های کامل تر و بهتری مثل [DNS Blocklists](https://github.com/hagezi/dns-blocklists) اضافه کنیم. من این کار رو در [فورک](https://github.com/chocolate4u/iran-hosted-domains/tree/adblock-all) خودم انجام دادم که میتونید ببینید. اینطوری با جایگزین کردن فایل geosite.db کاربران چیزی رو از دست نمیدن.

فقط مطمئن نیستم که با توجه به ماهیت این مخزن، بتونیم این کار رو انجام بدیم یا نه. (به نظرم چون فقط بستن دامنه های تبلیغاتی مدنظره، مشکلی نداشته باشه) برای همین این issue رو باز کردم که نظر شما رو راجع بهش بدونم و اگر که مشکلی نداشته باشیم، PR بدم.

پ.ن : سورس [DNS Blocklists](https://github.com/hagezi/dns-blocklists) حتی در سبک ترین [لیستش](https://github.com/hagezi/dns-blocklists#multi-light---light-protection-) (که من در فورکم استفاده کردم) بسیار بهتر از [domain-list-community](https://github.com/v2fly/domain-list-community) در بستن دامنه های تبلیغاتی عمل میکنه. همچنین [domain-list-community](https://github.com/v2fly/domain-list-community) بخش زیادی از لیست دامنه های تبلیغاتیش مربوط به دامنه های تبلیغاتی بومی چین هست که مورد نظر ما نیست. لایسنس این سورس هم MIT هست که با این مخزن سازگاره.

**Comment by bootmortis** [comment]
باید یه کم رو این مورد فکر کنم و نظر بقیه رو بپرسم
ما تا الان روی اینکه دومین‌های غیر مرتبط با ایران رو به ریپو اضافه نکنیم تاکید داشتیم
اگر مورد ۴ رو بخوایم انجام بدیم این زیر سوال می‌ره اما نظر خودم به اینه که همونطور که گفتید چون صرفا تبلیغاتی هست نباید زیاد مساله ساز بشه
قبل از PR حداقل دو سه روزی صبر کنید نظر باقی دوستان هم بدونیم این زیر

ممنون بابت پیشنهاد

**Comment by Graveyard9988** [comment]
> باید یه کم رو این مورد فکر کنم و نظر بقیه رو بپرسم ما تا الان روی اینکه دومین‌های غیر مرتبط با ایران رو به ریپو اضافه نکنیم تاکید داشتیم اگر مورد ۴ رو بخوایم انجام بدیم این زیر سوال می‌ره اما نظر خودم به اینه که همونطور که گفتید چون صرفا تبلیغاتی هست نباید زیاد مساله ساز بشه قبل از PR حداقل دو سه روزی صبر کنید نظر باقی دوستان هم بدونیم این زیر
> 
> ممنون بابت پیشنهاد

در فاز اول بهتره که دامین های تبلیغاتی خارجی فعلا در فایل geosite.db اعمال بشه چرا که v2ray قابلیت پشتیبانی از چند dat رو داره اما سینگ باکس فقط یک DB قبول می کنه، بنابراین بهتره گام به گام تغییرات صورت بگیره و بعید نیست بعدا سرویس های چ*ینی در ایران فعال بشن و تبلیغات اونها نیز به لیست افزوده بشه

**Comment by bootmortis** [comment]
@Graveyard9988 
اگر بنا به افزودن دومین‌های تبلیغاتی غیر ایران باشه، صرفا برای کلاینتایی اضافه می‌شه که قابلیت چندین geosite رو نداشته باشن، بقیه بدون تغییرا باقی می‌مونن.

**Comment by Chocolate4U** [comment]
از اونجایی که در کد فعلی فایل `db.` از روی `dat.` ساخته میشه، باید اول دامین های تبلیغاتی رو به فایل `dat.` اضافه کنیم و بعد از روی اون فایل `db.` رو بسازیم. اگر بخوایم دامین های تبلیغاتی غیر ایران فقط به فایل `db.` اضافه بشه میتونیم مثلا 2 تا فایل `dat.` بسازیم، یکی به صورت دست نخورده برای ریلیز فایل `iran.dat`  و یکی هم برای ساختن فایل `geosite.db` .
البته شاید روش های بهتری هم باشه برای این کار، @bootmortis نظرت چیه؟

**Comment by MasterKia** [comment]
> لایسنس این سورس هم MIT هست

نه، در عمل نیست. لایسنس رو حذف کردن:
https://github.com/hagezi/dns-blocklists/commit
/02dfafc67558f7152524ac480cfae59a0f97de9b




اون ریپو یک سری لیست ها رو گردآوری می‌کنه و در یک لیست قرار میده. بنابراین هر لیستی که ازش استفاده می‌کنن یک لایسنس جداگونه برای خودش داره.

مثلاً داره از لیست PersianBlockerHosts استفاده می‌کنه که تحت لایسنس AGPLv3 هست:
https://github.com/hagezi/dns-blocklists/blob/94244d7cdd072670dc71632cf9a20ab1fb12fac5/usedsources.md?plain=1#L120

**Comment by Chocolate4U** [comment]
> > لایسنس این سورس هم MIT هست
> 
> نه، در عمل نیست. لایسنس رو حذف کردن: https://github.com/hagezi/dns-blocklists/commit /02dfafc67558f7152524ac480cfae59a0f97de9b
> 
> اون ریپو یک سری لیست ها رو گردآوری می‌کنه و در یک لیست قرار میده. بنابراین هر لیستی که ازش استفاده می‌کنن یک لایسنس جداگونه برای خودش داره.
> 
> مثلاً داره از لیست PersianBlockerHosts استفاده می‌کنه که تحت لایسنس AGPLv3 هست: https://github.com/hagezi/dns-blocklists/blob/94244d7cdd072670dc71632cf9a20ab1fb12fac5/usedsources.md?plain=1#L120

ممنون که اشاره کردین، به این مورد دقت نکرده بودم. البته لیست مد نظر من یعنی [Multi LIGHT - Light protection](https://github.com/hagezi/dns-blocklists#multi-light---light-protection-) اکثرا از لیست های خود hagezi تشکیل شده که تحت لیسانس MIT بودن (هستن؟) . فقط دو سورس خارجی استفاده شده یعنی [Emerging-Malicious-Domain-Blocklist](https://github.com/manic-code/Emerging-Malicious-Domain-Blocklist) که لایسنس اون هم MIT هست و [d3host.txt](https://github.com/d3ward/toolz/blob/master/src/d3host.txt) که این مورد لایسنسش CC BY-NC-SA هست که خب در تناقض هست با این مخزن.
در هر صورت با توجه به مورد بالا و به علاوه این که لایسنس MIT این سورس هم حذف شده و این مخزن با استفاده از سورس های با لایسنس متفاوت مخالفه، استفاده از این لیست منتفی هست.
در صورتی که با این پیشنهاد موافقت شد، میتونیم از همون [domain-list-community](https://github.com/v2fly/domain-list-community) دامنه های تبلیغاتی رو اضافه کنیم.

**Comment by bootmortis** [comment]
> از اونجایی که در کد فعلی فایل `db.` از روی `dat.` ساخته میشه، باید اول دامین های تبلیغاتی رو به فایل `dat.` اضافه کنیم و بعد از روی اون فایل `db.` رو بسازیم. اگر بخوایم دامین های تبلیغاتی غیر ایران فقط به فایل `db.` اضافه بشه میتونیم مثلا 2 تا فایل `dat.` بسازیم، یکی به صورت دست نخورده برای ریلیز فایل `iran.dat` و یکی هم برای ساختن فایل `geosite.db` . البته شاید روش های بهتری هم باشه برای این کار، @bootmortis نظرت چیه؟


پایپلاین زیادی سنگین می‌شه دو تا `.dat`، به صورت کلی هم با اضافه کردن دومین‌های غیر مرتبط و تبلیغاتی توی `.dat` مخالفم، همینجوریش فایل زیادی سنگینه. (از وقتی که ای‌نماد اضافه شده).
اگر راه دیگه‌ای نیست بنظرم تو یک ریپوی دیگه (یا فورک) این مورد هندل بشه بهتره، این ریپو تمرکزش روی دومین‌های ایرانی هست و تخصصی روی تبلیغات تمرکزی نداره. ریپو برای این کار زیاده.

اینطور که متوجه شده مثل اینکه مشکل لایسنس هم داره سورس تبلیغاتی، اگر داره ارزش نداره که اطلاعاتش به این ریپو اضافه بشه.

**Comment by MasterKia** [comment]
برای مسدود کردن تبلیغات می‌تونید ازین فورک استفاده کنید:
https://github.com/MasterKia/iran-hosted-domains

دامنه های تبلیغاتی رو از لیست [PersianBlocker](https://github.com/MasterKia/PersianBlocker) می‌گیره.

**Comment by Chocolate4U** [comment]
> > از اونجایی که در کد فعلی فایل `db.` از روی `dat.` ساخته میشه، باید اول دامین های تبلیغاتی رو به فایل `dat.` اضافه کنیم و بعد از روی اون فایل `db.` رو بسازیم. اگر بخوایم دامین های تبلیغاتی غیر ایران فقط به فایل `db.` اضافه بشه میتونیم مثلا 2 تا فایل `dat.` بسازیم، یکی به صورت دست نخورده برای ریلیز فایل `iran.dat` و یکی هم برای ساختن فایل `geosite.db` . البته شاید روش های بهتری هم باشه برای این کار، @bootmortis نظرت چیه؟
> 
> پایپلاین زیادی سنگین می‌شه دو تا `.dat`، به صورت کلی هم با اضافه کردن دومین‌های غیر مرتبط و تبلیغاتی توی `.dat` مخالفم، همینجوریش فایل زیادی سنگینه. (از وقتی که ای‌نماد اضافه شده). اگر راه دیگه‌ای نیست بنظرم تو یک ریپوی دیگه (یا فورک) این مورد هندل بشه بهتره، این ریپو تمرکزش روی دومین‌های ایرانی هست و تخصصی روی تبلیغات تمرکزی نداره. ریپو برای این کار زیاده.
> 
> اینطور که متوجه شده مثل اینکه مشکل لایسنس هم داره سورس تبلیغاتی، اگر داره ارزش نداره که اطلاعاتش به این ریپو اضافه بشه.

اوکی پس من راهنما رو بر اساس همین فایل فعلی آپدیت میکنم و PR میدم.
این موارد رو هم اگر وقت کنم توی یه ریپوی دیگه انجام میدم که اگر کسی نیاز داشت به اون ها ارجاع کنه.
اگر مورد دیگه ای نیست این ایشو رو میتونیم ببندیم دیگه.

**Comment by ghost** [comment]
> 
> اینطور که متوجه شده مثل اینکه مشکل لایسنس هم داره سورس تبلیغاتی، اگر داره ارزش نداره که اطلاعاتش به این ریپو اضافه بشه.

یه سوال تغییر لایسنس دو سه تا کلیکه کلا. این‌که بخاطر یه لایسنس کلی کاربر به زحمت بیفته ارزش این کارا رو نداره. اگر از اول قصد ادغام این لیست با v2fly نبوده لزومی نداشته که حتما لایسنس MIT روی پروژه باشه؛ پس چرا لایسنس رو عوض نمی کنید؟

**Comment by bootmortis** [comment]
> یه سوال تغییر لایسنس دو سه تا کلیکه کلا. این‌که بخاطر یه لایسنس کلی کاربر به زحمت بیفته ارزش این کارا رو نداره. اگر از اول قصد ادغام این لیست با v2fly نبوده لزومی نداشته که حتما لایسنس MIT روی پروژه باشه؛ پس چرا لایسنس رو عوض نمی کنید؟

<div dir='rt'>

اشتباه متوجه شدید، لایسنس ریپوی تبلیغات محدود کرده مارو که از اطلاعاتشون استفاده کنیم. بحث در مورد ادغام این ریپو با v2fly نبوده اینجا. در مورد ادغام این ریپو با v2fly دلایلمون متفاوته که قبلا به maintainer های v2fly هم اعلام کردیم و اونا هم موافق بودن.

</div>
