### ISSUE TITLE
FoxyProxy ruleset

### ISSUE THREAD

**Issue by MasterKia** [bootmortis/iran-hosted-domains#88]
SwitchyOmega only works in Chrome (the Firefox version is unmaintained).
So Firefox users are using FoxyProxy instead:
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/

See: https://help.getfoxyproxy.org/index.php/knowledge-base/url-patterns/

Similar: https://github.com/bootmortis/iran-hosted-domains/issues/57

**Comment by Tirbod** [comment]
تو ورژن فعلی (7.5.1) استورش  نمیشه این تعداد دامنه اضافه کرد چون محدودیت حجم فایل داره ولی تو [ورژن 8](https://github.com/foxyproxy/browser-extension ) محدودیتی نیست و میشه از همون فایل SwitchyOmega هم استفاده کرد ولی یه مشکلی که فایل SwitchtyOmega هم برای خودش هم برای این داره اینه که 

`*example.com`

هم با `example.com` و ساب دامنه هاش مچ میشه هم با مثلا `fooexample.com`
