### ISSUE TITLE
Myirancell does not bypass

### ISSUE THREAD

**Issue by saeedt20** [bootmortis/iran-hosted-domains#90]
درود،
جدیدا روی مای ایرانسل کار نمیکنه و میگه وی پی ان باید خاموش شه.درصورتی قبلا همچین مشکلی نبود.

**Comment by shahin-io** [comment]
درود، 
ایرانسل اومده زرنگی کرده و یه درخواست به ادرس www.cloudflare.com گذاشته هنگام باز کردن سایتش. به همین دلیل پس از ریزالو این آدرس با آی پی سرور خارج متوجه میشه که فیلترشکن روشن هست. اگر سایت کلادفلر رو بزارید که دایرکت ریزالو بشه باز میشه!

**Comment by saeedt20** [comment]
تشکر با اضافه کردن کلودفلر حل شد مشکل👌
