### ISSUE TITLE
سوال در مورد category-ads-all

### ISSUE THREAD

**Issue by Graveyard9988** [bootmortis/iran-hosted-domains#91]
درود
آیا دستور category-ads-all در فایل iran.dat شما وجود دارد؟
چرا که می خواهم این دستور را به فایل شما در ابتدای کانفیگ کلش متا ارجاع دهم

**Comment by bootmortis** [comment]
خیر باید از فایل geosite ریپوی v2fly یا فورک‌هاش استفاده کنید.
فایل iran.dat صرفا شامل کتگوری‌های ir, other و ads هستش
