### ISSUE TITLE
آپدیت روش استفاده در نکوری

### ISSUE THREAD

**Issue by AbadanVpn** [bootmortis/iran-hosted-domains#95]
سلام 
بابت این کار بزرگی که انجام دادید خیلی ممنونم

یه خواهشی داشتم با توجه به اینکه Nekoray اپدیت داده و قسمت روتینگش تغییر پیدا کرده اگه امکان داره روش استفاده رو توی این نرم افزار رو آپدیت کنید متاسفانه من هر کاری کردم نتونستم راه بندازم این قسمت رو
خیلی ممنون

**Comment by bootmortis** [comment]
آپدیت شد.

**Comment by AbadanVpn** [comment]
خیلی ممنونم از شما
