### ISSUE TITLE
Nekobox routing issue

### ISSUE THREAD

**Issue by smsalehi** [bootmortis/iran-hosted-domains#96]
تو نکوباکس روتینگ عمل نمیکنه، یعنی وقتی vpn وصله سایت های ir باز نمیشن. همه مراحل مطابق آموزش انجام شده. 

![Screenshot_20230616-101521_NekoBox](https://github.com/bootmortis/iran-hosted-domains/assets/5753458/e1114fcb-212e-45fd-aebc-46e097b418f7)
![Screenshot_20230616-101529_NekoBox](https://github.com/bootmortis/iran-hosted-domains/assets/5753458/3d2bb78a-b394-4819-b173-8a7d6ae3249d)

"route": {
    "auto_detect_interface": true,
    "rules": [
      {
        "outbound": "dns-out",
        "port": [
          53
        ]
      },
      {
        "inbound": [
          "dns-in"
        ],
        "outbound": "dns-out"
      },
      {
        "geosite": [
          "ads"
        ],
        "outbound": "block"
      },
      {
        "domain_suffix": [
          ".ir"
        ],
        "outbound": "bypass"
      },
      {
        "geosite": [
          "other"
        ],
        "outbound": "bypass"
      },
      {
        "geoip": [
          "ir"
        ],
        "outbound": "bypass"
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block",
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
     }

**Comment by Tirbod** [comment]
اون direct dns ای که استفاده میکنید مشکل نداره؟ چون دیفالت خود نکوباکس فک کنم تو بیشتر اپراتور ها کار نده

**Comment by mu4um** [comment]
![Uploading Screenshot_20230822-215008.png…]()
این دو تا غیر فعال باشه، احتمالا درست میشه.

**Comment by mu4um** [comment]
![Uploading Screenshot_20230822-215008.png…]()
این دو تا غیر فعال باشه، احتمالا درست میشه.

**Comment by mu4um** [comment]
![Screenshot_20230822-215008](https://github.com/bootmortis/iran-hosted-domains/assets/34750114/e6597ab9-220d-4a8d-bfff-4fc54444efe8)
این دو تا غیر فعال باشه، احتمالا درست میشه.

**Comment by bootmortis** [comment]
اول اپدیت کنید اپ رو بعد از asset provider جدید که @Chocolate4U زحمتش رو کشیده اضافه کرده لطفا استفاده کنید.
https://github.com/MatsuriDayo/NekoBoxForAndroid/pull/331
