### ISSUE TITLE
Iran.dat, V2rayN Sing-Box core

### ISSUE THREAD

**Issue by Matin4359** [bootmortis/iran-hosted-domains#99]
Hi.
Iran.dat file and rules not working in V2rayN with Sing-Box core.
Please fix.
Thanks.

**Comment by ghost** [comment]
شما باید برای هسته singbox از iran.geosite.db استفاده کنید اموزش V2rayN هسته SingBox فعلا دردسترس نیست احتمالا آموزش nekoray برای هسته SingBox نزدیک باشه به مراحل اصلی.

**Comment by bootmortis** [comment]
از این asset provider استفاده کنید.
https://github.com/Chocolate4U/Iran-sing-box-rules/releases/latest
